Repository CoorpAcademy/components, pull requests merged in 2018-12, with the labels that each got.

#1409 update travis.yml remove matrix and scoping
  .travis.yml
Labels: pr: :wrench: Refactoring

#1418 Typing progressions
  package.json
  packages/@coorpacademy-player-services/src/analytics.js
  packages/@coorpacademy-player-services/src/definitions.js
  packages/@coorpacademy-player-services/src/recommendations.js
  packages/@coorpacademy-player-services/src/slides.js
  packages/@coorpacademy-player-services/src/test/analytics.send-progression-analytics.js
  packages/@coorpacademy-player-services/src/test/analytics.send-viewed-media-analytics.js
  packages/@coorpacademy-player-services/src/test/fixtures/data/chapter-rules.json
  packages/@coorpacademy-player-services/src/test/fixtures/data/levels.js
  packages/@coorpacademy-player-services/src/test/fixtures/data/levels.json
  packages/@coorpacademy-player-services/src/test/fixtures/data/progressions.js
  packages/@coorpacademy-player-services/src/test/fixtures/data/progressions.json
  packages/@coorpacademy-player-services/src/test/fixtures/data/recommendations.js
  packages/@coorpacademy-player-services/src/test/fixtures/data/recommendations.json
  packages/@coorpacademy-player-services/src/test/fixtures/data/slides.json
  packages/@coorpacademy-player-services/src/test/fixtures/progressions.js
  packages/@coorpacademy-player-services/src/test/fixtures/recommendations.js
  packages/@coorpacademy-player-services/src/test/fixtures/slides.js
  packages/@coorpacademy-player-services/src/types.js
  packages/@coorpacademy-progression-engine/src/create-progression/index.js
  packages/@coorpacademy-progression-engine/src/create-progression/test/index.js
  packages/@coorpacademy-progression-engine/src/index.js
  packages/@coorpacademy-progression-engine/src/reducers/test/validate.js
  packages/@coorpacademy-progression-engine/src/reducers/validate.js
  packages/@coorpacademy-progression-engine/src/test/update-state.js
  packages/@coorpacademy-progression-engine/src/types.js
Labels: pr: :lollipop: Enhancement

#1422 types for contents + progressions
  codecov.yml
  packages/@coorpacademy-player-services/src/content.js
  packages/@coorpacademy-player-services/src/definitions.js
  packages/@coorpacademy-player-services/src/index.js
  packages/@coorpacademy-player-services/src/progressions.js
  packages/@coorpacademy-player-services/src/recommendations.js
  packages/@coorpacademy-player-services/src/slides.js
  packages/@coorpacademy-player-services/src/test/answers.js
  packages/@coorpacademy-player-services/src/test/clues.js
  packages/@coorpacademy-player-services/src/test/content.js
  packages/@coorpacademy-player-services/src/test/extra-life.js
  packages/@coorpacademy-player-services/src/test/fixtures/content.js
  packages/@coorpacademy-player-services/src/test/fixtures/data/progressions.js
  packages/@coorpacademy-player-services/src/test/fixtures/levels.js
  packages/@coorpacademy-player-services/src/test/fixtures/progressions.js
  packages/@coorpacademy-player-services/src/test/fixtures/slides.js
  packages/@coorpacademy-player-services/src/test/next-content.js
  packages/@coorpacademy-player-services/src/test/progressions.js
  packages/@coorpacademy-player-services/src/test/recommendations.js
  packages/@coorpacademy-player-services/src/test/slides.js
  packages/@coorpacademy-progression-engine/package.json
  packages/@coorpacademy-progression-engine/src/create-progression/test/index.js
  packages/@coorpacademy-progression-engine/src/index.js
  packages/@coorpacademy-progression-engine/src/test/update-state.js
  packages/@coorpacademy-progression-engine/src/types.js
Labels: pr: :construction: Work In Progress

#1423 Typing answers + clues + exit nodes
  packages/@coorpacademy-player-services/src/answers.js
  packages/@coorpacademy-player-services/src/clues.js
  packages/@coorpacademy-player-services/src/definitions.js
  packages/@coorpacademy-player-services/src/exit-nodes.js
  packages/@coorpacademy-player-services/src/index.js
  packages/@coorpacademy-player-services/src/leaderboard.js
  packages/@coorpacademy-player-services/src/location.js
  packages/@coorpacademy-player-services/src/recommendations.js
  packages/@coorpacademy-player-services/src/test/answers.js
  packages/@coorpacademy-player-services/src/test/clues.js
  packages/@coorpacademy-player-services/src/test/exit-nodes.js
  packages/@coorpacademy-player-services/src/test/location.js
  packages/@coorpacademy-progression-engine/src/index.js
Labels: RFR, pr: :lollipop: Enhancement

#1424 [SC-37] [#7] List items should be justified on the left
  packages/@coorpacademy-components/src/molecule/setup-cohort-item/style.css
Labels: pr: :bug: Bug Fix, pr: :construction: Work In Progress

#1434 Bugfix lerna
  README.md
  package.json
  packages/@coorpacademy-components/package.json
  packages/@coorpacademy-css-modules-require-hook/package.json
  packages/@coorpacademy-history/package.json
  packages/@coorpacademy-nova-icons/package.json
  packages/@coorpacademy-redux-history/package.json
  packages/@coorpacademy-redux-router/package.json
  packages/@coorpacademy-redux-task/package.json
  packages/@coorpacademy-translate/package.json
  packages/@coorpacademy-treantjs-adapter-angular/package.json
  packages/@coorpacademy-treantjs-adapter-dust/package.json
  packages/@coorpacademy-webpack-config/package.json
  yarn.lock
Labels: pr: :bug: Bug Fix

#1435 fix dependcies issues
  packages/@coorpacademy-components/package.json
  packages/@coorpacademy-components/src/hoc/animation/index.js
  packages/@coorpacademy-nova-icons/package.json
  packages/@coorpacademy-player-services/package.json
  packages/@coorpacademy-player-store/package.json
  packages/@coorpacademy-player-web/package.json
  packages/@coorpacademy-translate/package.json
  packages/@coorpacademy-webpack-config/package.json
  yarn.lock
Labels: pr: :bug: Bug Fix
