Repository CoorpAcademy/components, pull requests merged in 2018-11, with the labels that each got.

#1396 update style and behavior of the select multiple component
  packages/@coorpacademy-components/src/molecule/brand-form-group/index.js
  packages/@coorpacademy-components/src/molecule/brand-form-group/style.css
  packages/@coorpacademy-components/src/molecule/brand-form-group/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/select-multiple/index.js
  packages/@coorpacademy-components/src/molecule/select-multiple/style.css
  packages/@coorpacademy-components/src/molecule/select-multiple/test/index.js
  packages/@coorpacademy-components/src/molecule/select-multiple/test/snapshots/index.js.md
  packages/@coorpacademy-components/src/molecule/select-multiple/test/snapshots/index.js.snap
  packages/@coorpacademy-components/src/molecule/titled-checkbox/index.js
  packages/@coorpacademy-components/src/molecule/titled-checkbox/style.css
  packages/@coorpacademy-components/src/variables/colors.css
  packages/@coorpacademy-components/src/variables/fonts.css
Labels: pr: :rocket: New feature

#1398 build only changed packages
  .travis.yml
Labels: pr: :lollipop: Enhancement

#1403 Clean pakagesjson
  packages/@coorpacademy-components/package.json
  packages/@coorpacademy-css-modules-require-hook/package.json
  packages/@coorpacademy-history/package.json
  packages/@coorpacademy-nova-icons/package.json
  packages/@coorpacademy-progression-engine/package.json
  packages/@coorpacademy-redux-history/package.json
  packages/@coorpacademy-redux-router/package.json
  packages/@coorpacademy-redux-task/package.json
  packages/@coorpacademy-translate/package.json
  packages/@coorpacademy-treantjs-adapter-angular/package.json
  packages/@coorpacademy-treantjs-adapter-dust/package.json
  packages/@coorpacademy-webpack-config/package.json
  yarn.lock
Labels: pr: :lollipop: Enhancement

#1394 Launch lerna
  .eslintignore
  .travis.yml
  codecov.yml
  lerna.json
  package.json
  packages/@coorpacademy-app-player/.eslintignore
  packages/@coorpacademy-app-player/.eslintrc
  packages/@coorpacademy-app-player/.nycrc
  packages/@coorpacademy-app-player/package.json
  packages/@coorpacademy-components/.eslintignore
  packages/@coorpacademy-components/.eslintrc
  packages/@coorpacademy-components/.nycrc
  packages/@coorpacademy-components/package.json
  packages/@coorpacademy-css-modules-require-hook/.eslintignore
  packages/@coorpacademy-css-modules-require-hook/.eslintrc
  packages/@coorpacademy-css-modules-require-hook/package.json
  packages/@coorpacademy-history/.eslintignore
  packages/@coorpacademy-history/.eslintrc
  packages/@coorpacademy-history/package.json
  packages/@coorpacademy-nova-icons/.eslintignore
  packages/@coorpacademy-nova-icons/.eslintrc
  packages/@coorpacademy-nova-icons/package.json
  packages/@coorpacademy-progression-engine/.eslintignore
  packages/@coorpacademy-progression-engine/.eslintrc
  packages/@coorpacademy-progression-engine/.nycrc
  packages/@coorpacademy-progression-engine/package.json
  packages/@coorpacademy-redux-history/.eslintignore
  packages/@coorpacademy-redux-history/.eslintrc
  packages/@coorpacademy-redux-history/package.json
  packages/@coorpacademy-redux-router/.eslintignore
  packages/@coorpacademy-redux-router/.eslintrc
  packages/@coorpacademy-redux-router/package.json
  packages/@coorpacademy-redux-task/.eslintignore
  packages/@coorpacademy-redux-task/.eslintrc
  packages/@coorpacademy-redux-task/package.json
  packages/@coorpacademy-translate/.eslintignore
  packages/@coorpacademy-translate/.eslintrc
  packages/@coorpacademy-translate/.nycrc
  packages/@coorpacademy-translate/package.json
  packages/@coorpacademy-treantjs-adapter-angular/.eslintignore
  packages/@coorpacademy-treantjs-adapter-angular/.eslintrc
  packages/@coorpacademy-treantjs-adapter-angular/package.json
  packages/@coorpacademy-treantjs-adapter-dust/.eslintignore
  packages/@coorpacademy-treantjs-adapter-dust/.eslintrc
  packages/@coorpacademy-treantjs-adapter-dust/package.json
  packages/@coorpacademy-webpack-config/.eslintignore
  packages/@coorpacademy-webpack-config/.eslintrc
  packages/@coorpacademy-webpack-config/.nycrc
  packages/@coorpacademy-webpack-config/package.json
  yarn.lock
Labels: pr: :wrench: Refactoring

#1405 remove overflows
  packages/@coorpacademy-components/src/template/app-player/player/slides/footer/style.css
  packages/@coorpacademy-components/src/template/app-player/player/slides/header/style.css
  packages/@coorpacademy-components/src/template/app-player/player/slides/style.css
Labels: pr: :bug: Bug Fix
