Repository CoorpAcademy/components, pull requests merged in 2019-11, with the labels that each got.

#1577 Tweaking the travis build
  .travis.yml
  .update-node.json
  package.json
  packages/@coorpacademy-components/package.json
  packages/@coorpacademy-history/package.json
  packages/@coorpacademy-player-services/package.json
  packages/@coorpacademy-player-store/package.json
  packages/@coorpacademy-player-web/package.json
  packages/@coorpacademy-progression-engine/package.json
  packages/@coorpacademy-redux-history/package.json
  packages/@coorpacademy-redux-router/package.json
  packages/@coorpacademy-redux-task/package.json
  packages/@coorpacademy-translate/package.json
  packages/@coorpacademy-treantjs-adapter-angular/package.json
  packages/@coorpacademy-treantjs-adapter-dust/package.json
  packages/@coorpacademy-webpack-config/package.json
  scripts/trigger-dependent-builds.sh
  yarn.lock
Labels: pr: :lollipop: Enhancement

#1640 Fix e2e window.jwplayer error
  packages/@coorpacademy-components/src/molecule/video-player/jwplayer.js
Labels: pr: :bug: Bug Fix

#1643 Give proper name to react adapters
  .travis.yml
  README.md
  package.json
  packages/@coorpacademy-react-adapter-angular/.babelrc
  packages/@coorpacademy-react-adapter-angular/.eslintignore
  packages/@coorpacademy-react-adapter-angular/.eslintrc
  packages/@coorpacademy-react-adapter-angular/ava.config.js
  packages/@coorpacademy-react-adapter-angular/demo/app.js
  packages/@coorpacademy-react-adapter-angular/demo/index.js
  packages/@coorpacademy-react-adapter-angular/demo/webpack.config.js
  packages/@coorpacademy-react-adapter-angular/nyc.config.js
  packages/@coorpacademy-react-adapter-angular/package.json
  packages/@coorpacademy-react-adapter-angular/src/index.js
  packages/@coorpacademy-react-adapter-angular/src/test/index.js
  packages/@coorpacademy-react-adapter-dust/.babelrc
  packages/@coorpacademy-react-adapter-dust/.eslintignore
  packages/@coorpacademy-react-adapter-dust/.eslintrc
  packages/@coorpacademy-react-adapter-dust/ava.config.js
  packages/@coorpacademy-react-adapter-dust/nyc.config.js
  packages/@coorpacademy-react-adapter-dust/package.json
  packages/@coorpacademy-react-adapter-dust/src/index.js
  packages/@coorpacademy-react-adapter-dust/src/test/index.js
  packages/@coorpacademy-treantjs-adapter-angular/README.md
  packages/@coorpacademy-treantjs-adapter-angular/package.json
  packages/@coorpacademy-treantjs-adapter-dust/README.md
  packages/@coorpacademy-treantjs-adapter-dust/package.json
Labels: pr: :collision: Breaking Change!, pr: :lollipop: Enhancement

#1644 Clean up the monorepo
  packages/@coorpacademy-treantjs-adapter-angular/README.md
  packages/@coorpacademy-treantjs-adapter-angular/package.json
  packages/@coorpacademy-treantjs-adapter-dust/README.md
  packages/@coorpacademy-treantjs-adapter-dust/package.json
Labels: pr: :wrench: Refactoring

#1646 Disableable double step
  packages/@coorpacademy-components/.storybook/webpack.config.js
  packages/@coorpacademy-components/src/atom/input-doublestep/index.js
  packages/@coorpacademy-components/src/atom/input-doublestep/style.css
  packages/@coorpacademy-components/src/atom/input-doublestep/test/fixtures/disabled.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement

#1647 Autoclose on confirm :door:
  packages/@coorpacademy-components/src/atom/input-doublestep/index.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement

#1648 add props type cockpit for select-multiple component
  packages/@coorpacademy-components/src/molecule/select-multiple/index.js
  packages/@coorpacademy-components/src/molecule/select-multiple/style.css
  packages/@coorpacademy-components/src/molecule/select-multiple/test/fixtures/checked-cockpit-theme.js
  packages/@coorpacademy-components/src/molecule/select-multiple/test/fixtures/checked-setup-theme.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :lollipop: Enhancement

#1649 new tab design
  packages/@coorpacademy-components/src/molecule/module-bubble/index.js
  packages/@coorpacademy-components/src/molecule/module-bubble/style.css
  packages/@coorpacademy-components/src/molecule/module-card/index.js
  packages/@coorpacademy-components/src/molecule/scope-tabs/index.js
  packages/@coorpacademy-components/src/molecule/scope-tabs/style.css
Labels: pr: :lollipop: Enhancement

#1651 add sticky block on discipline page
  packages/@coorpacademy-components/src/template/common/discipline/index.js
  packages/@coorpacademy-components/src/template/common/discipline/style.css
Labels: pr: :lollipop: Enhancement

#1618 using promise.all for selectProgression
  packages/@coorpacademy-player-services/src/progressions.js
  packages/@coorpacademy-player-store/src/actions/ui/progressions.js
  packages/@coorpacademy-player-store/src/actions/ui/test/answers-validation/check-accordion.js
  packages/@coorpacademy-player-store/src/actions/ui/test/extra-life.js
  packages/@coorpacademy-player-store/src/actions/ui/test/progressions.js
  packages/@coorpacademy-player-web/sandbox/fixtures/chapters.js
  packages/@coorpacademy-player-web/sandbox/fixtures/index.js
  packages/@coorpacademy-player-web/sandbox/fixtures/progressions.js
  packages/@coorpacademy-player-web/src/map-state-to-props/test/popin-correction.create-header-cta.js
Labels: enhancement, pr: :wrench: Refactoring

#1653 extralife overlay = no autoplay
  packages/@coorpacademy-components/src/molecule/resource-player/index.js
  packages/@coorpacademy-components/src/molecule/resource-player/test/fixtures/jwplayer-with-overlay.js
  packages/@coorpacademy-components/src/molecule/resource-player/test/overlay.js
  packages/@coorpacademy-components/src/molecule/video-player/index.js
  packages/@coorpacademy-components/src/molecule/video-player/jwplayer.js
  packages/@coorpacademy-components/src/molecule/video-player/test/fixtures/jwplayer-with-subtitles.js
  packages/@coorpacademy-components/src/molecule/video-player/test/fixtures/jwplayer.js
  packages/@coorpacademy-components/src/molecule/video-player/test/fixtures/kontiki.js
  packages/@coorpacademy-components/src/molecule/video-player/test/fixtures/mp4.js
  packages/@coorpacademy-components/src/molecule/video-player/test/index.js
  packages/@coorpacademy-components/src/molecule/video-player/test/jwplayer.js
Labels: pr: :bug: Bug Fix
