Repository CoorpAcademy/components, pull requests merged in 2019-07, with the labels that each got.

#1587 Fix issues of component "molecule/card-with-buttons" & "template/battle-requests"
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/molecule/card-with-button/index.js
  packages/@coorpacademy-components/src/molecule/card-with-button/style.css
  packages/@coorpacademy-components/src/molecule/card-with-button/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/card-with-button/test/fixtures/with-avatar.js
  packages/@coorpacademy-components/src/molecule/card-with-button/test/fixtures/without-label.js
  packages/@coorpacademy-components/src/molecule/card-with-button/with-avatar.css
  packages/@coorpacademy-components/src/template/battle-requests/index.js
  packages/@coorpacademy-components/src/template/battle-requests/style.css
  packages/@coorpacademy-components/src/template/battle-requests/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/battle/index.js
  packages/@coorpacademy-components/src/template/battle/style.css
  packages/@coorpacademy-components/src/template/battle/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/battles-desktop/index.js
  packages/@coorpacademy-components/src/template/battles-desktop/style.css
  packages/@coorpacademy-components/src/template/battles-desktop/test/fixtures/default.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :bug: Bug Fix

#1593 Add missing fill attribute for mail icons
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/mail-inbox-document.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/mail-inbox-document.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/mail-inbox.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/mail-inbox.native.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/mail-inbox-document.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/mail-inbox.svg
Labels: pr: :bug: Bug Fix

#1596 Make the videos state independent of content one
  packages/@coorpacademy-player-services/src/definitions.js
  packages/@coorpacademy-player-services/src/videos.js
  packages/@coorpacademy-player-store/src/actions/api/test/videos.js
  packages/@coorpacademy-player-store/src/actions/api/videos.js
  packages/@coorpacademy-player-store/src/definitions/models.js
  packages/@coorpacademy-player-store/src/definitions/redux.js
  packages/@coorpacademy-player-store/src/definitions/services/index.js
  packages/@coorpacademy-player-store/src/definitions/services/videos.js
  packages/@coorpacademy-player-store/src/index.js
  packages/@coorpacademy-player-store/src/reducers/data/index.js
  packages/@coorpacademy-player-store/src/reducers/data/test/videos.js
  packages/@coorpacademy-player-store/src/reducers/data/videos.js
  packages/@coorpacademy-player-store/src/test/index.js
  packages/@coorpacademy-player-store/src/utils/state-extract.js
  packages/@coorpacademy-player-store/src/utils/test/state-extract.js
Labels: pr: :wrench: Refactoring

#1598 Fix videos export and add tests in player-services
  packages/@coorpacademy-player-services/src/index.js
  packages/@coorpacademy-player-services/src/test/fixtures/data/videos.js
  packages/@coorpacademy-player-services/src/test/fixtures/index.js
  packages/@coorpacademy-player-services/src/test/fixtures/videos.js
  packages/@coorpacademy-player-services/src/test/index.js
  packages/@coorpacademy-player-services/src/test/videos.js
Labels: pr: :bug: Bug Fix

#1599 Add entities to videos initial state
  packages/@coorpacademy-player-store/src/reducers/data/test/videos.js
  packages/@coorpacademy-player-store/src/reducers/data/videos.js
Labels: pr: :wrench: Refactoring

#1597 Fix cards Battle
  packages/@coorpacademy-components/src/molecule/card-with-button/index.js
  packages/@coorpacademy-components/src/molecule/card-with-button/style.css
  packages/@coorpacademy-components/src/molecule/card-with-button/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/card-with-button/test/fixtures/with-avatar.js
  packages/@coorpacademy-components/src/molecule/card-with-button/test/fixtures/without-label.js
  packages/@coorpacademy-components/src/template/battle-requests/index.js
  packages/@coorpacademy-components/src/template/battle-requests/style.css
  packages/@coorpacademy-components/src/template/battle-requests/test/fixtures/default.js
Labels: pr: :lollipop: Enhancement

#1601 Export RecommendationAPI type
  packages/@coorpacademy-player-services/src/index.js
Labels: pr: :wrench: Refactoring

#1602 Adding anchors to forum and comments :anchor:
  packages/@coorpacademy-components/src/molecule/forum/forum-post/index.js
  packages/@coorpacademy-components/src/organism/discussion/index.js
Labels: pr: :lollipop: Enhancement

#1604 fix component battle-requests
  packages/@coorpacademy-components/src/atom/avatar/style.css
  packages/@coorpacademy-components/src/molecule/card-with-button/style.css
  packages/@coorpacademy-components/src/template/battle-requests/style.css
Labels: pr: :bug: Bug Fix
