Repository CoorpAcademy/components, pull requests merged in 2019-10, with the labels that each got.

#1630 Fix findBestOf function
  packages/@coorpacademy-player-services/src/progressions.js
  packages/@coorpacademy-player-services/src/test/progressions.js
  packages/@coorpacademy-player-store/src/definitions/services/progressions.js
  packages/@coorpacademy-player-web/sandbox/fixtures/progressions.js
Labels: pr: :bug: Bug Fix

#1631 Add ability to force best score refresh
  packages/@coorpacademy-player-store/src/actions/api/progressions.js
  packages/@coorpacademy-player-store/src/actions/api/test/progressions.fetch-bestof.js
Labels: pr: :lollipop: Enhancement

#1633 Add disciplineUniversalRef on LevelAPI type
  packages/@coorpacademy-player-services/src/definitions.js
  packages/@coorpacademy-player-services/src/test/fixtures/data/levels.js
  packages/@coorpacademy-player-store/src/definitions/models.js
  packages/@coorpacademy-player-web/sandbox/fixtures/data/levels.json
Labels: enhancement

#1635 add description to select field
  packages/@coorpacademy-components/src/atom/select/index.js
  packages/@coorpacademy-components/src/atom/select/style.css
  packages/@coorpacademy-components/src/organism/brand-form/test/fixtures/manageusers-edit.js
Labels: pr: :lollipop: Enhancement

#1567 activity page with hidden course
  packages/@coorpacademy-components/src/template/activity/progression-item.css
  packages/@coorpacademy-components/src/template/activity/progression-item.js
  packages/@coorpacademy-components/src/template/activity/test/fixtures/all-engines.js
  packages/@coorpacademy-components/src/template/activity/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/activity/test/progression-item-test.js
Labels: pr: :lollipop: Enhancement

#1637 Remove useless border
  packages/@coorpacademy-components/src/molecule/hero/style.css
Labels: pr: :bug: Bug Fix
