Repository CoorpAcademy/components, pull requests merged in 2019-05, with the labels that each got.

#1562 Change text align
  packages/@coorpacademy-components/src/template/back-office/brand-update/style.css
Labels: pr: :lollipop: Enhancement

#1560 Add types for nova-icons package
  flow-typed/custom/react-native-svg_vx.x.x.js
  packages/@coorpacademy-nova-icons/.flowconfig
  packages/@coorpacademy-nova-icons/package.json
  packages/@coorpacademy-nova-icons/scripts/generate-icons.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/src/types.js
  packages/@coorpacademy-nova-icons/src/types.native.js
  yarn.lock
Labels: pr: :wrench: Refactoring

#1568 Add authentication mobile icons
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/magic-wand.1.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/magic-wand.1.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/profile.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/profile.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/mobilephone/qr-code.1.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/mobilephone/qr-code.1.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/network/network-mobile.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/network/network-mobile.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/shopping/qr-code.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/shopping/qr-code.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/magic-wand.1.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/profile.svg
Labels: pr: :rocket: New feature

#1564 Fix button (get-the-app)
  packages/@coorpacademy-components/src/organism/get-the-app/index.js
  packages/@coorpacademy-components/src/organism/get-the-app/style.css
  packages/@coorpacademy-components/src/organism/get-the-app/test/fixtures/default.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement

#1574 Remove hover effect from disabled button
  packages/@coorpacademy-components/src/atom/button/index.js
  packages/@coorpacademy-components/src/atom/button/style.css
Labels: pr: :bug: Bug Fix

#1576 Fix SVG properties
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/magic-wand.1.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/magic-wand.1.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/profile.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/profile.native.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/magic-wand.1.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/profile.svg
Labels: pr: :bug: Bug Fix

#1559 addings component avatar/battle/battles-desktop
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/atom/avatar/index.js
  packages/@coorpacademy-components/src/atom/avatar/style.css
  packages/@coorpacademy-components/src/atom/avatar/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/battle-request/index.js
  packages/@coorpacademy-components/src/molecule/battle-request/style.css
  packages/@coorpacademy-components/src/template/battle/index.js
  packages/@coorpacademy-components/src/template/battle/style.css
  packages/@coorpacademy-components/src/template/battle/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/battles-desktop/index.js
  packages/@coorpacademy-components/src/template/battles-desktop/style.css
  packages/@coorpacademy-components/src/template/battles-desktop/test/fixtures/default.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :rocket: New feature
