Repository CoorpAcademy/components, pull requests merged in 2019-08, with the labels that each got.

#1609 Add v2 configuration for microlearning
  packages/@coorpacademy-progression-engine/src/config/microlearning.js
  packages/@coorpacademy-progression-engine/src/config/test/get-config-for-progression.js
  packages/@coorpacademy-progression-engine/src/config/test/get-config.js
Labels: pr: :rocket: New feature

#1610 Progression engine version override
  packages/@coorpacademy-progression-engine/src/create-progression/index.js
  packages/@coorpacademy-progression-engine/src/create-progression/test/index.js
Labels: pr: :rocket: New feature

#1613 Disable lives in correction popin when lives are disabled
  packages/@coorpacademy-player-web/src/map-state-to-props/popin-correction.js
  packages/@coorpacademy-player-web/src/map-state-to-props/test/popin-correction.js
  packages/@coorpacademy-progression-engine/src/config/microlearning.js
  packages/@coorpacademy-progression-engine/src/config/test/get-config-for-progression.js
  packages/@coorpacademy-progression-engine/src/config/test/get-config.js
Labels: pr: :rocket: New feature

#1614 Embed regenerator-runtime in the Webpack Config
  packages/@coorpacademy-webpack-config/package.json
Labels: pr: :lollipop: Enhancement

#1616 Fix player store type
  packages/@coorpacademy-player-store/src/definitions/redux.js
Labels: pr: :wrench: Refactoring
