Repository CoorpAcademy/components, pull requests merged in 2019-01, with the labels that each got.

#1459 Remove file created by Transifex
  packages/@coorpacademy-app-player/locales/fr/player.json
Labels: pr: :wrench: Refactoring

#1463 Fix/typing issues
  packages/@coorpacademy-player-services/src/clues.js
  packages/@coorpacademy-player-services/src/content.js
  packages/@coorpacademy-player-services/src/definitions.js
  packages/@coorpacademy-player-services/src/index.js
  packages/@coorpacademy-player-web/README.md
  packages/@coorpacademy-progression-engine/src/compute-next-step/test/fixtures/slides.js
  packages/@coorpacademy-progression-engine/src/index.js
  packages/@coorpacademy-progression-engine/src/types.js
Labels: pr: :construction: Work In Progress

#1464 Fix/improve type
  packages/@coorpacademy-player-services/src/definitions.js
  packages/@coorpacademy-progression-engine/src/test/check-answer-correctness.qcm-graphic.js
  packages/@coorpacademy-progression-engine/src/types.js
Labels: pr: :bug: Bug Fix
