Repository CoorpAcademy/components, pull requests merged in 2019-02, with the labels that each got.

#1481 Fix/improve flow
  packages/@coorpacademy-player-services/src/definitions.js
  packages/@coorpacademy-player-services/src/test/fixtures/recommendations.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement

#1487 Export some types and const
  packages/@coorpacademy-player-store/src/index.js
  packages/@coorpacademy-progression-engine/src/index.js
Labels: pr: :wrench: Refactoring

#1488 Fix failing test
  packages/@coorpacademy-player-store/src/test/index.js
Labels: pr: :wrench: Refactoring

#1492 Explicit export for clues
  packages/@coorpacademy-player-store/src/index.js
Labels: pr: :wrench: Refactoring

#1493 fix Template question
  packages/@coorpacademy-progression-engine/src/types.js
Labels: pr: :lollipop: Enhancement
