Repository CoorpAcademy/components, pull requests merged in 2020-02, with the labels that each got.

#1680 Create Drag and Drop V2
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/package.json
  packages/@coorpacademy-components/src/molecule/drag-and-drop/common.css
  packages/@coorpacademy-components/src/molecule/drag-and-drop/index.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/overlay.css
  packages/@coorpacademy-components/src/molecule/drag-and-drop/overlay.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/placeholder.css
  packages/@coorpacademy-components/src/molecule/drag-and-drop/placeholder.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/preview.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/style.css
  packages/@coorpacademy-components/src/molecule/drag-and-drop/test/dragging.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/test/fixtures/errored.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/test/fixtures/loading.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/test/fixtures/with-image.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/test/fixtures/with-video.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/upload-report.css
  packages/@coorpacademy-components/src/molecule/drag-and-drop/upload-report.js
  packages/@coorpacademy-components/storybook/components.js
  yarn.lock
Labels: pr: :lollipop: Enhancement, pr: :rocket: New feature

#1684 all platforms - modification wording
  packages/@coorpacademy-app-player/locales/en/player.json
Labels: pr: :lollipop: Enhancement

#1688 Fixed news crop
  packages/@coorpacademy-components/src/molecule/news/style.css
Labels: pr: :bug: Bug Fix
