Repository CoorpAcademy/components, pull requests merged in 2020-10, with the labels that each got.

#1799 Teams dashboard
  packages/@coorpacademy-components/src/molecule/card-content/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/style.css
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/link-only.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/teams.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/header.js
  packages/@coorpacademy-components/src/template/teams-dashboard/index.js
  packages/@coorpacademy-components/src/template/teams-dashboard/style.css
  packages/@coorpacademy-components/src/template/teams-dashboard/test/fixtures/default.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :rocket: New feature

#1802 fix progression bar style (space left behind) when it is Nil
  packages/@coorpacademy-components/src/molecule/card-content/index.js
  packages/@coorpacademy-components/src/molecule/card-content/style.css
  packages/@coorpacademy-components/src/molecule/card-content/test/fixtures/card-no-progress-bar.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :wrench: Refactoring

#1804 Fix header on IE
  packages/@coorpacademy-components/src/organism/mooc-header/style.css
Labels: bug

#1806 External content player without header and footer
  packages/@coorpacademy-components/src/template/external-course/index.js
  packages/@coorpacademy-components/src/template/external-course/test/fixtures/article.js
  packages/@coorpacademy-components/src/template/external-course/test/fixtures/h5p.js
  packages/@coorpacademy-components/src/template/external-course/test/fixtures/podcast-cockpit-mode.js
  packages/@coorpacademy-components/src/template/external-course/test/fixtures/podcast-no-background.js
  packages/@coorpacademy-components/src/template/external-course/test/fixtures/video.js
  packages/@coorpacademy-components/src/template/external-course/test/on-click.js
Labels: enhancement
