Repository CoorpAcademy/components, pull requests merged in 2020-12, with the labels that each got.

#1813 add teams popin
  packages/@coorpacademy-components/package.json
  packages/@coorpacademy-components/src/molecule/teams-popin/index.js
  packages/@coorpacademy-components/src/molecule/teams-popin/style.css
  packages/@coorpacademy-components/src/molecule/teams-popin/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/teams-popin/test/fixtures/login-faild.js
  packages/@coorpacademy-components/src/molecule/teams-popin/test/fixtures/login.js
  packages/@coorpacademy-components/src/molecule/teams-popin/test/fixtures/not-teams-account.js
  packages/@coorpacademy-components/src/molecule/teams-popin/test/fixtures/without-button.js
  packages/@coorpacademy-components/src/molecule/teams-popin/test/fixtures/wrong.js
  packages/@coorpacademy-components/storybook/components.js
  yarn.lock
Labels: pr: :rocket: New feature

#1817 move the search bar below the notification
  packages/@coorpacademy-components/src/molecule/filters/style.css
Labels: bug

#1818 Skip content fetch when validating answer[mobile]
  packages/@coorpacademy-player-store/src/actions/ui/answers.js
  packages/@coorpacademy-player-store/src/actions/ui/test/answers-validation/check-accordion.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement

#1820 adds loader to teams dashboard
  packages/@coorpacademy-components/src/template/teams-dashboard/index.js
  packages/@coorpacademy-components/src/template/teams-dashboard/style.css
  packages/@coorpacademy-components/src/template/teams-dashboard/test/dashboard.js
  packages/@coorpacademy-components/src/template/teams-dashboard/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/teams-dashboard/test/fixtures/is-loading.js
  packages/@coorpacademy-components/storybook/components.js
  yarn.lock
Labels: pr: :lollipop: Enhancement

#1821 [Teams] add loader to popin
  packages/@coorpacademy-components/src/molecule/teams-popin/index.js
  packages/@coorpacademy-components/src/molecule/teams-popin/style.css
  packages/@coorpacademy-components/src/molecule/teams-popin/test/fixtures/loading.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :rocket: New feature
