Repository CoorpAcademy/components, pull requests merged in 2020-04, with the labels that each got.

#1699 Fix news for ie11
  packages/@coorpacademy-components/src/molecule/news/style.css
Labels: pr: :bug: Bug Fix

#1702 added graphics improvements
  packages/@coorpacademy-components/src/molecule/card-content/index.js
  packages/@coorpacademy-components/src/molecule/card-content/style.css
  packages/@coorpacademy-components/src/molecule/card/index.js
  packages/@coorpacademy-components/src/molecule/card/style.css
Labels: pr: :lollipop: Enhancement

#1704 Mutualize logic about question cta state
  packages/@coorpacademy-player-store/src/test/index.js
  packages/@coorpacademy-player-store/src/utils/state-extract.js
  packages/@coorpacademy-player-store/src/utils/test/state-extract.js
  packages/@coorpacademy-player-web/src/map-state-to-props/player.js
Labels: pr: :wrench: Refactoring

#1705 Export missing ExitNodesService type
  packages/@coorpacademy-player-services/src/index.js
Labels: pr: :lollipop: Enhancement

#1712 Fixing glitch on adaptive when switching slides or loading courses
  packages/@coorpacademy-player-store/src/definitions/models.js
  packages/@coorpacademy-player-store/src/test/index.js
  packages/@coorpacademy-player-store/src/utils/state-extract.js
  packages/@coorpacademy-player-store/src/utils/test/state-extract.js
  packages/@coorpacademy-player-web/src/map-state-to-props/player.js
Labels: pr: :bug: Bug Fix, pr: :construction: Work In Progress
