Repository CoorpAcademy/components, pull requests merged in 2020-06, with the labels that each got.

#1713 (feat) Add LMS to brand update template
  packages/@coorpacademy-components/src/molecule/brand-tabs/test/fixtures/lms.js
  packages/@coorpacademy-components/src/organism/brand-form/test/fixtures/lms.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lms-error.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lms-modified.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lms-success.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lms.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :rocket: New feature

#1740 [COMP] Add InputDoublestep to SetupSlide
  packages/@coorpacademy-components/src/atom/input-doublestep/index.js
  packages/@coorpacademy-components/src/atom/input-doublestep/style.css
  packages/@coorpacademy-components/src/molecule/setup-slide/index.js
  packages/@coorpacademy-components/src/molecule/setup-slide/test/fixtures/default.js
Labels: pr: :lollipop: Enhancement

#1741 fix current step for new lesson
  packages/@coorpacademy-components/src/template/app-player/player/slides/index.js
  packages/@coorpacademy-components/src/template/app-player/player/slides/test/fixtures/qcm-see-lesson-no-step.js
  packages/@coorpacademy-components/storybook/components.js
Labels: DO NOT MERGE

#1743 [comp] Sync LMS fixtures and reset isOpenValues when item is added or removed
  packages/@coorpacademy-components/src/organism/accordion/toggler/index.js
  packages/@coorpacademy-components/src/organism/brand-form/test/fixtures/lms.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lms-error.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lms-modified.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lms-success.js
Labels: pr: :lollipop: Enhancement

#1746 Add external content button
  packages/@coorpacademy-components/src/molecule/external-content-button/index.js
  packages/@coorpacademy-components/src/molecule/external-content-button/style.css
  packages/@coorpacademy-components/src/molecule/external-content-button/test/fixtures/article.js
  packages/@coorpacademy-components/src/molecule/external-content-button/test/fixtures/podcast.js
  packages/@coorpacademy-components/src/molecule/external-content-button/test/fixtures/scorm.js
  packages/@coorpacademy-components/src/molecule/external-content-button/test/fixtures/video.js
  packages/@coorpacademy-components/src/molecule/external-content-button/test/on-click.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :rocket: New feature

#1755 Fix shuffle
  packages/@coorpacademy-player-web/src/map-state-to-props/answer.js
  packages/@coorpacademy-player-web/src/map-state-to-props/player.js
  packages/@coorpacademy-player-web/src/map-state-to-props/popin-correction.js
  packages/@coorpacademy-player-web/src/map-state-to-props/popin-end.js
  packages/@coorpacademy-player-web/src/map-state-to-props/test/index.js
Labels: pr: :bug: Bug Fix

#1752 Edit external content
  packages/@coorpacademy-components/src/atom/input-text/index.js
  packages/@coorpacademy-components/src/atom/input-text/style.css
  packages/@coorpacademy-components/src/molecule/drag-and-drop/index.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/overlay.css
  packages/@coorpacademy-components/src/molecule/drag-and-drop/style.css
  packages/@coorpacademy-components/src/molecule/drag-and-drop/test/dragging.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/test/fixtures/error.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/test/fixtures/loading.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/test/fixtures/ready.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/test/fixtures/success-video.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/test/fixtures/success.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/test/on-click.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/upload-report.css
  packages/@coorpacademy-components/src/molecule/drag-and-drop/upload-report.js
Labels: enhancement

#1751 Highlight the Add to my list
  packages/@coorpacademy-components/package.json
  packages/@coorpacademy-components/src/molecule/card/favorite.css
  packages/@coorpacademy-components/src/molecule/card/favorite.js
  packages/@coorpacademy-components/src/molecule/card/index.js
  packages/@coorpacademy-components/src/molecule/card/notification.js
  packages/@coorpacademy-components/src/molecule/card/test/fixtures/default.js
Labels: pr: :lollipop: Enhancement
