Repository CoorpAcademy/components, pull requests merged in 2020-07, with the labels that each got.

#1757 Modification on readMe @coorpacademy-components & publish.md
  doc/publish.md
  packages/@coorpacademy-components/README.md
Labels: pr: Wording :bookmark_tabs:

#1758 [Dashboard, CardsList] Add paging & change design
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/index.js
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/style.css
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/test/fixtures/microlearning.js
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/test/index.js
Labels: pr: :rocket: New feature, pr: Upgrades :outbox_tray:

#1761 [components] Fix animation & style ajustement for card list pagination
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/index.js
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/style.css
Labels: pr: :bug: Bug Fix

#1762 [components] Fix paging animation problem in CardList
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/index.js
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/style.css
Labels: pr: :bug: Bug Fix

#1763 Toggle showMore
  packages/@coorpacademy-components/src/molecule/discipline-header/index.js
  packages/@coorpacademy-components/src/molecule/discipline-header/style.css
  packages/@coorpacademy-components/src/molecule/discipline-header/test/fixtures/long-description.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :lollipop: Enhancement

#1759 [components] Update details page
  packages/@coorpacademy-components/src/molecule/discipline-header/index.js
  packages/@coorpacademy-components/src/molecule/discipline-scope/index.js
  packages/@coorpacademy-components/src/molecule/scope-content/index.js
  packages/@coorpacademy-components/src/molecule/scope-content/style.css
  packages/@coorpacademy-components/src/template/common/discipline/test/fixtures/external-course-with-video.js
  packages/@coorpacademy-components/src/template/common/discipline/test/fixtures/external-course-without-image.js
  packages/@coorpacademy-components/src/template/common/discipline/test/fixtures/external-course.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :lollipop: Enhancement

#1764 Use parseInt from lodash instead of Number (not supported by IE)
  packages/@coorpacademy-player-web/src/map-state-to-props/answer.js
Labels: pr: :bug: Bug Fix

#1767 [components] Update paging design
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/index.js
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/style.css
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/test/fixtures/performance.js
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/test/index.js
Labels: enhancement

#1768 [componenets] Replace native findIndex with lodash findIndex
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/index.js
Labels: pr: :bug: Bug Fix
