Repository CoorpAcademy/components, pull requests merged in 2020-11, with the labels that each got.

#1809 fix - Podcast selection on activity page
  packages/@coorpacademy-components/src/template/activity/progression-item.js
  packages/@coorpacademy-components/src/template/activity/test/fixtures/all-engines.js
Labels: bug

#1810 Update style for drag and drop setup sections
  packages/@coorpacademy-components/src/molecule/setup-section/index.js
  packages/@coorpacademy-components/src/molecule/setup-section/style.css
  packages/@coorpacademy-components/src/molecule/setup-sections/index.js
  packages/@coorpacademy-components/src/molecule/setup-sections/style.css
  packages/@coorpacademy-components/src/molecule/setup-sections/test/on-drop.js
Labels: enhancement

#1812 add teams popin icons
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/address-error.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/address-error.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/login-faild.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/login-faild.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/reload.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/reload.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/address-error.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/login-faild.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/reload.svg
Labels: pr: :rocket: New feature

#1815 add school graduation icon
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/login-failed.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/login-failed.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/school-graduation.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/school-graduation.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/login-failed.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/school-graduation.svg
Labels: pr: :rocket: New feature, pr: :wrench: Refactoring
