Repository CoorpAcademy/components, pull requests merged in 2021-09, with the labels that each got.

#1944 CM: Re-add header
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
Labels: pr: :bug: Bug Fix

#1946 CM: Export header icons
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-solid/content/content-view-module-1.js
  packages/@coorpacademy-nova-icons/src/components/nova-solid/content/content-view-module-1.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-solid/login/logout-1.js
  packages/@coorpacademy-nova-icons/src/components/nova-solid/login/logout-1.native.js
  packages/@coorpacademy-nova-icons/src/index.js
Labels: pr: :lollipop: Enhancement

#1947 CM Header Redesing
  packages/@coorpacademy-components/src/organism/setup-header/index.js
  packages/@coorpacademy-components/src/organism/setup-header/style.css
  packages/@coorpacademy-components/src/organism/setup-header/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/setup-header/test/fixtures/from-dashboards.js
  packages/@coorpacademy-components/src/template/back-office/brand-list/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-list/test/change.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/default.js
Labels: pr: :lollipop: Enhancement

#1950 [CM] Fix default items types
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/part/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
Labels: bug

#1949 CM: Tweak Header
  packages/@coorpacademy-components/src/organism/setup-header/index.js
  packages/@coorpacademy-components/src/organism/setup-header/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-list/test/fixtures/default.js
  packages/@coorpacademy-components/src/variables/breakpoints.css
  packages/@coorpacademy-components/src/variables/colors.css
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/type-eye.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/type-eye.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/type-eye.svg
Labels: pr: :lollipop: Enhancement

#1952 Fix CM header logout not to shift elements
  packages/@coorpacademy-components/src/organism/setup-header/index.js
  packages/@coorpacademy-components/src/organism/setup-header/style.css
Labels: pr: :bug: Bug Fix

#1954 update cockpit-popin to handle assistance type
  packages/@coorpacademy-components/src/atom/button/index.js
  packages/@coorpacademy-components/src/atom/button/style.css
  packages/@coorpacademy-components/src/molecule/popin/index.js
  packages/@coorpacademy-components/src/molecule/popin/style.css
  packages/@coorpacademy-components/src/molecule/popin/test/fixtures/assistance.js
  packages/@coorpacademy-components/src/molecule/popin/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/popin/test/fixtures/loading.js
  packages/@coorpacademy-components/src/molecule/popin/test/fixtures/video-translate.js
  packages/@coorpacademy-components/src/molecule/popin/test/on-change.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :lollipop: Enhancement

#1956 [Cockpit] Popin fix + email field
  packages/@coorpacademy-components/src/molecule/popin/index.js
  packages/@coorpacademy-components/src/molecule/popin/style.css
  packages/@coorpacademy-components/src/molecule/popin/test/fixtures/background-no-second-button.js
  packages/@coorpacademy-components/src/molecule/popin/test/on-change.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement
