Repository CoorpAcademy/components, pull requests merged in 2021-03, with the labels that each got.

#1845 Add coorplogo at "download the app" page + colour injection revamp
  packages/@coorpacademy-components/src/organism/get-the-app/index.js
  packages/@coorpacademy-components/src/organism/get-the-app/style.css
  packages/@coorpacademy-components/src/organism/mooc-footer/style.css
  packages/@coorpacademy-nova-icons/README.md
  packages/@coorpacademy-nova-icons/scripts/generate-icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/coorp-app.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/coorp-app.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/login-failed.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/address-error.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/coorp-app.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/facebook.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/icon-faq.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/import-icon.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/instagram.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/level-0.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/level-1.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/level-2.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/level-3.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/lightbulb.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/linkedin.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/locales.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/login-failed.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/logout.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/magic-wand.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/mail-inbox-document.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/mail-inbox.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/timer.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/tooltip-corner.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/twitter.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/youtube.svg
Labels: pr: :lollipop: Enhancement

#1851 Add about info label + let title, content & newly added aboutLabel render stringified html in trads
  packages/@coorpacademy-components/src/molecule/teams-popin/index.js
  packages/@coorpacademy-components/src/molecule/teams-popin/style.css
  packages/@coorpacademy-components/src/molecule/teams-popin/test/fixtures/login.js
Labels: pr: :lollipop: Enhancement

#1854 [MoocHeader] add color to header menu items
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/default.js
Labels: pr: :rocket: New feature

#1856 Show maintenance mode on brand cards
  packages/@coorpacademy-components/src/molecule/brand-card/index.js
  packages/@coorpacademy-components/src/molecule/brand-card/style.css
  packages/@coorpacademy-components/src/molecule/brand-card/test/fixtures/with-description.js
Labels: pr: :lollipop: Enhancement

#1855 fix link hover color
  packages/@coorpacademy-components/src/atom/link/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/default.js
Labels: pr: :bug: Bug Fix

#1857 fix battles page link badge
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/style.css
Labels: pr: :rocket: New feature

#1861 [SAP] Let image type for upload to be finely controlled + let description admit html for trads
  packages/@coorpacademy-components/src/atom/drag-and-drop/index.js
  packages/@coorpacademy-components/src/atom/drag-and-drop/style.css
  packages/@coorpacademy-components/src/atom/image-upload/index.js
  packages/@coorpacademy-components/src/atom/image-upload/test/fixtures/desktop-reset-description-only-png.js
  packages/@coorpacademy-components/src/atom/image-upload/test/fixtures/desktop-reset-description.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :lollipop: Enhancement
