Repository CoorpAcademy/components, pull requests merged in 2021-06, with the labels that each got.

#1883 override coach trad with custom one
  packages/@coorpacademy-player-web/locales/fr/player.json
Labels: pr: :lollipop: Enhancement

#1884 Fix audio learning for firefox and ie
  packages/@coorpacademy-components/src/molecule/audio/style.css
Labels: bug, ie

#1886 fix add to my list width button
  packages/@coorpacademy-components/src/molecule/add-to-my-list/style.css
  packages/@coorpacademy-components/src/template/common/discipline/test/fixtures/add-to-my-list.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :bug: Bug Fix

#1888 refactor brand dashboard
  packages/@coorpacademy-components/src/organism/brand-dashboard/dashboard-popin.js
  packages/@coorpacademy-components/src/organism/brand-dashboard/index.js
  packages/@coorpacademy-components/src/organism/brand-dashboard/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/brand-dashboard/test/fixtures/selected-error.js
  packages/@coorpacademy-components/src/organism/brand-dashboard/test/fixtures/selected-loading.js
  packages/@coorpacademy-components/src/organism/brand-dashboard/test/fixtures/selected.js
  packages/@coorpacademy-components/src/organism/brand-dashboard/test/on-update-field.js
  packages/@coorpacademy-components/src/organism/brand-dashboard/test/on-update-version.js
Labels: pr: :bug: Bug Fix

#1891 fix: IE 11 element append property
  packages/@coorpacademy-components/src/molecule/share/index.js
Labels: pr: :bug: Bug Fix

#1890 fix share width button
  packages/@coorpacademy-components/src/molecule/share/style.css
  packages/@coorpacademy-components/src/template/common/discipline/test/fixtures/share.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :bug: Bug Fix

#1889 Fix audio player width on ie11
  packages/@coorpacademy-components/src/molecule/audio/style.css
  packages/@coorpacademy-components/src/template/app-player/player/slides/style.css
  packages/@coorpacademy-components/src/template/common/discipline/style.css
Labels: bug, ie

#1893 add data name to share button
  packages/@coorpacademy-components/src/molecule/share/index.js
Labels: pr: :wrench: Refactoring

#1892 fix: remove child from parent rather than removing the child itself cuz IE11 :)
  packages/@coorpacademy-components/src/molecule/share/index.js
Labels: pr: :bug: Bug Fix

#1896 adding audio pause icon
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-solid/audio/audio-control-pause.js
  packages/@coorpacademy-nova-icons/src/components/nova-solid/audio/audio-control-pause.native.js
  packages/@coorpacademy-nova-icons/src/index.js
Labels: pr: :lollipop: Enhancement

#1895 Improve battle start component
  packages/@coorpacademy-components/src/molecule/dashboard/start-battle/index.js
  packages/@coorpacademy-components/src/molecule/dashboard/start-battle/style.css
  packages/@coorpacademy-components/src/molecule/dashboard/start-battle/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/dashboard/start-battle/test/fixtures/href.js
  packages/@coorpacademy-components/src/variables/colors.css
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/big-flash-left.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/big-flash-left.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/big-flash-right.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/big-flash-right.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/small-flash-left.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/small-flash-left.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/small-flash-right.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/small-flash-right.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/start-battle-shape.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/start-battle-shape.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/big-flash-left.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/big-flash-right.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/small-flash-left.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/small-flash-right.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/start-battle-shape.svg
Labels: pr: :wrench: Refactoring

#1897 Fix battle start component
  packages/@coorpacademy-components/src/molecule/dashboard/start-battle/index.js
  packages/@coorpacademy-components/src/molecule/dashboard/start-battle/style.css
Labels: pr: :bug: Bug Fix

#1899 export audio control icons
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/audio/audio-control-fast-forward.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/audio/audio-control-fast-forward.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/audio/audio-control-pause.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/audio/audio-control-pause.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/audio/audio-control-rewind.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/audio/audio-control-rewind.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-solid/audio/audio-control-rewind.js
  packages/@coorpacademy-nova-icons/src/components/nova-solid/audio/audio-control-rewind.native.js
  packages/@coorpacademy-nova-icons/src/index.js
Labels: pr: :lollipop: Enhancement

#1900 fix IE bug
  packages/@coorpacademy-components/src/molecule/dashboard/start-battle/style.css
Labels: pr: :bug: Bug Fix

#1901 center start battle
  packages/@coorpacademy-components/src/molecule/dashboard/start-battle/style.css
Labels: pr: :bug: Bug Fix

#1902 fix typo
  packages/@coorpacademy-components/src/molecule/dashboard/start-battle/index.js
  packages/@coorpacademy-components/src/molecule/dashboard/start-battle/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/dashboard/start-battle/test/fixtures/href.js
Labels: pr: :bug: Bug Fix

#1903 fix start battle component padding
  packages/@coorpacademy-components/src/molecule/dashboard/start-battle/style.css
Labels: pr: :bug: Bug Fix

#1905 fix subTabs scroll
  packages/@coorpacademy-components/src/molecule/brand-tabs/style.css
Labels: pr: :bug: Bug Fix

#1909 use onClick in edit brand card instade of href
  packages/@coorpacademy-components/src/molecule/brand-card/index.js
  packages/@coorpacademy-components/src/molecule/brand-card/style.css
  packages/@coorpacademy-components/src/molecule/brand-card/test/fixtures/with-description.js
Labels: pr: :rocket: New feature
