Repository CoorpAcademy/components, pull requests merged in 2021-08, with the labels that each got.

#1921 [Teams] Dashboard Header - mobile support
  packages/@coorpacademy-components/src/molecule/search-form/index.js
  packages/@coorpacademy-components/src/molecule/search/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/style.css
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/mobile-small-logo-format.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/mobile-wide-logo-format.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/on-header-action-handlers.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/user-change-password.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/header.js
  packages/@coorpacademy-components/src/template/teams-dashboard/index.js
  packages/@coorpacademy-components/src/template/teams-dashboard/style.css
  packages/@coorpacademy-components/src/template/teams-dashboard/test/dashboard.js
  packages/@coorpacademy-components/src/template/teams-dashboard/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/teams-dashboard/test/fixtures/mobile.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :lollipop: Enhancement

#1924 [Fix] Remove estraverse-fb unmaintained dependency in favour of estraverse 5.2, fix locales test error
  package.json
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/test/index.js
  test/helpers/locales.js
  yarn.lock
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement

#1925 menu wrapper style fix
  packages/@coorpacademy-components/src/organism/mooc-header/style.css
Labels: pr: :bug: Bug Fix

#1927 [Mooc-Header] Fix min-height for small logos on tablet - mobile view
  packages/@coorpacademy-components/src/organism/mooc-header/style.css
Labels: pr: :bug: Bug Fix

#1916 Coorpmanager menu
  packages/@coorpacademy-components/src/molecule/brand-tabs/test/fixtures/analytics.js
  packages/@coorpacademy-components/src/molecule/brand-tabs/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/index.js
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/part/index.js
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/part/style.css
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/part/test/fixtures/defaut.js
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/style.css
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/accordion/part/style.css
  packages/@coorpacademy-components/src/organism/sidebar/index.js
  packages/@coorpacademy-components/src/organism/sidebar/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/animations.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/default.js
  packages/@coorpacademy-components/src/variables/colors.css
  packages/@coorpacademy-components/storybook/components.js
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/administration.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/administration.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/analytics.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/analytics.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/animation.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/animation.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/content-creation.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/content-creation.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/dashboard.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/dashboard.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/editorialization.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/editorialization.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/magic-wand.1.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/magic-wand.1.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/magic-wand.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/magic-wand.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/administration.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/analytics.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/animation.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/content-creation.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/dashboard.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/editorialization.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/magic-wand.1.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/magic-wand.svg
Labels: pr: :collision: Breaking Change!, pr: :rocket: New feature

#1928 adding a set of audio playback icons
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/10sec-back.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/10sec-back.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/10sec-forward.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/10sec-forward.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/bluetooth.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/bluetooth.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/next.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/next.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/pause.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/pause.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/play.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/play.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/prev.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/prev.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/queue.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/queue.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/10sec-back.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/10sec-forward.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/bluetooth.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/next.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/pause.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/play.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/prev.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/queue.svg
Labels: pr: :lollipop: Enhancement

#1929 Fix - resource titles overlap
  packages/@coorpacademy-components/src/atom/resource-miniature/style.css
Labels: bug

#1930 [CM]: fix left menu
  packages/@coorpacademy-components/.storybook/preview-head.html
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/part/index.js
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/part/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/style.css
Labels: pr: :lollipop: Enhancement

#1933 CM menu : fix scroll & icon size
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/index.js
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/part/index.js
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/part/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-update/style.css
Labels: pr: :bug: Bug Fix

#1937 [CM] add 3rd level to menu
  packages/@coorpacademy-components/src/molecule/brand-tabs/style.css
  packages/@coorpacademy-components/src/molecule/brand-tabs/test/fixtures/analytics.js
  packages/@coorpacademy-components/src/molecule/brand-tabs/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/index.js
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/part/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/analytics.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/animations.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/cohort-error.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/cohort.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/dashboard.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/dashboards-analytics.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lms-error.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lms-modified.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lms-success.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lms.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lookandfeel.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/manageusers.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/sso.js
Labels: pr: :rocket: New feature

#1941 add hide as icon and bind it to props type for cockpit popin
  packages/@coorpacademy-components/src/molecule/cockpit-popin/index.js
  packages/@coorpacademy-components/src/molecule/cockpit-popin/test/fixtures/default.js
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/content-edition/hide.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/content-edition/hide.native.js
  packages/@coorpacademy-nova-icons/src/index.js
Labels: pr: :lollipop: Enhancement

#1942 fix items selection
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/index.js
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/part/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
Labels: bug

#1943 [CM] Fix tabs design
  packages/@coorpacademy-components/src/molecule/brand-tabs/style.css
  packages/@coorpacademy-components/src/molecule/brand-tabs/test/fixtures/analytics.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/default.js
  packages/@coorpacademy-components/src/variables/colors.css
Labels: pr: :lollipop: Enhancement
