Repository CoorpAcademy/components, pull requests merged in 2021-11, with the labels that each got.

#1990 fix author expand collapse
  packages/@coorpacademy-components/src/molecule/discipline-partners/index.js
Labels: bug

#1989 add vertical tab molecule
  packages/@coorpacademy-components/src/molecule/vertical-tabs/index.js
  packages/@coorpacademy-components/src/molecule/vertical-tabs/style.css
  packages/@coorpacademy-components/src/molecule/vertical-tabs/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/vertical-tabs/test/fixtures/with-selected-item.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :rocket: New feature

#1994 Cm input text
  packages/@coorpacademy-components/src/atom/input-text/index.js
  packages/@coorpacademy-components/src/atom/input-text/style.css
  packages/@coorpacademy-components/src/atom/input-text/test/fixtures/cm-default.js
  packages/@coorpacademy-components/src/organism/user-preferences/style.css
  packages/@coorpacademy-components/src/variables/colors.css
  packages/@coorpacademy-components/storybook/components.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/information-icon.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/information-icon.native.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/information-icon.svg
Labels: enhancement

#1995 add info / error banner
  packages/@coorpacademy-components/src/molecule/banner/index.js
  packages/@coorpacademy-components/src/molecule/banner/style.css
  packages/@coorpacademy-components/src/molecule/banner/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/banner/test/fixtures/error-banner.js
  packages/@coorpacademy-components/src/variables/colors.css
  packages/@coorpacademy-components/storybook/components.js
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-solid/interface-feedback/interface-alert-diamond.js
  packages/@coorpacademy-nova-icons/src/components/nova-solid/interface-feedback/interface-alert-diamond.native.js
  packages/@coorpacademy-nova-icons/src/index.js
Labels: pr: :rocket: New feature

#1996 Cm certif card
  packages/@coorpacademy-components/src/atom/content-badge/index.js
  packages/@coorpacademy-components/src/molecule/card-content/index.js
  packages/@coorpacademy-components/src/molecule/card-content/style.css
  packages/@coorpacademy-components/src/molecule/card/index.js
  packages/@coorpacademy-components/src/molecule/card/selectable.css
  packages/@coorpacademy-components/src/molecule/card/selectable.js
  packages/@coorpacademy-components/src/molecule/card/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/card/test/fixtures/selectable-false.js
  packages/@coorpacademy-components/src/molecule/card/test/fixtures/selectable-true.js
  packages/@coorpacademy-components/storybook/components.js
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-solid/remove-add/remove-circle-1.js
  packages/@coorpacademy-nova-icons/src/components/nova-solid/remove-add/remove-circle-1.native.js
  packages/@coorpacademy-nova-icons/src/index.js
Labels: pr: :lollipop: Enhancement

#2005 Add bullet point icon
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/bullet-point.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/bullet-point.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/bullet-point.svg
Labels: Minor

#2001 CM Input Search
  packages/@coorpacademy-components/src/atom/input-search/index.js
  packages/@coorpacademy-components/src/atom/input-search/style.css
  packages/@coorpacademy-components/src/atom/input-search/test/change.js
  packages/@coorpacademy-components/src/atom/input-search/test/fixtures/coorpmanager-with-value.js
  packages/@coorpacademy-components/src/atom/input-search/test/fixtures/coorpmanager.js
  packages/@coorpacademy-components/src/atom/input-search/test/fixtures/default.js
  packages/@coorpacademy-components/src/atom/input-search/test/fixtures/with-value.js
  packages/@coorpacademy-components/src/molecule/search-form/index.js
  packages/@coorpacademy-components/src/molecule/search/index.js
  packages/@coorpacademy-components/src/molecule/search/style.css
  packages/@coorpacademy-components/src/organism/brand-table/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/logged-with-battle-notifications.js
  packages/@coorpacademy-components/src/template/back-office/brand-list/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-list/style.css
  packages/@coorpacademy-components/storybook/components.js
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/magic-wand.1.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/magic-wand.1.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/magic-wand.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/magic-wand.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/search-1.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/search-1.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/magic-wand.1.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/magic-wand.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/search-1.svg
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/search.svg
Labels: pr: :rocket: New feature

#2012 Replace old buttons in popin by the new one.
  packages/@coorpacademy-components/src/atom/button-link/index.js
  packages/@coorpacademy-components/src/atom/button-link/style.css
  packages/@coorpacademy-components/src/atom/button-link/test/fixtures/button-dangerous-no-icon.js
  packages/@coorpacademy-components/src/molecule/cm-popin/index.js
  packages/@coorpacademy-components/src/molecule/cm-popin/style.css
  packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/dangerous.js
  packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/warning-with-close.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :wrench: Refactoring

#2014 Refactor: Select Multiple to FC with Hooks
  packages/@coorpacademy-components/src/molecule/select-multiple/index.js
  packages/@coorpacademy-components/src/molecule/select-multiple/test/index.js
Labels: pr: :lollipop: Enhancement, pr: :wrench: Refactoring

#2010 Translation organisme
  packages/@coorpacademy-components/src/atom/button-link/index.js
  packages/@coorpacademy-components/src/atom/button-link/style.css
  packages/@coorpacademy-components/src/atom/input-text/index.js
  packages/@coorpacademy-components/src/molecule/vertical-tabs/index.js
  packages/@coorpacademy-components/src/molecule/vertical-tabs/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/vertical-tabs/test/fixtures/with-selected-item.js
  packages/@coorpacademy-components/src/organism/playlist-translation/index.js
  packages/@coorpacademy-components/src/organism/playlist-translation/style.css
  packages/@coorpacademy-components/src/organism/playlist-translation/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/playlist-translation/test/fixtures/delete.js
  packages/@coorpacademy-components/storybook/components.js
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-solid/content-edition/bin.js
  packages/@coorpacademy-nova-icons/src/components/nova-solid/content-edition/bin.native.js
  packages/@coorpacademy-nova-icons/src/index.js
Labels: pr: :rocket: New feature

#2027 tag: add draft type
  packages/@coorpacademy-components/src/atom/tag/index.js
  packages/@coorpacademy-components/src/atom/tag/style.css
  packages/@coorpacademy-components/src/atom/tag/test/fixtures/draft.js
  packages/@coorpacademy-components/src/atom/tag/test/fixtures/revised.js
  packages/@coorpacademy-components/storybook/components.js
Labels: enhancement

#2029 fix myPlatform button condition
  packages/@coorpacademy-components/src/organism/setup-header/index.js
Labels: pr: :bug: Bug Fix

#2033 Fix translation org
  packages/@coorpacademy-components/src/molecule/vertical-tabs/style.css
  packages/@coorpacademy-components/src/organism/playlist-translation/style.css
Labels: pr: :bug: Bug Fix

#2036 recalculate tabs statets when props change
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/index.js
Labels: pr: :bug: Bug Fix

#2042 Fix css for buttons, removes bullet point menu interference
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/index.js
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/style.css
Labels: pr: :bug: Bug Fix

#2046 react-hooks eslint rules
  packages/@coorpacademy-components/.eslintrc
  packages/@coorpacademy-components/package.json
  packages/@coorpacademy-components/src/atom/button-link-icon-only/index.js
  packages/@coorpacademy-components/src/atom/button-link/index.js
  packages/@coorpacademy-components/src/atom/button-menu/index.js
  packages/@coorpacademy-components/src/atom/image-upload/index.js
  packages/@coorpacademy-components/src/hoc/transition/index.js
  packages/@coorpacademy-components/src/molecule/brand-create-form/index.js
  packages/@coorpacademy-components/src/molecule/card/index.js
  packages/@coorpacademy-components/src/molecule/select-multiple/index.js
  packages/@coorpacademy-components/src/molecule/share/index.js
  packages/@coorpacademy-components/src/molecule/wizard-summary/index.js
  packages/@coorpacademy-components/src/organism/accordion/container/index.js
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/index.js
  packages/@coorpacademy-components/src/template/teams-dashboard/index.js
Labels: pr: :lollipop: Enhancement
