Repository CoorpAcademy/components, pull requests merged in 2021-05, with the labels that each got.

#1875 Dynamics feedbacks
  packages/@coorpacademy-player-store/src/utils/state-extract.js
  packages/@coorpacademy-player-store/src/utils/test/state-extract.js
  packages/@coorpacademy-player-web/src/map-state-to-props/test/popin-end.js
Labels: enhancement

#1874 Audio-learning
  packages/@coorpacademy-components/src/atom/resource-miniature/index.js
  packages/@coorpacademy-components/src/atom/resource-miniature/style.css
  packages/@coorpacademy-components/src/atom/resource-miniature/test/fixtures/audio.js
  packages/@coorpacademy-components/src/molecule/answer/index.js
  packages/@coorpacademy-components/src/molecule/answer/style.css
  packages/@coorpacademy-components/src/molecule/answer/test/fixtures/audio.js
  packages/@coorpacademy-components/src/molecule/answer/test/fixtures/qcm-short-audio.js
  packages/@coorpacademy-components/src/molecule/audio/index.js
  packages/@coorpacademy-components/src/molecule/audio/style.css
  packages/@coorpacademy-components/src/molecule/audio/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/audio/test/fixtures/with-poster.js
  packages/@coorpacademy-components/src/molecule/audio/test/on-click.js
  packages/@coorpacademy-components/src/molecule/external-content-viewer/index.js
  packages/@coorpacademy-components/src/molecule/external-content-viewer/style.css
  packages/@coorpacademy-components/src/molecule/feedback/index.js
  packages/@coorpacademy-components/src/molecule/feedback/test/fixtures/success-with-title-and-description-and-audio.js
  packages/@coorpacademy-components/src/molecule/resource-player/index.js
  packages/@coorpacademy-components/src/molecule/resource-player/style.css
  packages/@coorpacademy-components/src/molecule/resource-player/test/fixtures/audio.js
  packages/@coorpacademy-components/src/molecule/scope-content/index.js
  packages/@coorpacademy-components/src/molecule/scope-content/test/fixtures/medias.js
  packages/@coorpacademy-components/src/organism/resource-browser/test/fixtures/audio.js
  packages/@coorpacademy-components/src/template/app-player/player/slides/index.js
  packages/@coorpacademy-components/src/template/app-player/player/slides/style.css
  packages/@coorpacademy-components/src/template/app-player/player/slides/test/fixtures/context-with-audio.js
  packages/@coorpacademy-components/storybook/components.js
  packages/@coorpacademy-player-store/src/definitions/models.js
  packages/@coorpacademy-player-store/src/utils/state-extract.js
  packages/@coorpacademy-progression-engine/src/types.js
Labels: enhancement

#1877 [Icons]add open in new tab icon
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/open-in-new-tab.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/open-in-new-tab.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/open-in-new-tab.svg
Labels: pr: :rocket: New feature

#1878 add open link in new tab item
  packages/@coorpacademy-components/src/organism/sidebar/index.js
  packages/@coorpacademy-components/src/organism/sidebar/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/animations.js
Labels: pr: :rocket: New feature

#1881 delete callback function
  packages/@coorpacademy-components/src/molecule/add-to-my-list/index.js
Labels: pr: :bug: Bug Fix

#1882 fix add to my list feedback
  packages/@coorpacademy-components/src/molecule/add-to-my-list/index.js
  packages/@coorpacademy-components/src/template/common/discipline/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/common/discipline/test/on-click.js
Labels: pr: :bug: Bug Fix
