Repository CoorpAcademy/components, pull requests merged in 2021-10, with the labels that each got.

#1958 fix: should fix bug for previewing external content pdf on mobile
  packages/@coorpacademy-components/src/molecule/external-content-viewer/index.js
Labels: pr: :bug: Bug Fix

#1980 Includes function not supported by ie11
  packages/@coorpacademy-components/src/atom/difficulty-level/index.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/index.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/upload-report.js
  packages/@coorpacademy-components/src/molecule/external-content-viewer/index.js
Labels: bug

#1982 Fix Input Checkbox Design
  packages/@coorpacademy-components/src/atom/input-checkbox/index.js
  packages/@coorpacademy-components/src/atom/input-checkbox/style.css
  packages/@coorpacademy-components/src/organism/brand-form/test/fixtures/manageusers-edit.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement
