Repository CoorpAcademy/components, pull requests merged in 2021-02, with the labels that each got.

#1835 [coorp-icons] add info icon
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/information-icon.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/information-icon.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/information-icon.svg
Labels: Minor

#1837 adds info icon
  packages/@coorpacademy-components/src/organism/user-preferences/index.js
  packages/@coorpacademy-components/src/organism/user-preferences/style.css
  packages/@coorpacademy-components/src/organism/user-preferences/test/fixtures/default.js
Labels: pr: :lollipop: Enhancement

#1842 fix notification button on ie
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
Labels: bug, ie

#1841 [Teams] Logout button for teams dashboard
  packages/@coorpacademy-components/src/atom/cta/index.js
  packages/@coorpacademy-components/src/atom/cta/style.css
  packages/@coorpacademy-components/src/atom/cta/test/fixtures/logout.js
  packages/@coorpacademy-components/src/atom/cta/test/fixtures/no-submit-value.js
  packages/@coorpacademy-components/src/atom/cta/test/hover.js
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/style.css
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/teams.js
  packages/@coorpacademy-components/src/template/teams-dashboard/index.js
  packages/@coorpacademy-components/src/template/teams-dashboard/test/fixtures/default.js
  packages/@coorpacademy-components/storybook/components.js
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/logout.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/logout.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/logout.svg
Labels: pr: :rocket: New feature

#1844 Fix long buttons (ctas) width issue (word capping)
  packages/@coorpacademy-components/src/organism/mooc-header/style.css
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/teams-french.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :bug: Bug Fix
