Repository CoorpAcademy/components, pull requests merged in 2021-01, with the labels that each got.

#1823 [TEAMS] adds backgroundImageUrl to teams popin
  packages/@coorpacademy-components/src/molecule/teams-popin/index.js
  packages/@coorpacademy-components/src/molecule/teams-popin/style.css
  packages/@coorpacademy-components/src/molecule/teams-popin/test/fixtures/loading-background.js
  packages/@coorpacademy-components/src/molecule/teams-popin/test/fixtures/login-background.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :lollipop: Enhancement

#1824 [Teams] Improve data name of popin's children
  packages/@coorpacademy-components/src/molecule/teams-popin/index.js
Labels: pr: :wrench: Refactoring

#1826 Components enhancement
  packages/@coorpacademy-components/src/molecule/filters/style.css
  packages/@coorpacademy-components/src/molecule/news/index.js
  packages/@coorpacademy-components/src/molecule/news/test/fixtures/arabic.js
  packages/@coorpacademy-components/src/organism/sidebar/index.js
  packages/@coorpacademy-components/src/organism/sidebar/test/fixtures/analytics.js
  packages/@coorpacademy-components/src/template/app-player/player/slides/index.js
  packages/@coorpacademy-components/src/template/app-player/player/slides/style.css
  packages/@coorpacademy-components/src/template/common/search-page/test/fixtures/default.js
  packages/@coorpacademy-components/storybook/components.js
Labels: enhancement

#1831 Fix cockpit popin
  packages/@coorpacademy-components/src/molecule/cockpit-popin/index.js
  packages/@coorpacademy-components/src/molecule/cockpit-popin/style.css
Labels: pr: :bug: Bug Fix

#1832 make close button cursor pointer
  packages/@coorpacademy-components/src/molecule/cockpit-popin/style.css
Labels: pr: :bug: Bug Fix
