Repository CoorpAcademy/components, pull requests merged in 2022-03, with the labels that each got.

#2145 Adds toggle to brandList view
  packages/@coorpacademy-components/src/template/back-office/brand-list/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-list/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-list/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/back-office/brand-list/test/fixtures/rh.js
Labels: enhancement

#2147 refacto data names for content componennts
  packages/@coorpacademy-components/src/atom/tag/index.js
  packages/@coorpacademy-components/src/organism/list-items/index.js
  packages/@coorpacademy-components/src/organism/wizard-contents/index.js
Labels: pr: :wrench: Refactoring

#2153 Fix lms select, complete LMS fixture
  packages/@coorpacademy-components/src/molecule/setup-slide/index.js
  packages/@coorpacademy-components/src/organism/brand-form/test/fixtures/lms.js
Labels: pr: :bug: Bug Fix

#2161 fix mandatory courses input width
  packages/@coorpacademy-components/src/atom/input-text-with-title/index.js
  packages/@coorpacademy-components/src/atom/input-text-with-title/style.css
  packages/@coorpacademy-components/src/atom/input-text-with-title/test/fixtures/error.js
Labels: pr: :bug: Bug Fix

#2164 Organism Review Header
  packages/@coorpacademy-components/src/atom/button-link-icon-only/index.js
  packages/@coorpacademy-components/src/atom/button-link-icon-only/style.css
  packages/@coorpacademy-components/src/atom/button-link-icon-only/test/button-link-icon-only.js
  packages/@coorpacademy-components/src/atom/button-link-icon-only/test/fixtures/review-header.js
  packages/@coorpacademy-components/src/atom/review-header-step-item/index.js
  packages/@coorpacademy-components/src/atom/review-header-step-item/style.css
  packages/@coorpacademy-components/src/organism/review-header/index.js
  packages/@coorpacademy-components/src/organism/review-header/style.css
  packages/@coorpacademy-components/src/organism/review-header/test/fixtures/all-questions-ok.js
  packages/@coorpacademy-components/src/organism/review-header/test/fixtures/current-question-no-answered.js
  packages/@coorpacademy-components/src/organism/review-header/test/fixtures/current-question-wrong.js
  packages/@coorpacademy-components/src/organism/review-header/test/fixtures/first-question-current-right.js
  packages/@coorpacademy-components/src/organism/review-header/test/fixtures/no-answered-question.js
  packages/@coorpacademy-components/src/organism/review-header/test/fixtures/question-to-repeat.js
  packages/@coorpacademy-components/src/organism/review-header/test/review-header.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :rocket: New feature

#2166 Fix qcm image
  packages/@coorpacademy-components/src/molecule/questions/qcm-graphic/style.css
Labels: bug

#2170 feedbacks drag and drop
  packages/@coorpacademy-components/src/atom/drag-and-drop/index.js
  packages/@coorpacademy-components/src/atom/drag-and-drop/style.css
Labels: enhancement

#2173 Molecule Skill Card
  packages/@coorpacademy-components/src/molecule/skill-card/index.js
  packages/@coorpacademy-components/src/molecule/skill-card/style.css
  packages/@coorpacademy-components/src/molecule/skill-card/test/fixtures/custom-skill.js
  packages/@coorpacademy-components/src/molecule/skill-card/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/skill-card/test/fixtures/no-aria-labels.js
  packages/@coorpacademy-components/src/molecule/skill-card/test/fixtures/short-skill-title.js
  packages/@coorpacademy-components/src/molecule/skill-card/test/skill-card.js
  packages/@coorpacademy-components/src/variables/colors.css
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :rocket: New feature

#2175 Atom Review Presentation
  packages/@coorpacademy-components/src/atom/review-presentation/index.js
  packages/@coorpacademy-components/src/atom/review-presentation/style.css
  packages/@coorpacademy-components/src/atom/review-presentation/test/fixtures/default.js
  packages/@coorpacademy-components/storybook/components.js
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/selection-cursors/cursor-arrow-target.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/selection-cursors/cursor-arrow-target.native.js
  packages/@coorpacademy-nova-icons/src/index.js
Labels: pr: :rocket: New feature

#2178 fix drag & drop component
  packages/@coorpacademy-components/src/atom/drag-and-drop/index.js
  packages/@coorpacademy-components/src/atom/drag-and-drop/test/fixtures/error.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop-wrapper/index.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop-wrapper/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop-wrapper/test/fixtures/two-drag-and-drops.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop-wrapper/test/fixtures/without-checkbox.js
  packages/@coorpacademy-components/src/organism/brand-form/test/fixtures/wizard-certification.js
  packages/@coorpacademy-components/src/organism/rewards-form/test/fixtures/default.js
Labels: pr: :bug: Bug Fix
