Repository CoorpAcademy/components, pull requests merged in 2022-09, with the labels that each got.

#2343 Add mocked fetch correction service
  packages/@coorpacademy-app-review/src/services/index.ts
  packages/@coorpacademy-app-review/src/test/util/services.mock.ts
  packages/@coorpacademy-app-review/src/types/common.ts
Labels: pr: :rocket: New feature

#2345 Add fetchCorrection action
  packages/@coorpacademy-app-review/src/actions/api/fetch-correction.ts
  packages/@coorpacademy-app-review/src/actions/api/fetch-skills.ts
  packages/@coorpacademy-app-review/src/actions/api/fetch-slide.ts
  packages/@coorpacademy-app-review/src/actions/api/post-answer.ts
  packages/@coorpacademy-app-review/src/actions/api/post-progression.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-correction.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-skills.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-slide.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-answer.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-progression.test.ts
  packages/@coorpacademy-app-review/src/reducers/data/index.ts
  packages/@coorpacademy-app-review/src/reducers/data/test/token.test.ts
  packages/@coorpacademy-app-review/src/reducers/data/token.ts
  packages/@coorpacademy-app-review/src/test/util/services.mock.ts
Labels: pr: :rocket: New feature

#2349 popin should be display in the firt level
  packages/@coorpacademy-components/src/molecule/cm-popin/style.css
Labels: pr: :bug: Bug Fix

#2346 Add answers correction reducer
  packages/@coorpacademy-app-review/nyc.config.js
  packages/@coorpacademy-app-review/src/actions/api/fetch-correction.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-correction.test.ts
  packages/@coorpacademy-app-review/src/reducers/data/corrections.ts
  packages/@coorpacademy-app-review/src/reducers/data/test/corrections.test.ts
  packages/@coorpacademy-app-review/src/reducers/data/test/skills.test.ts
  packages/@coorpacademy-app-review/src/reducers/data/test/slides.test.ts
  packages/@coorpacademy-app-review/src/views/slides/index.ts
Labels: pr: :rocket: New feature

#2355 News without cta
  packages/@coorpacademy-components/src/molecule/news/index.js
  packages/@coorpacademy-components/src/molecule/news/style.css
  packages/@coorpacademy-components/src/molecule/news/test/fixtures/without-cta.js
  packages/@coorpacademy-components/storybook/components.js
Labels: enhancement

#2353 Plug correction reducer, update tests, increase coverage
  packages/@coorpacademy-app-review/nyc.config.js
  packages/@coorpacademy-app-review/src/actions/api/post-answer.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-correction.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-skills.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-slide.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-answer.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-progression.test.ts
  packages/@coorpacademy-app-review/src/actions/data/test/token.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/answers.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/answers.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/slides.test.ts
  packages/@coorpacademy-app-review/src/reducers/data/index.ts
  packages/@coorpacademy-app-review/src/views/skills/test/skills.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.template.on-change.test.ts
Labels: pr: :rocket: New feature, pr: :wrench: Refactoring

#2357 [app-review] Add ui slide reducer handling for CORRECTION_FETCH_SUCCESS action
  packages/@coorpacademy-app-review/src/actions/api/test/post-answer.test.ts
  packages/@coorpacademy-app-review/src/actions/test/create-test-store.ts
  packages/@coorpacademy-app-review/src/reducers/ui/slide.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/slide.test.ts
Labels: pr: :rocket: New feature

#2356 [app-review] Add unit tests for answers actions
  packages/@coorpacademy-app-review/nyc.config.js
  packages/@coorpacademy-app-review/src/types/slides.ts
  packages/@coorpacademy-app-review/src/views/slides/map-api-slide-to-ui.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/qcm-graphic.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/qcm.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.free-text.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-drag.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-graphic.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-change.test.ts
Labels: pr: :lollipop: Enhancement

#2361 [app-review] Add fetchRank service and unit tests
  packages/@coorpacademy-app-review/nyc.config.js
  packages/@coorpacademy-app-review/src/services/fetch-rank.ts
  packages/@coorpacademy-app-review/src/services/test/fetch-rank.test.ts
  packages/@coorpacademy-app-review/src/types/common.ts
Labels: pr: :rocket: New feature

#2364 [app-review] add mocked fetch rank service
  packages/@coorpacademy-app-review/src/services/index.ts
  packages/@coorpacademy-app-review/src/test/util/services.mock.ts
  packages/@coorpacademy-app-review/src/types/common.ts
Labels: pr: :rocket: New feature

#2367 [app-review] Add fetchStartRank and fetchEndRank actions
  packages/@coorpacademy-app-review/nyc.config.js
  packages/@coorpacademy-app-review/src/actions/api/fetch-rank.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-rank.test.ts
  packages/@coorpacademy-app-review/src/reducers/data/corrections.ts
  packages/@coorpacademy-app-review/src/reducers/index.ts
Labels: pr: :rocket: New feature

#2369 [app-review] add rank reducer
  packages/@coorpacademy-app-review/nyc.config.js
  packages/@coorpacademy-app-review/src/actions/api/fetch-rank.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-correction.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-rank.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-skills.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-slide.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-answer.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-progression.test.ts
  packages/@coorpacademy-app-review/src/actions/data/test/token.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/answers.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/slides.test.ts
  packages/@coorpacademy-app-review/src/reducers/data/index.ts
  packages/@coorpacademy-app-review/src/reducers/data/rank.ts
  packages/@coorpacademy-app-review/src/reducers/data/test/rank.test.ts
  packages/@coorpacademy-app-review/src/views/skills/test/skills.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.free-text.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-drag.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-graphic.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.template.on-change.test.ts
Labels: pr: :rocket: New feature

#2371 fix html question tag
  packages/@coorpacademy-components/src/organism/review-slide/index.js
  packages/@coorpacademy-components/src/organism/review-slide/test/fixtures/initial-state.js
Labels: pr: :bug: Bug Fix

#2374 [app-review] add actions fetchStartRank and fetchEndRank in postAnswer action
  packages/@coorpacademy-app-review/nyc.config.js
  packages/@coorpacademy-app-review/src/actions/api/post-answer.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-answer.test.ts
Labels: pr: :rocket: New feature

#2375 Fix no card ranking
  packages/@coorpacademy-components/src/organism/review-congrats/index.js
  packages/@coorpacademy-components/src/organism/review-congrats/style.css
  packages/@coorpacademy-components/src/organism/review-congrats/test/fixtures/no-rank.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :bug: Bug Fix

#2377 [app-review] add ui action next-slide
  packages/@coorpacademy-app-review/nyc.config.js
  packages/@coorpacademy-app-review/src/actions/ui/next-slide.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/next-slide.test.ts
Labels: pr: :rocket: New feature

#2383 [app-review] refacto ui.slide and ui.answers
  packages/@coorpacademy-app-review/nyc.config.js
  packages/@coorpacademy-app-review/src/actions/api/fetch-correction.ts
  packages/@coorpacademy-app-review/src/actions/api/post-answer.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-correction.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-rank.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-skills.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-slide.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-answer.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-progression.test.ts
  packages/@coorpacademy-app-review/src/actions/data/test/token.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/answers.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/answers.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/next-slide.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/slides.test.ts
  packages/@coorpacademy-app-review/src/reducers/data/test/progression.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/answers.ts
  packages/@coorpacademy-app-review/src/reducers/ui/index.ts
  packages/@coorpacademy-app-review/src/reducers/ui/slide.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/answers.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/slide.test.ts
  packages/@coorpacademy-app-review/src/views/skills/test/skills.test.ts
  packages/@coorpacademy-app-review/src/views/slides/index.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.free-text.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-drag.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-graphic.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-slider-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.template.on-change.test.ts
  packages/@coorpacademy-app-review/tsconfig.es.json
  packages/@coorpacademy-app-review/tsconfig.lib.json
Labels: pr: :wrench: Refactoring

#2389 syntax guide on CoorpManager
  packages/@coorpacademy-components/src/molecule/brand-form-group/index.js
  packages/@coorpacademy-components/src/organism/brand-form/test/fixtures/wizard-playlists.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/wizard-form-create-playlist.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/wizard-form-edit-playlist.js
Labels: enhancement

#2393 [app-review] fix bug in reducers answers and corrections
  packages/@coorpacademy-app-review/src/reducers/data/corrections.ts
  packages/@coorpacademy-app-review/src/reducers/ui/answers.ts
Labels: pr: :bug: Bug Fix

#2395 [app-review] update `mapStateToProps` and bind the NEXT_SLIDE action to the popin's next button
  packages/@coorpacademy-app-review/nyc.config.js
  packages/@coorpacademy-app-review/src/actions/api/fetch-slide.ts
  packages/@coorpacademy-app-review/src/actions/ui/next-slide.ts
  packages/@coorpacademy-app-review/src/views/slides/index.ts
  packages/@coorpacademy-app-review/src/views/slides/map-api-slide-to-ui.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/free-text.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/qcm-drag.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/qcm-graphic.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/qcm.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/slider.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/template.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/map-api-slide-to-ui.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.free-text.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-drag.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-graphic.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.template.on-change.test.ts
  packages/@coorpacademy-components/src/organism/review-slide/index.js
Labels: pr: :rocket: New feature

#2403 Ie11 - fix pointer event
  packages/@coorpacademy-components/src/organism/review-slide/style.css
Labels: bug

#2396 Learner header mode scorm
  packages/@coorpacademy-components/src/template/app-player/player/slides/header/index.js
  packages/@coorpacademy-components/src/template/app-player/player/slides/header/learner.css
  packages/@coorpacademy-components/src/template/app-player/player/slides/header/learner.js
  packages/@coorpacademy-components/src/template/app-player/player/slides/header/test/fixtures/learner-mode-scorm.js
  packages/@coorpacademy-components/storybook/components.js
  packages/@coorpacademy-player-web/src/map-state-to-props/header.js
  packages/@coorpacademy-player-web/src/map-state-to-props/test/answer.js
Labels: pr: :rocket: New feature
