Repository CoorpAcademy/components, pull requests merged in 2022-08, with the labels that each got.

#2281 Customisation-Player-Scorm-end-screen
  packages/@coorpacademy-components/src/molecule/feedback/index.js
  packages/@coorpacademy-components/src/molecule/feedback/style.css
  packages/@coorpacademy-components/src/template/app-player/popin-end/index.js
  packages/@coorpacademy-components/src/template/app-player/popin-end/style.css
  packages/@coorpacademy-components/src/template/app-player/popin-end/summary.css
  packages/@coorpacademy-components/src/template/app-player/popin-end/summary.js
  packages/@coorpacademy-components/src/template/app-player/popin-end/test/fixtures/fail-scorm-with-feedback.js
  packages/@coorpacademy-components/src/template/app-player/popin-end/test/fixtures/fail-scorm.js
  packages/@coorpacademy-components/src/template/app-player/popin-end/test/fixtures/scorm-correct.js
  packages/@coorpacademy-components/src/template/app-player/popin-end/test/fixtures/success-scorm-with-feedback.js
  packages/@coorpacademy-components/src/template/app-player/popin-end/test/fixtures/success-scorm.js
  packages/@coorpacademy-components/src/template/app-player/popin-header/index.js
  packages/@coorpacademy-components/src/template/app-player/popin-header/style.css
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :rocket: New feature

#2290 popine-cookie
  packages/@coorpacademy-components/src/atom/input-switch/index.js
  packages/@coorpacademy-components/src/atom/input-switch/style.css
  packages/@coorpacademy-components/src/atom/input-switch/test/fixtures/details.js
  packages/@coorpacademy-components/src/atom/input-switch/test/fixtures/partiel-uncheck-right-checked.js
  packages/@coorpacademy-components/src/atom/input-switch/test/fixtures/partiel-uncheck-right-disabled.js
  packages/@coorpacademy-components/src/atom/input-switch/test/fixtures/partiel-uncheck-right.js
  packages/@coorpacademy-components/src/atom/input-switch/test/fixtures/required-selection.js
  packages/@coorpacademy-components/src/molecule/cm-popin/index.js
  packages/@coorpacademy-components/src/molecule/cm-popin/style.css
  packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/cookie-settings.js
  packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/cookie.js
  packages/@coorpacademy-components/src/template/common/dashboard/index.js
  packages/@coorpacademy-components/src/template/common/dashboard/test/fixtures/cookie-dashboard.js
  packages/@coorpacademy-components/src/template/common/dashboard/test/fixtures/cookie-settings-dashboard.js
  packages/@coorpacademy-components/src/variables/colors.css
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :rocket: New feature

#2298 Fix congrats - mobile version
  packages/@coorpacademy-components/src/organism/review-congrats/style.css
Labels: pr: :bug: Bug Fix

#2300 Fix ReviewCorrectionPopin style
  packages/@coorpacademy-components/src/organism/review-slide/style.css
Labels: pr: :bug: Bug Fix

#2303 Add Content title property of slide
  packages/@coorpacademy-components/src/organism/review-slide/index.js
  packages/@coorpacademy-components/src/organism/review-slide/prop-types.js
  packages/@coorpacademy-components/src/organism/review-slide/style.css
  packages/@coorpacademy-components/src/organism/review-slide/test/fixtures/choices-selected.js
  packages/@coorpacademy-components/src/organism/review-slide/test/fixtures/correction-ok-animated.js
  packages/@coorpacademy-components/src/organism/review-slide/test/fixtures/correction-ok.js
  packages/@coorpacademy-components/src/organism/review-slide/test/fixtures/correction-wrong-animated.js
  packages/@coorpacademy-components/src/organism/review-slide/test/fixtures/correction-wrong.js
  packages/@coorpacademy-components/src/organism/review-slide/test/fixtures/initial-state.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/all-ok.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/first-correct.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/initial-state.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/restack.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/unstack.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/wrong-ko.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/wrong.js
Labels: pr: :lollipop: Enhancement

#2307 Use css-modules to compose classes-2
  packages/@coorpacademy-components/src/atom/resource-miniature/index.js
  packages/@coorpacademy-components/src/atom/resource-miniature/style.css
  packages/@coorpacademy-components/src/template/app-player/player/slides/header/learner.css
  packages/@coorpacademy-components/src/template/app-player/player/slides/header/learner.js
  packages/@coorpacademy-components/src/template/app-player/player/slides/header/microlearning.css
  packages/@coorpacademy-components/src/template/app-player/player/slides/header/microlearning.js
  packages/@coorpacademy-components/src/template/app-player/player/slides/index.js
  packages/@coorpacademy-components/src/template/app-player/player/slides/style.css
  packages/@coorpacademy-components/src/template/app-player/popin-correction/index.js
  packages/@coorpacademy-components/src/template/app-player/popin-correction/style.css
  packages/@coorpacademy-components/src/template/app-player/popin-end/summary.css
  packages/@coorpacademy-components/src/template/app-player/popin-end/summary.js
  packages/@coorpacademy-components/src/template/app-player/popin-header/index.js
  packages/@coorpacademy-components/src/template/app-player/popin-header/style.css
  packages/@coorpacademy-components/src/template/common/authors/index.js
  packages/@coorpacademy-components/src/template/common/authors/style.css
Labels: pr: :bug: Bug Fix

#2311 Fix width container slide and add loading slide
  packages/@coorpacademy-components/src/organism/review-slide/index.js
  packages/@coorpacademy-components/src/organism/review-slide/prop-types.js
  packages/@coorpacademy-components/src/organism/review-slide/style.css
  packages/@coorpacademy-components/src/organism/review-slide/test/fixtures/choices-selected.js
  packages/@coorpacademy-components/src/organism/review-slide/test/fixtures/correction-ok-animated.js
  packages/@coorpacademy-components/src/organism/review-slide/test/fixtures/correction-ok.js
  packages/@coorpacademy-components/src/organism/review-slide/test/fixtures/correction-wrong-animated.js
  packages/@coorpacademy-components/src/organism/review-slide/test/fixtures/correction-wrong.js
  packages/@coorpacademy-components/src/organism/review-slide/test/fixtures/initial-state.js
  packages/@coorpacademy-components/src/organism/review-slide/test/fixtures/loading.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/index.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/prop-types.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/style.css
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/all-ok.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/first-correct.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/initial-state.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/loading.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/restack.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/second-wrong.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/unstack.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/wrong.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :bug: Bug Fix

#2316 Get parentContentTitle from the SlideAPI + related refactor
  packages/@coorpacademy-app-review/src/services/fetch-slide.ts
  packages/@coorpacademy-app-review/src/services/test/fetch-slide.test.ts
  packages/@coorpacademy-app-review/src/test/util/services.mock.ts
  packages/@coorpacademy-app-review/src/types/common.ts
  packages/@coorpacademy-app-review/src/views/slides/index.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/free-text.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/qcm-drag.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/qcm-graphic.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/qcm.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/select-template.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/slider.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/text-template.ts
Labels: pr: :rocket: New feature

#2319 Add postAnswer service
  packages/@coorpacademy-app-review/src/reducers/data/test/progression.test.ts
  packages/@coorpacademy-app-review/src/services/index.ts
  packages/@coorpacademy-app-review/src/services/post-answer.ts
  packages/@coorpacademy-app-review/src/services/test/post-answer.test.ts
  packages/@coorpacademy-app-review/src/services/test/post-progression.test.ts
  packages/@coorpacademy-app-review/src/test/util/services.mock.ts
  packages/@coorpacademy-app-review/src/types/common.ts
Labels: pr: :rocket: New feature

#2326 Post answer api action
  packages/@coorpacademy-app-review/src/actions/api/fetch-skills.ts
  packages/@coorpacademy-app-review/src/actions/api/fetch-slide.ts
  packages/@coorpacademy-app-review/src/actions/api/post-answer.ts
  packages/@coorpacademy-app-review/src/actions/api/post-progression.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-skills.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-slide.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-answer.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-progression.test.ts
  packages/@coorpacademy-app-review/src/actions/index.ts
  packages/@coorpacademy-app-review/src/index.tsx
  packages/@coorpacademy-app-review/src/reducers/data/progression.ts
  packages/@coorpacademy-app-review/src/reducers/data/test/progression.test.ts
  packages/@coorpacademy-app-review/src/test/util/services.mock.ts
Labels: pr: :rocket: New feature

#2323 Add actions to EDIT_QCM, EDIT_QCM_GRAPHIC and EDIT_QCM_DRAG
  packages/@coorpacademy-app-review/src/actions/ui/answers.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/answers.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/answers.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/answers.test.ts
  packages/@coorpacademy-app-review/src/views/slides/map-api-slide-to-ui.ts
Labels: pr: :rocket: New feature

#2329 Add action EDIT_SLIDER
  packages/@coorpacademy-app-review/src/actions/ui/answers.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/answers.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/answers.test.ts
  packages/@coorpacademy-app-review/src/views/slides/map-api-slide-to-ui.ts
Labels: pr: :rocket: New feature

#2331 Plug post answer action to validate click + add validateButton status to Slide state (UI)
  packages/@coorpacademy-app-review/src/actions/api/post-answer.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-skills.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-slide.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-answer.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-progression.test.ts
  packages/@coorpacademy-app-review/src/actions/data/test/token.test.ts
  packages/@coorpacademy-app-review/src/actions/index.ts
  packages/@coorpacademy-app-review/src/actions/ui/answers.ts
  packages/@coorpacademy-app-review/src/actions/ui/slides.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/answers.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/slides.test.ts
  packages/@coorpacademy-app-review/src/common/index.ts
  packages/@coorpacademy-app-review/src/reducers/data/slides.ts
  packages/@coorpacademy-app-review/src/reducers/ui/index.ts
  packages/@coorpacademy-app-review/src/reducers/ui/slide.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/answers.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/current-slide-ref.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/navigation.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/slide.test.ts
  packages/@coorpacademy-app-review/src/views/skills/test/skills.test.ts
  packages/@coorpacademy-app-review/src/views/slides/index.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
Labels: pr: :lollipop: Enhancement

#2335 Add reducer handling for the POST_ANSWER_SUCCESS action + fire fetchSlide + ut
  packages/@coorpacademy-app-review/src/actions/api/post-answer.ts
  packages/@coorpacademy-app-review/src/reducers/data/progression.ts
  packages/@coorpacademy-app-review/src/reducers/data/test/progression.test.ts
  packages/@coorpacademy-app-review/src/test/util/services.mock.ts
Labels: pr: :rocket: New feature

#2336 Migrate Atom input doubleStep to testing library
  packages/@coorpacademy-components/src/atom/input-doublestep/test/on-change.js
Labels: pr: :lollipop: Enhancement

#2330 Add action EDIT_TEMPLATE
  packages/@coorpacademy-app-review/src/actions/ui/answers.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/answers.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/answers.test.ts
  packages/@coorpacademy-app-review/src/test/util/services.mock.ts
  packages/@coorpacademy-app-review/src/views/slides/map-api-slide-to-ui.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/template.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/text-template.ts
  packages/@coorpacademy-app-review/src/views/slides/test/map-api-slide-to-ui.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.template.on-change.test.ts
Labels: pr: :rocket: New feature

#2338 Fixes slides order building
  packages/@coorpacademy-app-review/src/views/slides/index.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
Labels: pr: :bug: Bug Fix
