Repository CoorpAcademy/components, pull requests merged in 2022-02, with the labels that each got.

#2115 remove bold to feedback description
  packages/@coorpacademy-components/src/molecule/feedback/style.css
Labels: enhancement

#2114 create course section component
  packages/@coorpacademy-components/src/molecule/course-section/index.js
  packages/@coorpacademy-components/src/molecule/course-section/style.css
  packages/@coorpacademy-components/src/molecule/course-section/test/fixtures/chapter.js
  packages/@coorpacademy-components/src/molecule/course-section/test/fixtures/course.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :lollipop: Enhancement

#2124 fix language tooltip
  packages/@coorpacademy-components/src/molecule/select-multiple/style.css
  packages/@coorpacademy-components/src/organism/brand-form/test/fixtures/wizard-playlists.js
Labels: pr: :lollipop: Enhancement

#2121 Redesign molecule Qcm && add coverage
  packages/@coorpacademy-components/src/molecule/questions/qcm/index.js
  packages/@coorpacademy-components/src/molecule/questions/qcm/style.css
  packages/@coorpacademy-components/src/molecule/questions/qcm/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/questions/qcm/test/qcm.js
  packages/@coorpacademy-components/src/util/get-shadow-box-color-from-primary.js
  packages/@coorpacademy-components/src/util/test/get-shadow-box-color-from-primary.js
  packages/@coorpacademy-components/src/variables/colors.css
Labels: pr: :lollipop: Enhancement

#2139 Apply product reviews (fill in the blank): fix text font, hover on dropdown + mozilla area click bug
  packages/@coorpacademy-components/src/atom/select/index.js
  packages/@coorpacademy-components/src/atom/select/style.css
  packages/@coorpacademy-components/src/molecule/questions/template/index.js
  packages/@coorpacademy-components/src/molecule/questions/template/style.css
  packages/@coorpacademy-components/src/variables/colors.css
Labels: pr: :bug: Bug Fix

#2141 Micro fix - mozilla css specificity - fix full select (absolute) width
  packages/@coorpacademy-components/src/atom/select/style.css
Labels: pr: :bug: Bug Fix

#2144 Fixes coorpmanager select
  packages/@coorpacademy-components/src/atom/select/index.js
  packages/@coorpacademy-components/src/atom/select/style.css
  packages/@coorpacademy-components/src/atom/select/test/fixtures/coorpmanager.js
  packages/@coorpacademy-components/src/molecule/brand-form-group/index.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :bug: Bug Fix

#2140 Canary publish - Readme tips update
  doc/publish.md
Labels: pr: Documentation 📜
