Repository CoorpAcademy/components, pull requests merged in 2022-11, with the labels that each got.

#2469 add babel lodash plugin by default
  packages/@coorpacademy-webpack-config/package.json
  packages/@coorpacademy-webpack-config/src/index.js
  packages/@coorpacademy-webpack-config/src/test/index.js
Labels: pr: :lollipop: Enhancement

#2467 [app-review] Split component mobile Skills and update props & types
  packages/@coorpacademy-app-review/src/views/skills/index.ts
  packages/@coorpacademy-app-review/src/views/skills/test/skills.test.ts
  packages/@coorpacademy-components/src/molecule/skill-card/index.native.tsx
  packages/@coorpacademy-components/src/molecule/skill-card/prop-types.ts
  packages/@coorpacademy-components/src/organism/review-no-skills/index.js
  packages/@coorpacademy-components/src/organism/review-no-skills/index.native.tsx
  packages/@coorpacademy-components/src/organism/review-no-skills/prop-types.ts
  packages/@coorpacademy-components/src/organism/review-no-skills/style.css
  packages/@coorpacademy-components/src/organism/review-no-skills/test/fixtures/no-skills.js
  packages/@coorpacademy-components/src/organism/review-skills/index.js
  packages/@coorpacademy-components/src/organism/review-skills/index.native.tsx
  packages/@coorpacademy-components/src/organism/review-skills/prop-types.js
  packages/@coorpacademy-components/src/organism/review-skills/prop-types.ts
  packages/@coorpacademy-components/src/organism/review-skills/style.css
  packages/@coorpacademy-components/src/organism/review-skills/test/fixtures/many-skills.js
  packages/@coorpacademy-components/src/template/app-review/index.native.tsx
  packages/@coorpacademy-components/src/template/app-review/index.tsx
  packages/@coorpacademy-components/src/template/app-review/prop-types.ts
  packages/@coorpacademy-components/src/template/app-review/skills/index.js
  packages/@coorpacademy-components/src/template/app-review/skills/index.native.tsx
  packages/@coorpacademy-components/src/template/app-review/skills/prop-types.ts
  packages/@coorpacademy-components/src/template/app-review/skills/stories.tsx
  packages/@coorpacademy-components/src/template/app-review/skills/style.css
  packages/@coorpacademy-components/src/template/app-review/skills/test/fixtures/loading.js
  packages/@coorpacademy-components/src/template/app-review/skills/test/fixtures/many-skills.js
  packages/@coorpacademy-components/src/template/app-review/skills/test/fixtures/no-skills.js
  packages/@coorpacademy-components/src/template/review-dashboard-skills/index.js
  packages/@coorpacademy-components/src/template/review-dashboard-skills/test/fixtures/loading.js
  packages/@coorpacademy-components/src/template/review-dashboard-skills/test/fixtures/many-skills.js
  packages/@coorpacademy-components/src/template/review-dashboard-skills/test/fixtures/no-skills.js
Labels: pr: :wrench: Refactoring

#2461 [app-review] update mapStateToSkillsProps
  packages/@coorpacademy-app-review/locales/en/review.json
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-skills.test.ts
  packages/@coorpacademy-app-review/src/index.tsx
  packages/@coorpacademy-app-review/src/test/util/services.mock.ts
  packages/@coorpacademy-app-review/src/views/skills/index.ts
  packages/@coorpacademy-app-review/src/views/skills/test/skills.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.free-text.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-drag.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-graphic.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-slider-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.template.on-change.test.ts
Labels: pr: Upgrades :outbox_tray:

#2489 [app-review] udpate mapStateToSkillsProps function
  packages/@coorpacademy-app-review/locales/en/review.json
  packages/@coorpacademy-app-review/src/views/skills/index.ts
  packages/@coorpacademy-app-review/src/views/skills/test/skills.test.ts
Labels: pr: Upgrades :outbox_tray:

#2492 [mobile] modify component NavigationBar
  packages/@coorpacademy-components/src/organism/mobile-navigation/index.native.tsx
  packages/@coorpacademy-components/src/organism/mobile-navigation/test/fixtures/menu-selected-0.ts
  packages/@coorpacademy-components/src/organism/mobile-navigation/test/fixtures/menu-selected-1.ts
  packages/@coorpacademy-components/src/organism/mobile-navigation/test/fixtures/menu-selected-2.ts
  packages/@coorpacademy-components/src/organism/mobile-navigation/test/on-press.test.tsx
Labels: pr: :lollipop: Enhancement

#2490 Set primary skin color quit popin
  packages/@coorpacademy-app-review/sandbox/index.tsx
  packages/@coorpacademy-app-review/src/index.tsx
  packages/@coorpacademy-app-review/src/test/index.test.tsx
  packages/@coorpacademy-app-review/src/test/util/services.mock.ts
  packages/@coorpacademy-app-review/src/types/common.ts
  packages/@coorpacademy-app-review/src/views/skills/test/skills.test.ts
  packages/@coorpacademy-app-review/src/views/slides/index.ts
  packages/@coorpacademy-app-review/src/views/slides/test/button-revising.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/skin.ts
  packages/@coorpacademy-app-review/src/views/slides/test/header.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/on-quit-popin.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.free-text.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.next-slide.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-drag.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-graphic.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-slider-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.template.on-change.test.ts
  packages/@coorpacademy-components/src/molecule/cm-popin/index.js
  packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/on-review-quit.ts
  packages/@coorpacademy-components/src/molecule/cm-popin/types.ts
Labels: pr: :lollipop: Enhancement

#2494 Fix popin-end in scorm mode
  packages/@coorpacademy-components/src/template/app-player/popin-header/index.js
  packages/@coorpacademy-components/src/template/app-player/popin-header/style.css
Labels: bug

#2495 Change CTA next question color in CorrectionPopinProps
  packages/@coorpacademy-components/src/molecule/cm-popin/style.css
  packages/@coorpacademy-components/src/molecule/review-correction-popin/style.css
  packages/@coorpacademy-components/src/variables/colors.css
  packages/@coorpacademy-components/src/variables/colors.ts
  packages/@coorpacademy-components/src/variables/theme.native.ts
Labels: pr: :lollipop: Enhancement

#2498 [mobile] fix dashboard skills style
  packages/@coorpacademy-components/src/template/app-review/skills/index.native.tsx
Labels: pr: :bug: Bug Fix

#2502 Fix slide writable on post answer
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-correction.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-slides-to-review-by-skill-ref.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-answer.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/next-slide.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/slide.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/slide.test.ts
  packages/@coorpacademy-app-review/src/views/slides/index.ts
  packages/@coorpacademy-app-review/src/views/slides/test/button-revising.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/header.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/on-quit-popin.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.free-text.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.next-slide.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-drag.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-graphic.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-slider-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.template.on-change.test.ts
  packages/@coorpacademy-components/src/organism/review-slide/index.js
  packages/@coorpacademy-components/src/organism/review-slide/prop-types.ts
Labels: pr: :bug: Bug Fix

#2507 fix restack slide style
  packages/@coorpacademy-components/src/organism/review-stacked-slides/style.css
Labels: pr: :bug: Bug Fix

#2511 Add prevent publish script on non-master branches, refactor review-components data test ids for e2e purposes
  package.json
  packages/@coorpacademy-components/src/molecule/review-correction-popin/index.js
  packages/@coorpacademy-components/src/organism/review-congrats/index.js
  packages/@coorpacademy-components/src/organism/review-congrats/test/review-congrats.js
  packages/@coorpacademy-components/src/organism/review-header/index.js
  packages/@coorpacademy-components/src/organism/review-header/test/review-header.js
  packages/@coorpacademy-components/src/organism/review-slide/index.js
  packages/@coorpacademy-components/src/template/app-review/player/index.js
  scripts/prevent-master-publish.sh
Labels: pr: :rocket: New feature, pr: :wrench: Refactoring

#2512 fix tests
  packages/@coorpacademy-components/src/atom/button-link/index.js
  packages/@coorpacademy-components/src/atom/button-link/test/fixtures/link-tertiary-no-icon.js
  packages/@coorpacademy-components/src/organism/review-congrats/test/review-congrats.js
Labels: pr: :bug: Bug Fix

#2513 fix review dashboard skills mobile style
  packages/@coorpacademy-components/src/template/app-review/skills/style.css
  packages/@coorpacademy-components/src/template/review-dashboard-skills/style.css
Labels: pr: :bug: Bug Fix

#2505 [mobile] add Popin component
  packages/@coorpacademy-components/src/atom/text/index.native.tsx
  packages/@coorpacademy-components/src/atom/text/test/fixtures/default.tsx
  packages/@coorpacademy-components/src/hoc/touchable/index.native.tsx
  packages/@coorpacademy-components/src/molecule/review-correction-popin/index.native.tsx
  packages/@coorpacademy-components/src/molecule/review-correction-popin/prop-types.ts
  packages/@coorpacademy-components/src/molecule/review-correction-popin/test/fixtures/wrong.js
  packages/@coorpacademy-components/src/molecule/review-correction-popin/test/on-press.test.tsx
  packages/@coorpacademy-components/src/organism/review-slide/index.native.tsx
  packages/@coorpacademy-components/src/organism/review-slide/test/fixtures/choices-selected.js
  packages/@coorpacademy-components/src/organism/review-slide/test/fixtures/initial-state.js
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/all-ok.ts
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/first-correct.ts
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/restack.ts
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/second-wrong.ts
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/unstack.ts
  packages/@coorpacademy-components/src/organism/review-stacked-slides/test/fixtures/wrong.ts
Labels: pr: :rocket: New feature
