Repository CoorpAcademy/components, pull requests merged in 2022-10, with the labels that each got.

#2416 workaround to fix DnD bug
  packages/@coorpacademy-components/src/molecule/draggable/style.css
Labels: bug

#2413 Add quit popin app review
  packages/@coorpacademy-app-review/nyc.config.js
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-correction.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-rank.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-skills.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-slide.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-answer.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-progression.test.ts
  packages/@coorpacademy-app-review/src/actions/data/test/token.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/quit-popin.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/answers.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/next-slide.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/quit-popin.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/slides.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/index.ts
  packages/@coorpacademy-app-review/src/reducers/ui/quit-popin.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/quit-popin.test.ts
  packages/@coorpacademy-app-review/src/views/skills/test/skills.test.ts
  packages/@coorpacademy-app-review/src/views/slides/index.ts
  packages/@coorpacademy-app-review/src/views/slides/test/header.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/on-quit-popin.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.free-text.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.next-slide.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-drag.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-graphic.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-slider-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.template.on-change.test.ts
Labels: pr: :rocket: New feature

#2422 Migrate input search atom test to testing-library
  packages/@coorpacademy-components/src/atom/input-search/test/change.js
Labels: pr: :lollipop: Enhancement

#2430 [app-review] add service fetchSlidesBySkill + mock
  packages/@coorpacademy-app-review/ava.config.js
  packages/@coorpacademy-app-review/sandbox/index.tsx
  packages/@coorpacademy-app-review/src/services/fetch-slides-to-review-by-skill-ref.ts
  packages/@coorpacademy-app-review/src/services/index.ts
  packages/@coorpacademy-app-review/src/services/test/fetch-slides-to-review-by-skill-ref.test.ts
  packages/@coorpacademy-app-review/src/test/index.test.tsx
  packages/@coorpacademy-app-review/src/test/util/services.mock.ts
  packages/@coorpacademy-app-review/src/types/common.ts
  packages/@coorpacademy-app-review/webpack.config.js
Labels: pr: :rocket: New feature

#2419 fix responsive exit node retry button
  packages/@coorpacademy-components/src/template/app-player/popin-end/summary.css
Labels: bug

#2455 [app-review] add reducer showButtonRevising
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-correction.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-rank.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-skills.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-slide.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/fetch-slides-to-review-by-skill-ref.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-answer.test.ts
  packages/@coorpacademy-app-review/src/actions/api/test/post-progression.test.ts
  packages/@coorpacademy-app-review/src/actions/data/test/token.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/answers.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/navigation.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/next-slide.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/quit-popin.test.ts
  packages/@coorpacademy-app-review/src/actions/ui/test/slides.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/index.ts
  packages/@coorpacademy-app-review/src/reducers/ui/show-button-revising.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/show-button-revising.test.ts
  packages/@coorpacademy-app-review/src/views/skills/test/skills.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/header.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/on-quit-popin.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.free-text.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.next-slide.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-drag.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-graphic.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-slider-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.template.on-change.test.ts
Labels: pr: :rocket: New feature

#2457 [app-review] update stateMapToProps
  packages/@coorpacademy-app-review/src/actions/api/post-progression.ts
  packages/@coorpacademy-app-review/src/reducers/data/corrections.ts
  packages/@coorpacademy-app-review/src/reducers/data/progression.ts
  packages/@coorpacademy-app-review/src/reducers/data/rank.ts
  packages/@coorpacademy-app-review/src/reducers/data/skills.ts
  packages/@coorpacademy-app-review/src/reducers/data/slides.ts
  packages/@coorpacademy-app-review/src/reducers/data/test/corrections.test.ts
  packages/@coorpacademy-app-review/src/reducers/data/test/progression.test.ts
  packages/@coorpacademy-app-review/src/reducers/data/test/rank.test.ts
  packages/@coorpacademy-app-review/src/reducers/data/test/slides.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/answers.ts
  packages/@coorpacademy-app-review/src/reducers/ui/current-slide-ref.ts
  packages/@coorpacademy-app-review/src/reducers/ui/positions.ts
  packages/@coorpacademy-app-review/src/reducers/ui/show-button-revising.ts
  packages/@coorpacademy-app-review/src/reducers/ui/show-congrats.ts
  packages/@coorpacademy-app-review/src/reducers/ui/slide.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/answers.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/current-slide-ref.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/positions.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/show-button-revising.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/show-congrats.test.ts
  packages/@coorpacademy-app-review/src/reducers/ui/test/slide.test.ts
  packages/@coorpacademy-app-review/src/views/slides/index.ts
  packages/@coorpacademy-app-review/src/views/slides/test/button-revising.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
Labels: pr: :rocket: New feature

#2459 [app-review] update mapStateToSlidesProps for button revise skill
  packages/@coorpacademy-app-review/src/reducers/ui/test/show-congrats.test.ts
  packages/@coorpacademy-app-review/src/views/slides/index.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
Labels: pr: :rocket: New feature

#2460 Bug fix - display quit popin
  packages/@coorpacademy-components/src/template/app-review/player/index.js
  packages/@coorpacademy-components/src/template/app-review/player/style.css
Labels: pr: :bug: Bug Fix

#2468 Fix i18n issues
  packages/@coorpacademy-app-review/locales/en/review.json
  packages/@coorpacademy-app-review/src/views/slides/index.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.free-text.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-drag.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-graphic.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-slider-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.template.on-change.test.ts
Labels: pr: :bug: Bug Fix
