Repository CoorpAcademy/components, pull requests merged in 2022-07, with the labels that each got.

#2257 Fix import and export computeNextStepAfterAnswerForReview function
  packages/@coorpacademy-progression-engine/src/index.js
Labels: pr: :bug: Bug Fix

#2259 Create go1 banner
  packages/@coorpacademy-components/src/molecule/cm-popin/index.js
  packages/@coorpacademy-components/src/molecule/cm-popin/style.css
  packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/go1-popin.js
  packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/warning-with-close.js
  packages/@coorpacademy-components/src/molecule/go1-banner/index.js
  packages/@coorpacademy-components/src/molecule/go1-banner/style.css
  packages/@coorpacademy-components/src/molecule/go1-banner/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/go1-banner/test/handle-test.js
  packages/@coorpacademy-components/src/organism/brand-dashboard/index.js
  packages/@coorpacademy-components/src/organism/brand-dashboard/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/quick-access.js
  packages/@coorpacademy-components/src/variables/colors.css
  packages/@coorpacademy-components/storybook/components.js
Labels: enhancement

#2262 [R&D] react testing tools: link, provider, social-link, tab atoms
  packages/@coorpacademy-components/src/atom/link/test/index.js
  packages/@coorpacademy-components/src/atom/provider/test/index.js
  packages/@coorpacademy-components/src/atom/social-link/test/social-link-test.js
  packages/@coorpacademy-components/src/atom/tab/index.js
  packages/@coorpacademy-components/src/atom/tab/test/on-click.js
Labels: pr: :lollipop: Enhancement

#2261 Add CREATE_PROGRESSION action
  packages/@coorpacademy-app-review/src/actions/data/progression.ts
  packages/@coorpacademy-app-review/src/actions/data/slides.ts
  packages/@coorpacademy-app-review/src/actions/data/token.ts
  packages/@coorpacademy-app-review/src/actions/index.ts
  packages/@coorpacademy-app-review/src/configure-store.ts
  packages/@coorpacademy-app-review/src/index.test.tsx
  packages/@coorpacademy-app-review/src/middlewares/on-receive-progression.test.ts
  packages/@coorpacademy-app-review/src/middlewares/on-receive-progression.ts
  packages/@coorpacademy-app-review/src/middlewares/on-start-app.test.ts
  packages/@coorpacademy-app-review/src/middlewares/on-start-app.ts
  packages/@coorpacademy-app-review/src/reducers/data/progression.ts
  packages/@coorpacademy-app-review/src/reducers/data/slides.ts
  packages/@coorpacademy-app-review/src/services/fetch-skills.ts
  packages/@coorpacademy-app-review/src/services/fetch-slide.ts
  packages/@coorpacademy-app-review/src/services/post-progression.mock.ts
  packages/@coorpacademy-app-review/src/services/post-progression.test.ts
  packages/@coorpacademy-app-review/src/services/post-progression.ts
  packages/@coorpacademy-app-review/src/services/tools/fetch-responses.ts
  packages/@coorpacademy-app-review/src/services/tools/sleep.ts
  packages/@coorpacademy-app-review/src/types/common.ts
  packages/@coorpacademy-app-review/src/types/ui-progression.ts
  packages/@coorpacademy-components/src/template/app-review/slides/index.js
  packages/@coorpacademy-components/src/template/app-review/slides/prop-types.js
  packages/@coorpacademy-components/src/template/app-review/slides/test/fixtures/one-fail.js
  packages/@coorpacademy-components/src/template/app-review/slides/test/fixtures/one-right.js
Labels: pr: :rocket: New feature, pr: :wrench: Refactoring

#2271 Fix podcast in mobile mode
  packages/@coorpacademy-components/src/molecule/external-content-viewer/index.js
  packages/@coorpacademy-components/src/molecule/external-content-viewer/test/fixtures/podcast-default.js
  packages/@coorpacademy-components/src/molecule/external-content-viewer/test/fixtures/podcast-mobile.js
  packages/@coorpacademy-components/storybook/components.js
Labels: bug

#2277 [R&D] React TestingLibrary (Atoms): Drag & Drop, input checkbox, input switch
  packages/@coorpacademy-components/src/atom/drag-and-drop/index.js
  packages/@coorpacademy-components/src/atom/drag-and-drop/test/dragging.js
  packages/@coorpacademy-components/src/atom/input-checkbox/index.js
  packages/@coorpacademy-components/src/atom/input-checkbox/test/on-change.js
  packages/@coorpacademy-components/src/atom/input-switch/index.js
  packages/@coorpacademy-components/src/atom/input-switch/test/on-change.js
Labels: pr: :lollipop: Enhancement

#2278 Remove button coach
  packages/@coorpacademy-player-web/src/map-state-to-props/player.js
  packages/@coorpacademy-player-web/src/map-state-to-props/test/player.js
  packages/@coorpacademy-player-web/src/views/test/slide.js
Labels: pr: :rocket: New feature

#2267 popine no access
  packages/@coorpacademy-components/src/index.js
  packages/@coorpacademy-components/src/molecule/cm-popin/index.js
  packages/@coorpacademy-components/src/molecule/cm-popin/style.css
  packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/no-access.js
  packages/@coorpacademy-components/src/template/app-player/popin-no-access/index.js
  packages/@coorpacademy-components/src/template/app-player/popin-no-access/test/fixtures/default.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :rocket: New feature

#2274 ApiSlide to UiSlide mapping function
  packages/@coorpacademy-app-review/.eslintignore
  packages/@coorpacademy-app-review/src/actions/ui/navigation.ts
  packages/@coorpacademy-app-review/src/fixtures/qcm-slide.ts
  packages/@coorpacademy-app-review/src/helpers/map-api-slide-to-ui.ts
  packages/@coorpacademy-app-review/src/helpers/test/fixtures/free-text.ts
  packages/@coorpacademy-app-review/src/helpers/test/fixtures/qcm-drag.ts
  packages/@coorpacademy-app-review/src/helpers/test/fixtures/qcm-graphic.ts
  packages/@coorpacademy-app-review/src/helpers/test/fixtures/qcm.ts
  packages/@coorpacademy-app-review/src/helpers/test/fixtures/select-template.ts
  packages/@coorpacademy-app-review/src/helpers/test/fixtures/slider.ts
  packages/@coorpacademy-app-review/src/helpers/test/fixtures/text-template.ts
  packages/@coorpacademy-app-review/src/helpers/test/map-api-slide-to-ui.test.ts
  packages/@coorpacademy-app-review/src/index.tsx
  packages/@coorpacademy-app-review/src/reducers/ui/navigation.ts
  packages/@coorpacademy-app-review/src/test/index.test.tsx
  packages/@coorpacademy-app-review/src/test/util/services.mock.ts
  packages/@coorpacademy-app-review/src/types/common.ts
  packages/@coorpacademy-app-review/src/types/slides.ts
  packages/@coorpacademy-components/src/template/app-review/prop-types.js
  packages/@coorpacademy-components/src/template/app-review/slides/index.js
Labels: pr: :rocket: New feature

#2280 ecran-une-erreur-est-survenue
  packages/@coorpacademy-components/src/molecule/cm-popin/index.js
  packages/@coorpacademy-components/src/molecule/cm-popin/style.css
  packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/error-with-close.js
  packages/@coorpacademy-components/src/template/app-player/player/index.js
  packages/@coorpacademy-components/src/template/app-player/player/test/fixtures/popin-error.js
  packages/@coorpacademy-components/src/template/app-player/player/test/popin-error.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :rocket: New feature
