Repository CoorpAcademy/components, pull requests merged in 2022-12, with the labels that each got.

#2518 translate html tag for help in review slide
  packages/@coorpacademy-components/src/organism/review-slide/index.js
Labels: pr: :bug: Bug Fix

#2522 [RGAA] add arialable to search input
  packages/@coorpacademy-components/src/atom/input-search/index.js
Labels: RGAA

#2533 [review] add molecule ReviewBanner in component template CommonDashboard
  packages/@coorpacademy-components/src/template/common/dashboard/index.js
  packages/@coorpacademy-components/src/template/common/dashboard/test/fixtures/cookie-dashboard.js
  packages/@coorpacademy-components/src/template/common/dashboard/test/fixtures/cookie-settings-dashboard.js
  packages/@coorpacademy-components/src/template/common/dashboard/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/common/dashboard/test/fixtures/empty-requests.js
Labels: pr: :lollipop: Enhancement

#2534 [RGAA] Player: Alternative textuelle pour les <img> porteuses d'informations
  packages/@coorpacademy-components/src/molecule/discipline-partners/index.js
  packages/@coorpacademy-components/src/molecule/discipline-partners/test/fixtures/more-info.js
Labels: RGAA

#2536 [RGAA]add alt to profile picture
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/logged-with-battle-notifications.js
Labels: RGAA

#2539 [RGAA] add active page aria label
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/default.js
Labels: RGAA

#2538 [RGAA] Dashboard : Alternative textuelle pour les <svg> porteuses d'informations
  packages/@coorpacademy-components/src/molecule/card-content/index.js
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/index.js
  packages/@coorpacademy-components/src/template/common/dashboard/index.js
Labels: RGAA

#2529 [RGAA]Fix template activity mobile style
  packages/@coorpacademy-components/src/template/activity/engine-stars.css
  packages/@coorpacademy-components/src/template/activity/stars-summary.css
  packages/@coorpacademy-components/src/template/activity/stars-summary.js
  packages/@coorpacademy-components/src/template/activity/style.css
  packages/@coorpacademy-components/src/template/activity/test/handles-test.js
Labels: RGAA

#2543 [RGAA]Discussions + battles + MonCompte + Header: Alternative textuelle pour les <svg> porteuses d'informations
  packages/@coorpacademy-components/src/atom/select/index.js
  packages/@coorpacademy-components/src/organism/get-the-app/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
Labels: RGAA

#2545 [RGAA][Quick Fix] : web style regression- template activity
  packages/@coorpacademy-components/src/template/activity/stars-summary.css
  packages/@coorpacademy-components/src/template/activity/stars-summary.js
Labels: RGAA

#2547 [RGAA] refacto <div> element to <ul> in Stars box in template activity
  packages/@coorpacademy-components/src/template/activity/stars-summary.css
  packages/@coorpacademy-components/src/template/activity/stars-summary.js
Labels: pr: :lollipop: Enhancement, RGAA

#2544 [RGAA] add aria label to faq link
  packages/@coorpacademy-components/src/organism/mooc-footer/index.js
  packages/@coorpacademy-components/src/organism/mooc-footer/test/fixtures/default.js
Labels: RGAA
