Repository CoorpAcademy/components, pull requests merged in 2022-06, with the labels that each got.

#2227 Move ReviewDashboardSkills out of app-review
  packages/@coorpacademy-components/src/template/app-review/review-dashboard-skills/test/fixtures/loading.js
  packages/@coorpacademy-components/src/template/app-review/review-dashboard-skills/test/fixtures/many-skills.js
  packages/@coorpacademy-components/src/template/app-review/review-dashboard-skills/test/fixtures/no-skills.js
  packages/@coorpacademy-components/src/template/app-review/root-view/prop-types.js
  packages/@coorpacademy-components/src/template/app-review/root-view/root-view.js
  packages/@coorpacademy-components/src/template/review-dashboard-skills/index.js
  packages/@coorpacademy-components/src/template/review-dashboard-skills/style.css
  packages/@coorpacademy-components/src/template/review-dashboard-skills/test/fixtures/loading.js
  packages/@coorpacademy-components/src/template/review-dashboard-skills/test/fixtures/many-skills.js
  packages/@coorpacademy-components/src/template/review-dashboard-skills/test/fixtures/no-skills.js
  packages/@coorpacademy-components/storybook/components.js
Labels: pr: :wrench: Refactoring

#2231 [R&D] react testing tools: cta
  packages/@coorpacademy-components/src/atom/cta/index.js
  packages/@coorpacademy-components/src/atom/cta/test/cta.js
  packages/@coorpacademy-components/src/atom/cta/test/hover.js
Labels: pr: :lollipop: Enhancement

#2233 Bugfix card and tooltip
  packages/@coorpacademy-components/src/atom/review-presentation/style.css
  packages/@coorpacademy-components/src/atom/review-presentation/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/skill-card/style.css
  packages/@coorpacademy-components/src/organism/review-skills/style.css
  packages/@coorpacademy-components/src/template/review-dashboard-skills/style.css
Labels: pr: :bug: Bug Fix

#2252 add total courses in courses setion
  packages/@coorpacademy-components/src/molecule/course-sections/index.js
  packages/@coorpacademy-components/src/molecule/course-sections/style.css
  packages/@coorpacademy-components/src/molecule/course-sections/test/fixtures/with-mandatory-courses-input.js
Labels: pr: :rocket: New feature
