Repository CoorpAcademy/components, pull requests merged in 2022-01, with the labels that each got.

#2083 fix platformlist button
  packages/@coorpacademy-components/src/organism/setup-header/style.css
Labels: pr: :bug: Bug Fix

#2087 fix summary size and position
  packages/@coorpacademy-components/src/molecule/wizard-summary/style.css
  packages/@coorpacademy-components/src/organism/wizard-contents/style.css
Labels: pr: :bug: Bug Fix

#2092 CM Loader Tweaks
  packages/@coorpacademy-components/src/organism/course-selection/index.js
  packages/@coorpacademy-components/src/organism/course-selection/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/search-and-chips-results/index.js
  packages/@coorpacademy-components/src/organism/search-and-chips-results/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/wizard-contents/index.js
  packages/@coorpacademy-components/src/organism/wizard-contents/style.css
Labels: pr: :lollipop: Enhancement

#2093 close summary when click out side
  packages/@coorpacademy-components/src/molecule/wizard-summary/index.js
Labels: pr: :bug: Bug Fix

#2103 move the loader at the component level
  packages/@coorpacademy-components/src/organism/course-selection/index.js
  packages/@coorpacademy-components/src/organism/course-selection/style.css
  packages/@coorpacademy-components/src/organism/search-and-chips-results/index.js
  packages/@coorpacademy-components/src/organism/search-and-chips-results/style.css
  packages/@coorpacademy-components/src/organism/wizard-contents/index.js
  packages/@coorpacademy-components/src/organism/wizard-contents/style.css
Labels: pr: :lollipop: Enhancement

#2107 Fix empty resource url bug in mobile
  packages/@coorpacademy-player-store/src/utils/state-extract.js
Labels: pr: :bug: Bug Fix

#2105 remove tolower when fuzzyMatching is activated for template text ques…
  packages/@coorpacademy-progression-engine/src/check-answer-correctness.js
  packages/@coorpacademy-progression-engine/src/test/check-answer-correctness.qcm-drag.js
  packages/@coorpacademy-progression-engine/src/test/check-answer-correctness.qcm-graphic.js
  packages/@coorpacademy-progression-engine/src/test/check-answer-correctness.qcm.js
  packages/@coorpacademy-progression-engine/src/test/check-answer-correctness.template.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement
