Repository CoorpAcademy/components, pull requests merged in 2023-05, with the labels that each got.

#2725 [RGAA] Rgaa-9.2 structured document
  packages/@coorpacademy-components/src/molecule/scope-tabs/index.js
  packages/@coorpacademy-components/src/organism/mooc-footer/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/template/app-player/player/slides/footer/index.js
Labels: RGAA

#2727 Fix activity UI bugs
  packages/@coorpacademy-components/src/organism/mooc-header/style.css
  packages/@coorpacademy-components/src/template/activity/stars-summary.css
  packages/@coorpacademy-components/src/template/activity/stars-summary.js
Labels: pr: :bug: Bug Fix

#2726 [RGAA - regression fix] fix scope content condition
  packages/@coorpacademy-components/src/molecule/scope-tabs/index.js
Labels: pr: :bug: Bug Fix, RGAA

#2729 Hotfix, clash pop-in
  packages/@coorpacademy-components/src/organism/mooc-header/style.css
Labels: pr: :bug: Bug Fix

#2733 [Review] Gtm callbacks
  packages/@coorpacademy-app-review/sandbox/index.tsx
  packages/@coorpacademy-app-review/src/actions/api/post-answer.ts
  packages/@coorpacademy-app-review/src/actions/api/post-progression.ts
  packages/@coorpacademy-app-review/src/actions/test/create-test-store.ts
  packages/@coorpacademy-app-review/src/configure-store.ts
  packages/@coorpacademy-app-review/src/index.tsx
  packages/@coorpacademy-app-review/src/types/common.ts
  packages/@coorpacademy-app-review/src/views/slides/test/button-revising.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/on-quit-popin.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.free-text.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.next-slide.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-drag.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm-graphic.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.qcm.on-click.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.slider.on-slider-change.test.ts
  packages/@coorpacademy-app-review/src/views/slides/test/slide.template.on-change.test.ts
Labels: pr: :lollipop: Enhancement
