Repository CoorpAcademy/components, pull requests merged in 2023-09, with the labels that each got.

#2774 add icon to the link type
  packages/@coorpacademy-components/src/organism/sidebar/index.js
  packages/@coorpacademy-components/src/organism/sidebar/style.css
  packages/@coorpacademy-components/src/organism/sidebar/test/fixtures/default.js
Labels: WIP

#2799 [R&D] testing-library: Card lists test migration
  packages/@coorpacademy-components/src/molecule/card/index.js
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/index.js
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/prop-types.ts
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/test/index.js
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/test/index.tsx
Labels: R&D

#2800 design ok > next step canary for CM
  packages/@coorpacademy-components/src/molecule/banner/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/style.css
  packages/@coorpacademy-components/src/variables/colors.css
Labels: pr: :bug: Bug Fix

#2805 [massive-battle] modify TitleAndCheckBoxWrapper and SelectOpponents components
  packages/@coorpacademy-components/src/molecule/title-and-checkbox-wrapper/index.js
  packages/@coorpacademy-components/src/organism/select-opponents/index.tsx
  packages/@coorpacademy-components/src/organism/select-opponents/style.css
  packages/@coorpacademy-components/src/organism/select-opponents/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/select-opponents/types.ts
Labels: pr: :lollipop: Enhancement
