Repository CoorpAcademy/components, pull requests merged in 2023-06, with the labels that each got.

#2744 [RGAA] 11.1 & 2: Use the same "Add your comment" trad for the placeholder + title + aria-label on Discussion text field
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/molecule/forum/forum-comment/index.js
Labels: RGAA

#2746 [RGAA] replace icons
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/content-edition/content-book.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/content-edition/content-book.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/objects/binoculars.1.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/objects/binoculars.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/objects/binoculars.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/phone/mobile-phone.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/phone/mobile-phone.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-line.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-line.iconjar/icons/binoculars.1.svg
  packages/@coorpacademy-nova-icons/third-party/nova-line.iconjar/icons/binoculars.svg
  packages/@coorpacademy-nova-icons/third-party/nova-line.iconjar/icons/content-book.svg
  packages/@coorpacademy-nova-icons/third-party/nova-line.iconjar/icons/mobile-phone.svg
Labels: RGAA

#2745 [RGAA] 11: Adds aria-label and title
  packages/@coorpacademy-components/src/atom/input-switch/index.js
  packages/@coorpacademy-components/src/organism/user-preferences/index.js
Labels: RGAA

#2748 [R&D] Migrate molecules tests to testing-library
  packages/@coorpacademy-components/src/molecule/external-content-viewer/test/podcast.js
  packages/@coorpacademy-components/src/molecule/external-content-viewer/test/podcast.tsx
  packages/@coorpacademy-components/src/molecule/filters/test/index.js
  packages/@coorpacademy-components/src/molecule/filters/test/index.tsx
  packages/@coorpacademy-components/src/molecule/go1-banner/test/handle-test.js
  packages/@coorpacademy-components/src/molecule/go1-banner/test/handle-test.tsx
  packages/@coorpacademy-components/src/molecule/hero/test/handle-test.js
  packages/@coorpacademy-components/src/molecule/hero/test/handle-test.tsx
  packages/@coorpacademy-components/src/molecule/questions/template/test/index.tsx
Labels: pr: :lollipop: Enhancement

#2750 fix icons colors
  packages/@coorpacademy-nova-icons/src/components/nova-line/content-edition/content-book.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/content-edition/content-book.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/objects/binoculars.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/objects/binoculars.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/phone/mobile-phone.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/phone/mobile-phone.native.js
  packages/@coorpacademy-nova-icons/third-party/nova-line.iconjar/icons/binoculars.svg
  packages/@coorpacademy-nova-icons/third-party/nova-line.iconjar/icons/content-book.svg
  packages/@coorpacademy-nova-icons/third-party/nova-line.iconjar/icons/mobile-phone.svg
Labels: RGAA

#2739 [RGAA] refacto div to nav in mooc header
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
Labels: RGAA

#2753 modif notification animation time
  packages/@coorpacademy-components/src/molecule/banner/style.css
Labels: pr: :lollipop: Enhancement

#2749 [massive-battle] modify components for massive battle form
  packages/@coorpacademy-components/src/atom/autocomplete/index.js
  packages/@coorpacademy-components/src/atom/autocomplete/style.css
  packages/@coorpacademy-components/src/molecule/select-multiple/index.js
  packages/@coorpacademy-components/src/molecule/select-multiple/style.css
  packages/@coorpacademy-components/src/organism/brand-form/index.js
  packages/@coorpacademy-components/src/organism/brand-form/test/fixtures/animations.js
  packages/@coorpacademy-components/src/organism/brand-form/test/index.js
  packages/@coorpacademy-components/src/organism/brand-form/test/index.tsx
  packages/@coorpacademy-components/src/template/back-office/brand-update/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/animations.js
Labels: pr: :rocket: New feature

#2756 fix select style
  packages/@coorpacademy-components/src/atom/select/style.css
Labels: pr: :bug: Bug Fix

#2757 fix popin content
  packages/@coorpacademy-components/src/molecule/cm-popin/style.css
Labels: pr: :bug: Bug Fix

#2752 [R&D] Migrate molecules tests to testing-library
  packages/@coorpacademy-components/src/molecule/questions/free-text/test/free-text.js
  packages/@coorpacademy-components/src/molecule/questions/free-text/test/free-text.tsx
  packages/@coorpacademy-components/src/molecule/search-form/test/submit.tsx
  packages/@coorpacademy-components/src/organism/mooc-footer/test/footer.js
  packages/@coorpacademy-components/src/organism/mooc-footer/test/footer.tsx
  packages/@coorpacademy-components/src/organism/mooc-header/test/header.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/header.tsx
  packages/@coorpacademy-components/src/organism/review-header/test/review-header.js
  packages/@coorpacademy-components/src/organism/review-header/test/review-header.tsx
Labels: pr: :lollipop: Enhancement

#2761 RGAA: 11.4 - Filters switch, move label to the right
  packages/@coorpacademy-components/src/molecule/filters/filters-wapper.css
  packages/@coorpacademy-components/src/molecule/filters/filters-wrapper.js
Labels: RGAA
