Repository CoorpAcademy/components, pull requests merged in 2023-07, with the labels that each got.

#2759 [R&D] Migrate molecules tests to testing-library
  packages/@coorpacademy-components/src/molecule/questions/qcm-graphic/test/qcm-graphic.js
  packages/@coorpacademy-components/src/molecule/questions/qcm-graphic/test/qcm-graphic.tsx
  packages/@coorpacademy-components/src/molecule/questions/qcm/test/qcm.js
  packages/@coorpacademy-components/src/molecule/questions/qcm/test/qcm.tsx
  packages/@coorpacademy-components/src/molecule/skill-card/test/skill-card.js
  packages/@coorpacademy-components/src/molecule/skill-card/test/skill-card.tsx
  packages/@coorpacademy-components/src/molecule/video-iframe/test/index.js
  packages/@coorpacademy-components/src/molecule/video-iframe/test/index.tsx
Labels: pr: :lollipop: Enhancement

#2763 [MassiveBattle] Input radio wrapper
  packages/@coorpacademy-components/src/atom/radio-with-title/index.tsx
  packages/@coorpacademy-components/src/atom/radio-with-title/test/fixtures/without-on-change.ts
  packages/@coorpacademy-components/src/atom/radio-with-title/test/on-change.tsx
  packages/@coorpacademy-components/src/atom/radio-with-title/types.ts
  packages/@coorpacademy-components/src/molecule/title-radio-wrapper/index.tsx
  packages/@coorpacademy-components/src/molecule/title-radio-wrapper/style.css
  packages/@coorpacademy-components/src/molecule/title-radio-wrapper/test/fixtures/select-cohortes.ts
  packages/@coorpacademy-components/src/molecule/title-radio-wrapper/test/fixtures/upload-users.ts
  packages/@coorpacademy-components/src/molecule/title-radio-wrapper/test/fixtures/without-radio-title.ts
  packages/@coorpacademy-components/src/molecule/title-radio-wrapper/types.ts
Labels: pr: :construction: Work In Progress

#2765 [MassiveBattle] Create Select Opponents Component
  packages/@coorpacademy-components/src/atom/image-upload/style.css
  packages/@coorpacademy-components/src/atom/radio-with-title/index.tsx
  packages/@coorpacademy-components/src/atom/radio-with-title/test/fixtures/default.ts
  packages/@coorpacademy-components/src/atom/radio-with-title/test/on-change.tsx
  packages/@coorpacademy-components/src/atom/title/index.js
  packages/@coorpacademy-components/src/atom/title/style.css
  packages/@coorpacademy-components/src/molecule/title-radio-wrapper/test/fixtures/select-cohortes.ts
  packages/@coorpacademy-components/src/molecule/title-radio-wrapper/test/fixtures/upload-users.ts
  packages/@coorpacademy-components/src/organism/select-opponents/index.tsx
  packages/@coorpacademy-components/src/organism/select-opponents/style.css
  packages/@coorpacademy-components/src/organism/select-opponents/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/select-opponents/types.ts
Labels: pr: :rocket: New feature

#2767 [massive-battle] create new component and update `BrandFormGroup` component
  packages/@coorpacademy-components/src/atom/title/index.js
  packages/@coorpacademy-components/src/atom/title/style.css
  packages/@coorpacademy-components/src/molecule/brand-form-group/index.js
  packages/@coorpacademy-components/src/molecule/brand-form-group/style.css
  packages/@coorpacademy-components/src/molecule/brand-form-group/test/fixtures/cm-massive-battle.js
  packages/@coorpacademy-components/src/molecule/select-multiple/index.js
  packages/@coorpacademy-components/src/molecule/title-radio-wrapper/style.css
  packages/@coorpacademy-components/src/organism/brand-form/index.js
  packages/@coorpacademy-components/src/organism/brand-form/style.css
  packages/@coorpacademy-components/src/organism/title-and-input/index.tsx
  packages/@coorpacademy-components/src/organism/title-and-input/style.css
  packages/@coorpacademy-components/src/organism/title-and-input/test/fixtures/autocomplete-and-title.js
  packages/@coorpacademy-components/src/organism/title-and-input/test/fixtures/select-multiple-and-title.js
  packages/@coorpacademy-components/src/organism/title-and-input/test/fixtures/select-opponents-and-title.js
  packages/@coorpacademy-components/src/organism/title-and-input/types.ts
Labels: pr: :rocket: New feature

#2769 Update locked card style
  packages/@coorpacademy-components/src/molecule/card/index.js
  packages/@coorpacademy-components/src/molecule/card/style.css
  packages/@coorpacademy-components/src/molecule/card/test/fixtures/default.js
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/padlock.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/padlock.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/padlock.svg
Labels: pr: :lollipop: Enhancement

#2766 [R&D] Migrate components tests to testing-library
  packages/@coorpacademy-components/src/molecule/select-multiple/test/index.tsx
  packages/@coorpacademy-components/src/organism/accordion/container/test/on-click.js
  packages/@coorpacademy-components/src/organism/accordion/container/test/on-click.tsx
  packages/@coorpacademy-components/src/organism/accordion/toggler/test/on-click.js
  packages/@coorpacademy-components/src/organism/accordion/toggler/test/on-click.tsx
  packages/@coorpacademy-components/src/organism/accordion/toggler/test/render.js
  packages/@coorpacademy-components/src/organism/accordion/toggler/test/render.tsx
  packages/@coorpacademy-components/src/template/activity/test/progression-item-test.js
  packages/@coorpacademy-components/src/template/activity/test/progression-item.tsx
Labels: pr: :lollipop: Enhancement
