Repository CoorpAcademy/components, pull requests merged in 2023-04, with the labels that each got.

#2705 fix select multiple problems
  packages/@coorpacademy-components/src/molecule/select-multiple/index.js
  packages/@coorpacademy-components/src/organism/list-items/index.js
  packages/@coorpacademy-components/src/organism/list-items/style.css
Labels: bug

#2719 Migrate molecules tests to testing-library
  packages/@coorpacademy-components/src/molecule/brand-create-form/test/index.js
  packages/@coorpacademy-components/src/molecule/brand-create-form/test/index.tsx
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/test/bullet-point-menu-button.js
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/test/bullet-point-menu-button.tsx
  packages/@coorpacademy-components/src/molecule/external-content-button/index.js
  packages/@coorpacademy-components/src/molecule/external-content-button/test/on-click.js
  packages/@coorpacademy-components/src/molecule/external-content-button/test/on-click.tsx
Labels: pr: :lollipop: Enhancement

#2721 [RGAA] Rga11.1 aria label on player web and review slide
  packages/@coorpacademy-app-review/locales/en/review.json
  packages/@coorpacademy-app-review/src/types/slides.ts
  packages/@coorpacademy-app-review/src/views/slides/map-api-slide-to-ui.ts
  packages/@coorpacademy-app-review/src/views/slides/test/fixtures/template.ts
  packages/@coorpacademy-components/src/molecule/questions/free-text/index.js
  packages/@coorpacademy-components/src/molecule/questions/qcm-drag/index.js
  packages/@coorpacademy-components/src/molecule/questions/qcm-graphic/index.js
  packages/@coorpacademy-components/src/molecule/questions/qcm/index.js
  packages/@coorpacademy-components/src/molecule/questions/question-range/index.js
  packages/@coorpacademy-components/src/molecule/questions/template/index.js
  packages/@coorpacademy-components/src/molecule/questions/template/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/questions/template/test/fixtures/multiple.js
  packages/@coorpacademy-player-web/src/map-state-to-props/answer.js
  packages/@coorpacademy-player-web/src/map-state-to-props/test/answer.js
Labels: pr: :construction: Work In Progress, RGAA

#2724 [RGAA]add icons
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/content-edition/content-book.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/content-edition/content-book.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/messages-chat/chat-bubble-circle-question-mark.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/messages-chat/chat-bubble-circle-question-mark.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/network/network-alert.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/network/network-alert.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/objects/binoculars.1.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/objects/binoculars.1.native.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/phone/mobile-phone.js
  packages/@coorpacademy-nova-icons/src/components/nova-line/phone/mobile-phone.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-line.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-line.iconjar/icons/binoculars.1.svg
  packages/@coorpacademy-nova-icons/third-party/nova-line.iconjar/icons/chat-bubble-circle-question-mark.1.svg
  packages/@coorpacademy-nova-icons/third-party/nova-line.iconjar/icons/content-book.svg
  packages/@coorpacademy-nova-icons/third-party/nova-line.iconjar/icons/mobile-phone.svg
  packages/@coorpacademy-nova-icons/third-party/nova-line.iconjar/icons/network-alert.1.svg
Labels: RGAA

#2723 RGAA: validate button player 11.9
  packages/@coorpacademy-components/src/atom/cta/index.js
  packages/@coorpacademy-components/src/atom/cta/index.tsx
  packages/@coorpacademy-components/src/atom/cta/prop-types.ts
  packages/@coorpacademy-components/src/atom/cta/test/cta.js
  packages/@coorpacademy-components/src/atom/cta/test/fixtures/no-submit-value-button.js
  packages/@coorpacademy-components/src/atom/link/index.js
  packages/@coorpacademy-components/src/atom/link/test/fixtures/button-link.ts
  packages/@coorpacademy-components/src/globals.d.ts
  packages/@coorpacademy-player-web/locales/en/player.json
  packages/@coorpacademy-player-web/src/map-state-to-props/player.js
  packages/@coorpacademy-player-web/src/views/test/slide.js
Labels: pr: :lollipop: Enhancement, pr: :wrench: Refactoring, RGAA
