Repository CoorpAcademy/components, pull requests merged in 2023-10, with the labels that each got.

#2806 Bulk import update
  packages/@coorpacademy-components/src/atom/button-link/index.tsx
  packages/@coorpacademy-components/src/atom/button-link/style.css
  packages/@coorpacademy-components/src/atom/drag-and-drop/index.js
  packages/@coorpacademy-components/src/atom/drag-and-drop/style.css
  packages/@coorpacademy-components/src/atom/drag-and-drop/test/dragging.js
  packages/@coorpacademy-components/src/atom/drag-and-drop/test/fixtures/with-multiple.js
  packages/@coorpacademy-components/src/atom/image-upload/style.css
  packages/@coorpacademy-components/src/atom/input-file-draggable/index.js
  packages/@coorpacademy-components/src/atom/input-file-draggable/style.css
  packages/@coorpacademy-components/src/atom/input-file-draggable/test/fixtures/clean-modified.js
  packages/@coorpacademy-components/src/atom/input-file-draggable/test/fixtures/default.js
  packages/@coorpacademy-components/src/atom/input-file-draggable/test/fixtures/desktop-reset-description-multiple.js
  packages/@coorpacademy-components/src/atom/input-file-draggable/test/fixtures/desktop-reset-description-only-png.js
  packages/@coorpacademy-components/src/atom/input-file-draggable/test/fixtures/desktop-reset-description.js
  packages/@coorpacademy-components/src/atom/input-file-draggable/test/fixtures/desktop-reset-no-description.js
  packages/@coorpacademy-components/src/atom/input-file-draggable/test/fixtures/desktop.js
  packages/@coorpacademy-components/src/atom/input-file-draggable/test/fixtures/disabled.js
  packages/@coorpacademy-components/src/atom/input-file-draggable/test/fixtures/email.js
  packages/@coorpacademy-components/src/atom/input-file-draggable/test/fixtures/mobile.js
  packages/@coorpacademy-components/src/atom/input-file-draggable/test/fixtures/modified.js
  packages/@coorpacademy-components/src/atom/input-file-draggable/test/fixtures/multiple-files-uploaded.js
  packages/@coorpacademy-components/src/atom/input-file-draggable/test/fixtures/pdf.js
  packages/@coorpacademy-components/src/atom/input-file-draggable/test/index.js
  packages/@coorpacademy-components/src/molecule/brand-form-group/index.js
  packages/@coorpacademy-components/src/molecule/brand-form-group/test/fixtures/bulk-massive-import.js
  packages/@coorpacademy-components/src/molecule/brand-form-group/test/fixtures/images.js
  packages/@coorpacademy-components/src/molecule/cm-popin/index.js
  packages/@coorpacademy-components/src/molecule/cm-popin/style.css
  packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/list.js
  packages/@coorpacademy-components/src/molecule/cm-popin/types.ts
  packages/@coorpacademy-components/src/molecule/drag-and-drop-wrapper/index.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop-wrapper/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop-wrapper/test/fixtures/disabled.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop-wrapper/test/fixtures/pdf.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop-wrapper/test/fixtures/two-drag-and-drops.js
  packages/@coorpacademy-components/src/molecule/setup-slider/index.js
  packages/@coorpacademy-components/src/molecule/title-radio-wrapper/index.tsx
  packages/@coorpacademy-components/src/molecule/title-radio-wrapper/types.ts
  packages/@coorpacademy-components/src/organism/brand-form/test/fixtures/lms.js
  packages/@coorpacademy-components/src/organism/list-item/index.js
  packages/@coorpacademy-components/src/organism/list-item/style.css
  packages/@coorpacademy-components/src/organism/list-item/test/fixtures/file.js
  packages/@coorpacademy-components/src/organism/list-items/index.js
  packages/@coorpacademy-components/src/organism/list-items/style.css
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/files-list.js
  packages/@coorpacademy-components/src/organism/rewards-form/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/rewards-form/test/fixtures/one-reward.js
  packages/@coorpacademy-components/src/organism/setup-header/style.css
  packages/@coorpacademy-components/src/organism/wizard-contents/test/fixtures/bulk-massive-import.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/bulk-massive-import.js
  packages/@coorpacademy-components/src/util/proptypes.js
  packages/@coorpacademy-components/src/util/test/proptypes.js
Labels: pr: :lollipop: Enhancement, pr: :rocket: New feature

#2808 [massive-battle] modify TitleAndCheckBoxWrapper and SelectOpponents components
  packages/@coorpacademy-components/src/molecule/title-and-checkbox-wrapper/index.js
  packages/@coorpacademy-components/src/organism/select-opponents/index.tsx
  packages/@coorpacademy-components/src/organism/select-opponents/style.css
  packages/@coorpacademy-components/src/organism/select-opponents/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/select-opponents/types.ts
Labels: pr: :wrench: Refactoring

#2810 [massive-battle] modify TitleAndCheckBoxWrapper and SelectOpponents components
  packages/@coorpacademy-components/src/molecule/title-and-checkbox-wrapper/index.js
  packages/@coorpacademy-components/src/organism/select-opponents/index.tsx
  packages/@coorpacademy-components/src/organism/select-opponents/style.css
  packages/@coorpacademy-components/src/organism/select-opponents/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/select-opponents/types.ts
Labels: pr: :wrench: Refactoring

#2803 [R&D] Migrate components tests to testing-library
  packages/@coorpacademy-components/src/molecule/scope-tabs/test/on-click.js
  packages/@coorpacademy-components/src/molecule/scope-tabs/test/on-click.tsx
  packages/@coorpacademy-components/src/template/back-office/brand-list/test/change.tsx
  packages/@coorpacademy-components/src/template/back-office/dashboard-preview/test/on-select-dashboard.js
  packages/@coorpacademy-components/src/template/back-office/dashboard-preview/test/on-select-dashboard.tsx
  packages/@coorpacademy-components/src/template/back-office/layout/index.js
  packages/@coorpacademy-components/src/template/common/authors/test/show-more.js
  packages/@coorpacademy-components/src/template/common/authors/test/show-more.tsx
  packages/@coorpacademy-components/src/template/teams-dashboard/index.js
  packages/@coorpacademy-components/src/template/teams-dashboard/test/dashboard.js
  packages/@coorpacademy-components/src/template/teams-dashboard/test/dashboard.tsx
  packages/@coorpacademy-components/src/util/render-with-context.js
Labels: pr: :lollipop: Enhancement

#2811 Fix CMPopinCard style
  packages/@coorpacademy-components/src/atom/title/style.css
  packages/@coorpacademy-components/src/molecule/card/index.js
  packages/@coorpacademy-components/src/molecule/card/style.css
  packages/@coorpacademy-components/src/molecule/cm-popin/index.js
  packages/@coorpacademy-components/src/molecule/cm-popin/style.css
  packages/@coorpacademy-components/src/molecule/cm-popin/test/on-close.tsx
  packages/@coorpacademy-components/src/molecule/cm-popin/types.ts
  packages/@coorpacademy-components/src/template/common/dashboard/index.js
  packages/@coorpacademy-components/src/template/common/search-page/index.js
Labels: pr: :construction: Work In Progress

#2812 modify empty state component to handle also upload progression
  packages/@coorpacademy-components/src/molecule/bulk-infos/index.tsx
  packages/@coorpacademy-components/src/molecule/bulk-infos/style.css
  packages/@coorpacademy-components/src/molecule/bulk-infos/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/bulk-infos/test/fixtures/progress.js
  packages/@coorpacademy-components/src/molecule/bulk-infos/types.ts
  packages/@coorpacademy-components/src/molecule/empty-state-dashboard/index.tsx
  packages/@coorpacademy-components/src/molecule/empty-state-dashboard/style.css
  packages/@coorpacademy-components/src/molecule/empty-state-dashboard/types.ts
  packages/@coorpacademy-components/src/molecule/uploading-file-progress/index.tsx
  packages/@coorpacademy-components/src/molecule/uploading-file-progress/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/wizard-contents/index.js
  packages/@coorpacademy-components/src/organism/wizard-contents/style.css
  packages/@coorpacademy-components/src/organism/wizard-contents/test/fixtures/bulk-massive-import.js
  packages/@coorpacademy-components/src/organism/wizard-contents/test/fixtures/bulk-upload-progression.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/bulk-uploading-file-progress.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/bulk.js
Labels: enhancement
