Repository CoorpAcademy/components, pull requests merged in 2023-08, with the labels that each got.

#2772 Style of disabled card on hover
  packages/@coorpacademy-components/src/molecule/card/style.css
  packages/@coorpacademy-components/src/variables/colors.css
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/padlock.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/padlock.native.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/padlock.svg
Labels: pr: :construction: Work In Progress

#2780 [RGAA] Apply audit reviews: 11.9 - Dans chaque formulaire, l’intitulé de chaque bouton est-il pertinent (hors cas particuliers)?
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/template/activity/engine-stars.js
Labels: RGAA

#2783 fix picture background
  packages/@coorpacademy-components/src/atom/picture-background/style.css
Labels: RGAA

#2784 [massive-battle] add new icon file-lines in nova-icons
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-solid/files-basic/file-lines.js
  packages/@coorpacademy-nova-icons/src/components/nova-solid/files-basic/file-lines.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-solid.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-solid.iconjar/icons/file-lines.svg
Labels: pr: :rocket: New feature

#2779 [massive-battle] show uploaded file name in drag and drop components
  packages/@coorpacademy-components/src/atom/drag-and-drop/index.js
  packages/@coorpacademy-components/src/atom/drag-and-drop/style.css
  packages/@coorpacademy-components/src/atom/drag-and-drop/test/fixtures/with-xlsx.js
  packages/@coorpacademy-components/src/molecule/title-radio-wrapper/index.tsx
  packages/@coorpacademy-components/src/molecule/title-radio-wrapper/style.css
  packages/@coorpacademy-components/src/molecule/title-radio-wrapper/test/fixtures/upload-opponents-loading.ts
  packages/@coorpacademy-components/src/molecule/title-radio-wrapper/test/fixtures/upload-opponents.ts
  packages/@coorpacademy-components/src/molecule/title-radio-wrapper/test/fixtures/upload-validated-opponents.ts
  packages/@coorpacademy-components/src/organism/select-opponents/test/fixtures/default.ts
Labels: pr: :lollipop: Enhancement

#2788 Fix picture background with
  packages/@coorpacademy-components/src/atom/picture-background/style.css
Labels: RGAA

#2786 add isLoading props to display a loader
  packages/@coorpacademy-components/src/template/back-office/brand-list/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-list/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-list/test/fixtures/loading.js
Labels: enhancement

#2789 fix img object-fit
  packages/@coorpacademy-components/src/atom/picture-background/style.css
Labels: RGAA

#2794 add alt to img
  packages/@coorpacademy-components/src/atom/picture-background/index.js
  packages/@coorpacademy-components/src/atom/picture-background/test/fixtures/default.js
Labels: RGAA

#2793 Rgaa groupes
  packages/@coorpacademy-components/src/molecule/answer/index.js
  packages/@coorpacademy-components/src/molecule/answer/prop-types.ts
  packages/@coorpacademy-components/src/molecule/answer/test/fixtures/audio.ts
  packages/@coorpacademy-components/src/molecule/answer/test/fixtures/default.ts
  packages/@coorpacademy-components/src/molecule/answer/test/fixtures/drop-down.ts
  packages/@coorpacademy-components/src/molecule/answer/test/fixtures/qcm-arabic.ts
  packages/@coorpacademy-components/src/molecule/answer/test/fixtures/qcm-drag.ts
  packages/@coorpacademy-components/src/molecule/answer/test/fixtures/qcm-graphic.ts
  packages/@coorpacademy-components/src/molecule/answer/test/fixtures/qcm-short-audio.ts
  packages/@coorpacademy-components/src/molecule/answer/test/fixtures/qcm-short-video.ts
  packages/@coorpacademy-components/src/molecule/answer/test/fixtures/qcm-short.ts
  packages/@coorpacademy-components/src/molecule/answer/test/fixtures/qcm.ts
  packages/@coorpacademy-components/src/molecule/answer/test/fixtures/range.ts
  packages/@coorpacademy-components/src/molecule/answer/test/fixtures/template.ts
  packages/@coorpacademy-components/src/molecule/questions/qcm-drag/index.js
  packages/@coorpacademy-components/src/organism/review-slide/index.js
  packages/@coorpacademy-components/src/template/app-player/player/slides/index.js
Labels: RGAA

#2775 Sso page refacto enable to chose config
  packages/@coorpacademy-components/src/molecule/setup-slide/index.js
  packages/@coorpacademy-components/src/molecule/setup-slide/style.css
  packages/@coorpacademy-components/src/molecule/setup-slide/test/fixtures/alert-message.js
  packages/@coorpacademy-components/src/molecule/setup-slide/test/fixtures/checkbox.js
  packages/@coorpacademy-components/src/molecule/setup-slide/test/fixtures/cohort.js
  packages/@coorpacademy-components/src/molecule/setup-slide/test/fixtures/create-new-cohort.js
  packages/@coorpacademy-components/src/molecule/setup-slide/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/setup-slide/test/fixtures/split-form.js
  packages/@coorpacademy-components/src/molecule/setup-slide/test/fixtures/without-upload-image.js
  packages/@coorpacademy-components/src/molecule/setup-slider/index.js
  packages/@coorpacademy-components/src/molecule/setup-slider/style.css
  packages/@coorpacademy-components/src/molecule/setup-slider/test/fixtures/alert-message.js
  packages/@coorpacademy-components/src/molecule/setup-slider/test/fixtures/checkbox.js
  packages/@coorpacademy-components/src/molecule/setup-slider/test/fixtures/cohort.js
  packages/@coorpacademy-components/src/molecule/setup-slider/test/fixtures/create-new-cohort.js
  packages/@coorpacademy-components/src/molecule/setup-slider/test/fixtures/default-cohort.js
  packages/@coorpacademy-components/src/molecule/setup-slider/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/setup-slider/test/fixtures/split-form.js
  packages/@coorpacademy-components/src/molecule/setup-slider/test/fixtures/without-upload-image.js
  packages/@coorpacademy-components/src/organism/brand-form/index.js
  packages/@coorpacademy-components/src/organism/brand-form/test/fixtures/sso.js
Labels: pr: :lollipop: Enhancement

#2795 fix image types
  packages/@coorpacademy-components/src/atom/image-upload/index.js
  packages/@coorpacademy-components/src/atom/image-upload/test/fixtures/desktop.js
  packages/@coorpacademy-components/src/atom/image-upload/test/fixtures/pdf.js
  packages/@coorpacademy-components/src/atom/image-upload/test/index.js
  packages/@coorpacademy-components/src/util/proptypes.js
  packages/@coorpacademy-components/src/util/test/proptypes.js
Labels: pr: :bug: Bug Fix
