Repository CoorpAcademy/components, pull requests merged in 2023-03, with the labels that each got.

#2663 Fix select label
  packages/@coorpacademy-components/src/atom/select/index.js
  packages/@coorpacademy-components/src/atom/select/style.css
  packages/@coorpacademy-components/src/molecule/filters/test/fixtures/default.js
Labels: pr: :bug: Bug Fix

#2656 [RGAA] fix select style & remove account in moocHeader
  packages/@coorpacademy-components/src/atom/input-switch/style.css
  packages/@coorpacademy-components/src/atom/select/style.css
  packages/@coorpacademy-components/src/molecule/filters/filters-wapper.css
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/style.css
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/with-population.js
Labels: RGAA

#2679 Favorite (From Card) refactor to function component + coverage
  packages/@coorpacademy-components/src/molecule/card/favorite.js
  packages/@coorpacademy-components/src/molecule/card/test/fixtures/eligible-for-favorite-no-aria-label.js
  packages/@coorpacademy-components/src/molecule/card/test/fixtures/eligible-for-favorite-no-tooltip-message.js
Labels: pr: :wrench: Refactoring

#2671 modifiy image upload component props image type
  packages/@coorpacademy-components/src/atom/drag-and-drop/index.js
  packages/@coorpacademy-components/src/atom/drag-and-drop/style.css
  packages/@coorpacademy-components/src/atom/drag-and-drop/test/fixtures/with-pdf.js
  packages/@coorpacademy-components/src/atom/image-upload/index.js
  packages/@coorpacademy-components/src/atom/image-upload/test/fixtures/desktop-reset-description-multiple.js
  packages/@coorpacademy-components/src/atom/image-upload/test/fixtures/desktop-reset-description-only-png.js
  packages/@coorpacademy-components/src/atom/image-upload/test/fixtures/pdf.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop-wrapper/style.css
  packages/@coorpacademy-components/src/organism/list-item/index.js
  packages/@coorpacademy-components/src/organism/list-items/index.js
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/published-certification.js
  packages/@coorpacademy-components/src/organism/rewards-form/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/rewards-form/test/fixtures/one-reward.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/list-items-certification-published.js
  packages/@coorpacademy-components/src/util/button-icons.js
  packages/@coorpacademy-components/src/util/proptypes.js
  packages/@coorpacademy-components/src/util/test/proptypes.js
Labels: enhancement, DO NOT MERGE

#2675 Create a Boosted revision player :orange_book:
  packages/@coorpacademy-progression-engine/src/config/review.js
Labels: pr: :lollipop: Enhancement

#2689 fix import style
  packages/@coorpacademy-components/src/molecule/setup-slider/index.js
Labels: pr: :bug: Bug Fix

#2690 fix design regression
  packages/@coorpacademy-components/src/atom/drag-and-drop/index.js
  packages/@coorpacademy-components/src/atom/drag-and-drop/style.css
  packages/@coorpacademy-components/src/atom/image-upload/index.js
  packages/@coorpacademy-components/src/molecule/brand-form-group/style.css
  packages/@coorpacademy-components/src/molecule/drag-and-drop-wrapper/style.css
  packages/@coorpacademy-components/src/molecule/drag-and-drop-wrapper/test/fixtures/pdf.js
Labels: pr: :bug: Bug Fix

#2691 Massive import fix
  packages/@coorpacademy-components/src/atom/image-upload/index.js
  packages/@coorpacademy-components/src/atom/image-upload/style.css
  packages/@coorpacademy-components/src/molecule/brand-form-group/index.js
  packages/@coorpacademy-components/src/molecule/brand-form-group/style.css
  packages/@coorpacademy-components/src/molecule/brand-form-group/test/fixtures/bulk-massive-import.js
  packages/@coorpacademy-components/src/organism/brand-form/index.js
  packages/@coorpacademy-components/src/organism/brand-form/style.css
  packages/@coorpacademy-components/src/organism/wizard-contents/index.js
  packages/@coorpacademy-components/src/organism/wizard-contents/test/fixtures/bulk-external-content.js
  packages/@coorpacademy-components/src/organism/wizard-contents/test/fixtures/bulk-massive-import.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/bulk-massive-import.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement, pr: :rocket: New feature

#2694 [RGAA] add role group to settings menu
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/default.js
Labels: RGAA

#2678 create Actionnable expandible table
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/atom/button-link-icon-only/style.css
  packages/@coorpacademy-components/src/atom/button-link/index.tsx
  packages/@coorpacademy-components/src/atom/button-link/style.css
  packages/@coorpacademy-components/src/atom/button-link/test/fixtures/button-dangerous-no-icon.ts
  packages/@coorpacademy-components/src/atom/button-link/test/fixtures/button-primary-icon-left.ts
  packages/@coorpacademy-components/src/atom/button-link/test/fixtures/button-primary-no-icon.ts
  packages/@coorpacademy-components/src/atom/button-link/test/fixtures/button-secondary-no-icon-disabled.ts
  packages/@coorpacademy-components/src/atom/button-link/test/fixtures/button-tertiary-icon-left.ts
  packages/@coorpacademy-components/src/atom/button-link/test/fixtures/link-primary-disabled-icon-right.ts
  packages/@coorpacademy-components/src/atom/button-link/test/fixtures/link-secondary-icon-right.ts
  packages/@coorpacademy-components/src/atom/button-link/test/fixtures/link-tertiary-no-icon-no-aria-label.ts
  packages/@coorpacademy-components/src/atom/button-link/test/fixtures/link-tertiary-no-icon.ts
  packages/@coorpacademy-components/src/atom/button-link/test/fixtures/link-text-icon-right-target-blank.ts
  packages/@coorpacademy-components/src/atom/button-link/test/fixtures/link-text-no-icon-download.ts
  packages/@coorpacademy-components/src/atom/button-link/types.ts
  packages/@coorpacademy-components/src/atom/button-menu/index.tsx
  packages/@coorpacademy-components/src/atom/button-menu/test/fixtures/default.ts
  packages/@coorpacademy-components/src/atom/button-menu/test/fixtures/multiple-buttons.ts
  packages/@coorpacademy-components/src/atom/button-menu/types.ts
  packages/@coorpacademy-components/src/atom/link/index.js
  packages/@coorpacademy-components/src/atom/status-item/style.css
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/index.tsx
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/style.css
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/test/fixtures/default.ts
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/test/fixtures/multiple-buttons.ts
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/types.ts
  packages/@coorpacademy-components/src/molecule/empty-state-dashboard/index.tsx
  packages/@coorpacademy-components/src/molecule/empty-state-dashboard/types.ts
  packages/@coorpacademy-components/src/molecule/expandible-actionable-table/index.tsx
  packages/@coorpacademy-components/src/molecule/expandible-actionable-table/style.css
  packages/@coorpacademy-components/src/molecule/expandible-actionable-table/test/expandible-actionable-table.js
  packages/@coorpacademy-components/src/molecule/expandible-actionable-table/test/fixtures/dashboard-pending.ts
  packages/@coorpacademy-components/src/molecule/expandible-actionable-table/test/fixtures/dashboard-saved.ts
  packages/@coorpacademy-components/src/molecule/expandible-actionable-table/test/fixtures/empty.ts
  packages/@coorpacademy-components/src/molecule/expandible-actionable-table/test/fixtures/inspect-all-valid.ts
  packages/@coorpacademy-components/src/molecule/expandible-actionable-table/test/fixtures/inspect-valid-invalid.ts
  packages/@coorpacademy-components/src/molecule/expandible-actionable-table/types.ts
  packages/@coorpacademy-components/src/molecule/uploading-file-progress/index.tsx
  packages/@coorpacademy-components/src/molecule/uploading-file-progress/test/fixtures/default.ts
  packages/@coorpacademy-components/src/molecule/uploading-file-progress/types.ts
  packages/@coorpacademy-components/src/organism/list-items/index.js
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/archived.js
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/bulk-imports-saved.js
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/draft.js
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/published-certification.js
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/published.js
  packages/@coorpacademy-components/src/organism/wizard-contents/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/bulk-dashboard-imports-pending.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/bulk-dashboard-imports-saved.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/bulk-inspect.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/list-items-certification-published.js
Labels: pr: :rocket: New feature

#2695 (Fix) - fix avatar color in battle request
  packages/@coorpacademy-components/src/atom/avatar/style.css
  packages/@coorpacademy-components/src/atom/difficulty-level/style.css
Labels: RGAA

#2699 Fixes input that should use display: none; instead of opacity
  packages/@coorpacademy-components/src/molecule/questions/qcm-graphic/style.css
Labels: pr: :bug: Bug Fix

#2700 fix button-link regression
  packages/@coorpacademy-components/src/atom/button-link/index.tsx
  packages/@coorpacademy-components/src/atom/button-link/style.css
  packages/@coorpacademy-components/src/atom/button-link/types.ts
  packages/@coorpacademy-components/src/molecule/expandible-actionable-table/test/fixtures/dashboard-pending.ts
Labels: bug
