Repository CoorpAcademy/components, pull requests merged in 2023-02, with the labels that each got.

#2620 Activity tooltip: 12.11 - Dans chaque page web, les contenus additionnels apparaissant au survol, à la prise de focus ou à l'activation d'un composant d'interface sont-ils, si nécessaire, atteignables au clavier
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/package.json
  packages/@coorpacademy-components/src/atom/review-presentation/index.js
  packages/@coorpacademy-components/src/atom/review-presentation/style.css
  packages/@coorpacademy-components/src/atom/review-presentation/test/on-key-down.js
  packages/@coorpacademy-components/src/atom/review-presentation/test/on-mouse-leave.js
  packages/@coorpacademy-components/src/atom/tooltip/index.js
  packages/@coorpacademy-components/src/atom/tooltip/style.css
  packages/@coorpacademy-components/src/atom/tooltip/test/fixtures/default.ts
  packages/@coorpacademy-components/src/atom/tooltip/test/fixtures/react-tooltip-not-visible.ts
  packages/@coorpacademy-components/src/atom/tooltip/test/fixtures/react-tooltip.ts
  packages/@coorpacademy-components/src/template/activity/engine-stars.css
  packages/@coorpacademy-components/src/template/activity/engine-stars.js
  packages/@coorpacademy-components/src/template/activity/index.js
  packages/@coorpacademy-components/src/template/activity/progression-item.js
  packages/@coorpacademy-components/src/template/activity/stars-summary.js
  packages/@coorpacademy-components/src/template/activity/test/handles-test.js
  packages/@coorpacademy-components/src/template/activity/test/stars-summary-test.js
  packages/@coorpacademy-components/src/template/activity/test/tooltip-keydown.js
  yarn.lock
Labels: pr: :lollipop: Enhancement, pr: :rocket: New feature, pr: :wrench: Refactoring, pr: Upgrades :outbox_tray:, RGAA

#2626 [review] fix video's layout on the player
  packages/@coorpacademy-components/src/molecule/answer/style.css
Labels: pr: :bug: Bug Fix

#2615 [RGAA]add checkbox to player answers
  packages/@coorpacademy-components/src/molecule/questions/qcm-drag/index.js
  packages/@coorpacademy-components/src/molecule/questions/qcm-drag/style.css
  packages/@coorpacademy-components/src/molecule/questions/qcm-graphic/index.js
  packages/@coorpacademy-components/src/molecule/questions/qcm-graphic/style.css
Labels: RGAA

#2623 add uploading file progress component
  packages/@coorpacademy-components/src/molecule/uploading-file-progress/index.tsx
  packages/@coorpacademy-components/src/molecule/uploading-file-progress/style.css
  packages/@coorpacademy-components/src/molecule/uploading-file-progress/test/fixtures/default.ts
  packages/@coorpacademy-components/src/molecule/uploading-file-progress/types.ts
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/bulk-uploading-file-progress.js
Labels: pr: :rocket: New feature

#2622 [RGAA] Add svg color to css files and properties
  packages/@coorpacademy-components/src/atom/avatar/index.js
  packages/@coorpacademy-components/src/atom/avatar/style.css
  packages/@coorpacademy-components/src/atom/card-image-preview/index.js
  packages/@coorpacademy-components/src/atom/difficulty-level/index.js
  packages/@coorpacademy-components/src/atom/difficulty-level/style.css
  packages/@coorpacademy-components/src/atom/input-html/index.js
  packages/@coorpacademy-components/src/atom/life/index.js
  packages/@coorpacademy-components/src/atom/resource-miniature/index.js
  packages/@coorpacademy-components/src/molecule/audio/index.js
  packages/@coorpacademy-components/src/molecule/battle-request/index.js
  packages/@coorpacademy-components/src/molecule/brand-download-box/index.js
  packages/@coorpacademy-components/src/molecule/brand-upload-box/index.js
  packages/@coorpacademy-components/src/molecule/card-content/index.js
  packages/@coorpacademy-components/src/molecule/card-content/style.css
  packages/@coorpacademy-components/src/molecule/card/favorite.js
  packages/@coorpacademy-components/src/molecule/card/index.js
  packages/@coorpacademy-components/src/molecule/card/notification.js
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/index.js
  packages/@coorpacademy-components/src/molecule/discipline-partners/index.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/overlay.js
  packages/@coorpacademy-components/src/molecule/drag-and-drop/upload-report.js
  packages/@coorpacademy-components/src/molecule/filters/index.js
  packages/@coorpacademy-components/src/molecule/pdf/index.js
  packages/@coorpacademy-components/src/molecule/resource-player/index.js
  packages/@coorpacademy-components/src/molecule/search-form/index.js
  packages/@coorpacademy-components/src/molecule/select-multiple/index.js
  packages/@coorpacademy-components/src/molecule/setup-section/index.js
  packages/@coorpacademy-components/src/molecule/table/index.js
  packages/@coorpacademy-components/src/molecule/titled-checkbox/index.js
  packages/@coorpacademy-components/src/molecule/titled-checkbox/style.css
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/part/index.js
  packages/@coorpacademy-components/src/organism/accordion/coorp-manager/part/style.css
  packages/@coorpacademy-components/src/organism/accordion/part/index.js
  packages/@coorpacademy-components/src/organism/accordion/part/style.css
  packages/@coorpacademy-components/src/organism/brand-form/index.js
  packages/@coorpacademy-components/src/organism/get-the-app/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/organism/slider/index.js
  packages/@coorpacademy-components/src/template/activity/progression-item.js
  packages/@coorpacademy-components/src/template/activity/stars-summary.js
  packages/@coorpacademy-components/src/template/app-player/player/slides/footer/index.js
  packages/@coorpacademy-components/src/template/app-player/player/slides/header/learner.css
  packages/@coorpacademy-components/src/template/app-player/player/slides/header/learner.js
  packages/@coorpacademy-components/src/template/app-player/player/slides/header/microlearning.css
  packages/@coorpacademy-components/src/template/app-player/player/slides/header/microlearning.js
  packages/@coorpacademy-components/src/template/app-player/popin-correction/index.js
  packages/@coorpacademy-components/src/template/app-player/popin-correction/style.css
  packages/@coorpacademy-components/src/template/app-player/popin-end/summary.js
  packages/@coorpacademy-components/src/template/app-player/popin-header/index.js
  packages/@coorpacademy-components/src/template/app-player/popin-header/style.css
Labels: RGAA

#2613 [RGAA] Add tooltip information text on logo mooc header
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/style.css
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/on-key.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/on-mouse.js
  packages/@coorpacademy-nova-icons/README.md
  packages/@coorpacademy-nova-icons/icons.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/places-home-24.js
  packages/@coorpacademy-nova-icons/src/components/nova-composition/coorpacademy/places-home-24.native.js
  packages/@coorpacademy-nova-icons/src/index.js
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/META
  packages/@coorpacademy-nova-icons/third-party/nova-composition.iconjar/icons/places-home-24.svg
  packages/@coorpacademy-nova-icons/third-party/nova-solid.iconjar/icons/places-home-24.svg
Labels: RGAA

#2632 Fix review dashboard color
  packages/@coorpacademy-components/src/atom/review-presentation/style.css
Labels: pr: :bug: Bug Fix

#2625 [RGAA] fix translation in answer component
  packages/@coorpacademy-components/src/atom/provider/web-context.tsx
  packages/@coorpacademy-components/src/atom/review-header-step-item/index.tsx
  packages/@coorpacademy-components/src/molecule/answer/index.js
  packages/@coorpacademy-components/src/molecule/answer/test/drop-down-no-aria-label.js
  packages/@coorpacademy-components/src/organism/review-header/index.js
  packages/@coorpacademy-components/src/organism/review-header/test/review-header.js
  packages/@coorpacademy-components/src/template/activity/engine-stars.js
  packages/@coorpacademy-components/src/template/activity/index.js
  packages/@coorpacademy-components/src/template/activity/stars-summary.js
  packages/@coorpacademy-components/src/template/activity/test/handles-test.js
  packages/@coorpacademy-components/src/template/activity/test/stars-summary-test.js
  packages/@coorpacademy-components/src/util/render-with-context.js
  packages/@coorpacademy-components/src/util/test/render-with-context.js
Labels: pr: :bug: Bug Fix, RGAA

#2606 [RGAA] etiquette des champs de formulaires critères: 11.1 - 11.2
  packages/@coorpacademy-components/src/atom/input-search/index.js
  packages/@coorpacademy-components/src/atom/input-switch/index.js
  packages/@coorpacademy-components/src/atom/input-switch/test/fixtures/no-title-invisible-label.js
  packages/@coorpacademy-components/src/atom/input-switch/test/fixtures/no-title-visible-label.js
  packages/@coorpacademy-components/src/atom/select/index.js
  packages/@coorpacademy-components/src/atom/select/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/filters/filters-wrapper.js
  packages/@coorpacademy-components/src/molecule/filters/index.js
  packages/@coorpacademy-components/src/molecule/filters/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/template/activity/index.js
  packages/@coorpacademy-components/src/template/activity/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/common/search-page/index.js
  packages/@coorpacademy-components/src/template/common/search-page/test/fixtures/default.js
Labels: RGAA

#2640 [RGAA]add status roles
  packages/@coorpacademy-components/src/molecule/card-content/index.js
  packages/@coorpacademy-components/src/molecule/forum/forum-post/index.js
  packages/@coorpacademy-components/src/molecule/review-card-congrats/index.js
  packages/@coorpacademy-components/src/molecule/review-correction-popin/index.js
  packages/@coorpacademy-components/src/template/app-player/popin-header/index.js
Labels: RGAA

#2644 fix cookies popin
  packages/@coorpacademy-components/src/atom/input-switch/index.js
Labels: RGAA

#2637 [RGAA] Battle Opponent Atom + Tooltip: 12.11
  packages/@coorpacademy-components/package.json
  packages/@coorpacademy-components/src/atom/battle-opponent/index.tsx
  packages/@coorpacademy-components/src/atom/battle-opponent/prop-types.ts
  packages/@coorpacademy-components/src/atom/battle-opponent/style.css
  packages/@coorpacademy-components/src/atom/battle-opponent/test/already-engaged-opponent-click.tsx
  packages/@coorpacademy-components/src/atom/battle-opponent/test/available-opponent-click copy.tsx
  packages/@coorpacademy-components/src/atom/battle-opponent/test/fixtures/available-opponent.ts
  packages/@coorpacademy-components/src/atom/battle-opponent/test/fixtures/opponent-already-engaged.ts
  packages/@coorpacademy-components/src/atom/battle-opponent/test/fixtures/random-opponent.ts
  packages/@coorpacademy-components/src/atom/tooltip/index.js
  packages/@coorpacademy-components/src/atom/tooltip/style.css
  packages/@coorpacademy-components/src/atom/tooltip/test/fixtures/small-font-big-icon.ts
  packages/@coorpacademy-components/src/globals.d.ts
  packages/@coorpacademy-components/src/molecule/battle-opponent-list/index.tsx
  packages/@coorpacademy-components/src/molecule/battle-opponent-list/prop-types.ts
  packages/@coorpacademy-components/src/molecule/battle-opponent-list/style.css
  packages/@coorpacademy-components/src/molecule/battle-opponent-list/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/user-preferences/index.js
  yarn.lock
Labels: pr: :rocket: New feature, RGAA

#2631 Adapt header review step item to support bulk import design
  packages/@coorpacademy-components/locales/bs/global.json
  packages/@coorpacademy-components/locales/cs/global.json
  packages/@coorpacademy-components/locales/de/global.json
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/locales/es/global.json
  packages/@coorpacademy-components/locales/et/global.json
  packages/@coorpacademy-components/locales/fr/global.json
  packages/@coorpacademy-components/locales/hr/global.json
  packages/@coorpacademy-components/locales/hu/global.json
  packages/@coorpacademy-components/locales/hy/global.json
  packages/@coorpacademy-components/locales/it/global.json
  packages/@coorpacademy-components/locales/ja/global.json
  packages/@coorpacademy-components/locales/ko/global.json
  packages/@coorpacademy-components/locales/nl/global.json
  packages/@coorpacademy-components/locales/pl/global.json
  packages/@coorpacademy-components/locales/pt/global.json
  packages/@coorpacademy-components/locales/ro/global.json
  packages/@coorpacademy-components/locales/ru/global.json
  packages/@coorpacademy-components/locales/sk/global.json
  packages/@coorpacademy-components/locales/th/global.json
  packages/@coorpacademy-components/locales/tl/global.json
  packages/@coorpacademy-components/locales/tr/global.json
  packages/@coorpacademy-components/locales/uk/global.json
  packages/@coorpacademy-components/locales/vi/global.json
  packages/@coorpacademy-components/locales/zh/global.json
  packages/@coorpacademy-components/locales/zh_TW/global.json
  packages/@coorpacademy-components/src/atom/review-header-step-item/index.tsx
  packages/@coorpacademy-components/src/atom/review-header-step-item/types.ts
  packages/@coorpacademy-components/src/atom/status-item/index.native.tsx
  packages/@coorpacademy-components/src/atom/status-item/index.tsx
  packages/@coorpacademy-components/src/atom/status-item/style.css
  packages/@coorpacademy-components/src/atom/status-item/test/fixtures/bulk-import-errors-number.ts
  packages/@coorpacademy-components/src/atom/status-item/test/fixtures/bulk-import-invalid.ts
  packages/@coorpacademy-components/src/atom/status-item/test/fixtures/bulk-import-valid.ts
  packages/@coorpacademy-components/src/atom/status-item/test/fixtures/current.ts
  packages/@coorpacademy-components/src/atom/status-item/test/fixtures/default.ts
  packages/@coorpacademy-components/src/atom/status-item/test/fixtures/right.ts
  packages/@coorpacademy-components/src/atom/status-item/test/fixtures/wrong.ts
  packages/@coorpacademy-components/src/atom/status-item/types.ts
  packages/@coorpacademy-components/src/molecule/review-header-steps/index.js
  packages/@coorpacademy-components/src/molecule/review-header-steps/prop-types.ts
  packages/@coorpacademy-components/src/organism/review-header/index.native.tsx
  packages/@coorpacademy-components/src/organism/review-header/types.ts
  packages/@coorpacademy-components/src/variables/colors.css
Labels: enhancement, RGAA

#2639 [RGAA]change links style in footer and header
  packages/@coorpacademy-components/src/organism/mooc-footer/style.css
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/style.css
  packages/@coorpacademy-components/src/organism/mooc-header/test/on-mouse.js
Labels: RGAA

#2649 [RGAA] set color attribute into style
  packages/@coorpacademy-components/src/template/activity/engine-stars.js
Labels: RGAA

#2651 New learner engine with doubled stars
  packages/@coorpacademy-progression-engine/src/config/learner.js
Labels: pr: :lollipop: Enhancement, pr: :wrench: Refactoring

#2655 [RGAA]add progressbar role
  packages/@coorpacademy-components/src/template/activity/progression-item.js
Labels: RGAA

#2659 fix question slider style for mobile
  packages/@coorpacademy-components/src/molecule/answer/index.js
  packages/@coorpacademy-components/src/molecule/answer/style.css
Labels: pr: :bug: Bug Fix

#2660 [RGAA]add aria label to buttons
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/atom/button/index.js
  packages/@coorpacademy-components/src/molecule/forum/forum-comment/index.js
  packages/@coorpacademy-components/src/molecule/skill-card/index.js
  packages/@coorpacademy-components/src/molecule/skill-card/test/skill-card.js
  packages/@coorpacademy-components/src/organism/review-header/index.js
  packages/@coorpacademy-components/src/organism/review-header/test/fixtures/all-questions-ok.ts
  packages/@coorpacademy-components/src/organism/review-header/test/review-header.js
  packages/@coorpacademy-components/src/organism/review-slide/index.js
Labels: RGAA

#2662 [RGAA]fix links bug
  packages/@coorpacademy-components/src/organism/mooc-header/style.css
Labels: RGAA

#2653 [review] fix select in player mobile
  packages/@coorpacademy-components/src/molecule/questions/mobile/switch/test/on-item-input-change.test.tsx
  packages/@coorpacademy-components/src/molecule/questions/mobile/template/index.native.tsx
Labels: pr: :bug: Bug Fix
