Repository CoorpAcademy/components, pull requests merged in 2023-01, with the labels that each got.

#2552 Add dropdown icon arialabel +trad
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/atom/provider/index.js
  packages/@coorpacademy-components/src/atom/select/index.js
  packages/@coorpacademy-components/src/atom/select/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/answer/index.js
  packages/@coorpacademy-components/src/molecule/answer/test/drop-down-aria-label-translation.js
  packages/@coorpacademy-components/src/molecule/questions/drop-down/index.js
  packages/@coorpacademy-components/src/molecule/questions/drop-down/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/template/app-player/player/slides/index.js
  packages/@coorpacademy-components/src/template/app-review/player/test/review-player.js
  packages/@coorpacademy-components/src/template/app-review/template-context.tsx
  packages/@coorpacademy-components/src/template/app-review/test/fixtures/player.ts
  packages/@coorpacademy-components/src/test/helpers/mock-mobile-context.ts
  packages/@coorpacademy-components/src/test/helpers/render-component.js
  packages/@coorpacademy-components/src/util/render-with-context.js
  packages/@coorpacademy-components/src/util/test/render-with-context.js
Labels: pr: :lollipop: Enhancement, pr: :wrench: Refactoring, pr: Wording :bookmark_tabs:

#2555 [RGAA] activities & myAccount : Alternative textuelle pour les <svg> porteuses d'informations
  packages/@coorpacademy-components/src/organism/user-preferences/index.js
  packages/@coorpacademy-components/src/organism/user-preferences/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/activity/index.js
  packages/@coorpacademy-components/src/template/activity/progression-item.js
  packages/@coorpacademy-components/src/template/activity/test/fixtures/default.js
Labels: RGAA

#2558 Lottie wrapper automatic aria props
  packages/@coorpacademy-app-review/locales/en/review.json
  packages/@coorpacademy-app-review/src/views/slides/index.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
  packages/@coorpacademy-components/src/atom/lottie-wrapper/index.js
  packages/@coorpacademy-components/src/atom/lottie-wrapper/prop-types.ts
  packages/@coorpacademy-components/src/atom/lottie-wrapper/test/fixtures/rank.js
  packages/@coorpacademy-components/src/organism/review-congrats/index.js
  packages/@coorpacademy-components/tsconfig.json
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement, pr: Wording :bookmark_tabs:

#2550 [RGAA] Add information aria label review item dashboard component
  packages/@coorpacademy-components/src/atom/review-presentation/index.js
  packages/@coorpacademy-components/src/atom/review-presentation/prop-types.ts
  packages/@coorpacademy-components/src/atom/review-presentation/test/fixtures/default.ts
Labels: RGAA

#2561 [R&D] Remove Lottie ie11 backup
  packages/@coorpacademy-app-review/src/views/slides/index.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
  packages/@coorpacademy-components/package.json
  packages/@coorpacademy-components/src/atom/lottie-wrapper/index.js
  packages/@coorpacademy-components/src/atom/lottie-wrapper/prop-types.ts
  packages/@coorpacademy-components/src/atom/lottie-wrapper/style.css
  packages/@coorpacademy-components/src/atom/lottie-wrapper/test/fixtures/confetti.js
  packages/@coorpacademy-components/src/atom/lottie-wrapper/test/fixtures/default.js
  packages/@coorpacademy-components/src/atom/lottie-wrapper/test/fixtures/rank.js
  packages/@coorpacademy-components/src/atom/lottie-wrapper/test/lottie.js
  packages/@coorpacademy-components/src/template/app-player/popin-end/summary.js
  yarn.lock
Labels: pr: :wrench: Refactoring

#2569 [review] fix bug popin to close player
  packages/@coorpacademy-app-review/src/views/slides/index.ts
  packages/@coorpacademy-app-review/src/views/slides/test/header.on-click.test.ts
Labels: pr: :bug: Bug Fix

#2565 [RGAA] Remove ReviewBackground (rotated coloured question marks + colors) from sequential navigation
  packages/@coorpacademy-components/src/atom/review-background/index.js
Labels: pr: :lollipop: Enhancement, RGAA

#2570 [mobile] add a button in the header to display popin
  packages/@coorpacademy-app-review/src/views/slides/index.ts
  packages/@coorpacademy-components/src/organism/review-header/index.native.tsx
  packages/@coorpacademy-components/src/organism/review-header/test/on-press.test.tsx
Labels: pr: :rocket: New feature

#2572 [review] delete tooltip next to the title in dashboard review
  packages/@coorpacademy-components/src/template/app-review/skills/index.js
  packages/@coorpacademy-components/src/template/app-review/skills/style.css
Labels: pr: :bug: Bug Fix

#2571 [Bulk Content Creation] Updating menu's width
  packages/@coorpacademy-components/src/template/back-office/brand-update/style.css
Labels: pr: :lollipop: Enhancement

#2575 [RGAA]add aria label to burgerIcon
  packages/@coorpacademy-components/src/organism/mooc-header/index.js
  packages/@coorpacademy-components/src/organism/mooc-header/test/fixtures/default.js
Labels: RGAA

#2583 [RGAA] add aria label and area description in review header step item
  packages/@coorpacademy-components/locales/en/global.json
Labels: RGAA

#2559 [RGAA] rendre le messages de statut correctement restitués par les technologies d’assistance
  packages/@coorpacademy-components/src/molecule/add-to-my-list/index.js
  packages/@coorpacademy-components/src/molecule/card/notification.js
  packages/@coorpacademy-components/src/molecule/forum/forum-post/index.js
  packages/@coorpacademy-components/src/molecule/share/index.js
  packages/@coorpacademy-components/src/template/common/search-page/index.js
Labels: RGAA

#2585 Configuration for the transifex-github integration
  .tx/transifex.yml
Labels: pr: Wording :bookmark_tabs:

#2586 Tweak CI travis to ignore trad commit
  .travis.yml
Labels: pr: :lollipop: Enhancement

#2562 [RGAA] Information icon reviewable skill keyboard events
  packages/@coorpacademy-components/src/atom/review-presentation/index.js
  packages/@coorpacademy-components/src/atom/review-presentation/prop-types.ts
  packages/@coorpacademy-components/src/atom/review-presentation/style.css
  packages/@coorpacademy-components/src/atom/review-presentation/test/fixtures/default.ts
  packages/@coorpacademy-components/src/atom/review-presentation/test/on-key-down.js
  packages/@coorpacademy-components/src/atom/review-presentation/test/on-mouse-leave.js
Labels: RGAA

#2593 [RGAA] add missing closeToolTipInformationAriaLabel to label props & update fixtures due to latest changes
  packages/@coorpacademy-components/src/atom/review-presentation/index.js
  packages/@coorpacademy-components/src/atom/review-presentation/test/fixtures/default.ts
Labels: pr: :bug: Bug Fix, RGAA

#2600 [review] add background image for mobile
  packages/@coorpacademy-app-review/src/index.tsx
  packages/@coorpacademy-app-review/src/types/common.ts
  packages/@coorpacademy-app-review/src/views/slides/index.ts
  packages/@coorpacademy-app-review/src/views/slides/test/index.test.ts
  packages/@coorpacademy-components/src/atom/review-background/prop-types.js
  packages/@coorpacademy-components/src/atom/review-background/style.css
  packages/@coorpacademy-components/src/atom/review-background/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/app-review/player/background-review.css
  packages/@coorpacademy-components/src/template/app-review/player/background-review.js
  packages/@coorpacademy-components/src/template/app-review/player/index.js
  packages/@coorpacademy-components/src/template/app-review/player/index.native.tsx
  packages/@coorpacademy-components/src/template/app-review/player/prop-types.ts
  packages/@coorpacademy-components/src/template/app-review/player/test/fixtures/all-ok.ts
  packages/@coorpacademy-components/src/template/app-review/player/test/fixtures/end-review.ts
  packages/@coorpacademy-components/src/template/app-review/player/test/fixtures/first-right.ts
  packages/@coorpacademy-components/src/template/app-review/player/test/fixtures/initial-state.ts
  packages/@coorpacademy-components/src/template/app-review/player/test/fixtures/loading.ts
  packages/@coorpacademy-components/src/template/app-review/player/test/fixtures/on-quit.ts
  packages/@coorpacademy-components/src/template/app-review/player/test/fixtures/one-fail.ts
  packages/@coorpacademy-components/src/template/app-review/player/test/fixtures/restack-with-videos.ts
  packages/@coorpacademy-components/src/template/app-review/player/test/fixtures/restack.ts
  packages/@coorpacademy-components/src/template/app-review/player/test/fixtures/second-failed-question.ts
  packages/@coorpacademy-components/src/template/app-review/player/test/fixtures/slide-with-video-loading.ts
  packages/@coorpacademy-components/src/template/app-review/player/test/fixtures/unstack.ts
Labels: pr: :rocket: New feature

#2589 [RGAA] Icons on select must remain decorative
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/atom/select/index.js
  packages/@coorpacademy-components/src/atom/select/test/fixtures/no-options.js
  packages/@coorpacademy-components/src/atom/select/test/select.js
  packages/@coorpacademy-components/src/molecule/answer/index.js
  packages/@coorpacademy-components/src/molecule/answer/test/drop-down-no-aria-label.js
Labels: pr: :lollipop: Enhancement

#2598 [RGAA] Activity (tooltip): Progression && StarsSummary from class to functional components
  packages/@coorpacademy-components/src/template/activity/index.js
  packages/@coorpacademy-components/src/template/activity/stars-summary.js
  packages/@coorpacademy-components/src/template/activity/test/stars-summary-test.js
Labels: pr: :lollipop: Enhancement, pr: :wrench: Refactoring, RGAA

#2588 create component + integrate in brand update template
  packages/@coorpacademy-components/src/molecule/empty-state-dashboard/index.tsx
  packages/@coorpacademy-components/src/molecule/empty-state-dashboard/style.css
  packages/@coorpacademy-components/src/molecule/empty-state-dashboard/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/empty-state-dashboard/types.ts
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/bulk.js
  packages/@coorpacademy-components/src/util/button-icons.js
Labels: pr: :rocket: New feature, pr: :construction: Work In Progress

#2607 [TMA] modify select component
  packages/@coorpacademy-components/src/atom/select/index.js
  packages/@coorpacademy-components/src/atom/select/test/fixtures/group-options.js
  packages/@coorpacademy-components/src/molecule/filters/test/fixtures/default.js
Labels: pr: :lollipop: Enhancement

#2568 [RGAA] regrouper les champs de meme nature
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/molecule/answer/index.js
  packages/@coorpacademy-components/src/molecule/filters/filters-wrapper.js
  packages/@coorpacademy-components/src/molecule/filters/index.js
  packages/@coorpacademy-components/src/molecule/filters/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/questions/drop-down/index.js
  packages/@coorpacademy-components/src/molecule/questions/qcm-drag/index.js
  packages/@coorpacademy-components/src/molecule/questions/qcm-drag/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/questions/qcm-graphic/index.js
  packages/@coorpacademy-components/src/molecule/questions/qcm-graphic/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/questions/qcm/index.js
  packages/@coorpacademy-components/src/molecule/questions/qcm/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/questions/question-range/index.js
  packages/@coorpacademy-components/src/molecule/questions/question-range/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/questions/template/index.js
  packages/@coorpacademy-components/src/molecule/questions/template/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/user-preferences/index.js
  packages/@coorpacademy-components/src/organism/user-preferences/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/common/search-page/index.js
  packages/@coorpacademy-components/src/template/common/search-page/test/fixtures/default.js
Labels: RGAA

#2612 [RGAA]add label to discussion page
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/molecule/forum/forum-comment/index.js
Labels: RGAA

#2610 [RGAA]add labels to myAccount alerts
  packages/@coorpacademy-components/src/atom/input-switch/index.js
Labels: RGAA

#2616 [TMA] fix select group options
  packages/@coorpacademy-components/src/atom/select/index.js
  packages/@coorpacademy-components/src/atom/select/test/fixtures/group-options.js
Labels: pr: :bug: Bug Fix
