Repository CoorpAcademy/components, pull requests merged in 2024-10, with the labels that each got.

#2882 [components] Fix design, unifying color & button usage on Coorp Manager
  packages/@coorpacademy-components/src/atom/button-link/index.tsx
  packages/@coorpacademy-components/src/atom/button-link/types.ts
  packages/@coorpacademy-components/src/atom/input-doublestep/index.js
  packages/@coorpacademy-components/src/atom/input-doublestep/style.css
  packages/@coorpacademy-components/src/atom/input-doublestep/test/fixtures/with-icon.js
  packages/@coorpacademy-components/src/atom/input-doublestep/test/on-change.js
  packages/@coorpacademy-components/src/atom/select/index.js
  packages/@coorpacademy-components/src/molecule/base-modal/index.js
  packages/@coorpacademy-components/src/molecule/brand-create-form/index.js
  packages/@coorpacademy-components/src/molecule/brand-download-box/index.js
  packages/@coorpacademy-components/src/molecule/brand-download-box/style.css
  packages/@coorpacademy-components/src/molecule/brand-form-group/index.js
  packages/@coorpacademy-components/src/molecule/cm-popin/style.css
  packages/@coorpacademy-components/src/molecule/discipline-associated-skills/index.js
  packages/@coorpacademy-components/src/molecule/learning-priority-modal/index.js
  packages/@coorpacademy-components/src/molecule/learning-priority-modal/style.css
  packages/@coorpacademy-components/src/molecule/learning-priority-setup-item/index.js
  packages/@coorpacademy-components/src/molecule/setup-section/index.js
  packages/@coorpacademy-components/src/molecule/setup-section/style.css
  packages/@coorpacademy-components/src/molecule/skill-picker-modal/index.js
  packages/@coorpacademy-components/src/organism/brand-form/index.js
  packages/@coorpacademy-components/src/organism/brand-form/test/fixtures/general-settings.js
  packages/@coorpacademy-components/src/organism/brand-form/test/fixtures/lms.js
  packages/@coorpacademy-components/src/organism/brand-form/test/index.tsx
  packages/@coorpacademy-components/src/organism/brand-learning-priorities/index.js
  packages/@coorpacademy-components/src/organism/brand-learning-priorities/style.css
  packages/@coorpacademy-components/src/organism/brand-learning-priorities/test/fixtures/default.js
  packages/@coorpacademy-components/src/organism/list-item/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/analytics.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/dashboard.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lms-error.js
Labels: pr: :lollipop: Enhancement

#2836 Upgrade Node 18 :outbox_tray:
  .nvmrc
  .travis.yml
  package.json
  packages/@coorpacademy-app-review/package.json
  packages/@coorpacademy-components/package.json
  packages/@coorpacademy-player-services/package.json
  packages/@coorpacademy-player-store/package.json
  packages/@coorpacademy-player-web/package.json
  packages/@coorpacademy-progression-engine/package.json
  packages/@coorpacademy-react-native-animation/package.json
  packages/@coorpacademy-redux-history/package.json
  packages/@coorpacademy-review-services-mocks/package.json
  packages/@coorpacademy-review-services/package.json
  yarn.lock
Labels: pr: Upgrades :outbox_tray:

#2890 Upgrade Node to v20.18.0
  .nvmrc
  .travis.yml
  package.json
  yarn.lock
Labels: Upgrades :outbox_tray:

#2891 CLXP-72 update minor UI feedback
  packages/@coorpacademy-components/src/molecule/playlist-detail-cover/index.js
  packages/@coorpacademy-components/src/template/playlist-detail/style.css
Labels: pr: :lollipop: Enhancement
