Repository CoorpAcademy/components, pull requests merged in 2024-05, with the labels that each got.

#2851 Replace colorjs with css convert
  packages/@coorpacademy-components/src/atom/chip/index.js
  packages/@coorpacademy-components/src/atom/chip/test/calculate-hovered-selected-color.js
  packages/@coorpacademy-components/src/atom/icon/index.js
  packages/@coorpacademy-components/src/atom/icon/test/get-foreground-color.test.js
Labels: pr: :bug: Bug Fix

#2853 fix course title rendering in popin-end
  packages/@coorpacademy-components/src/template/app-player/popin-header/style.css
Labels: bug

#2852 CLXP-40 My Learning Template
  doc/publish.md
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/atom/button-link/index.tsx
  packages/@coorpacademy-components/src/atom/button-link/types.ts
  packages/@coorpacademy-components/src/atom/icon/index.js
  packages/@coorpacademy-components/src/atom/input-search/style.css
  packages/@coorpacademy-components/src/molecule/learner-skill-card/index.js
  packages/@coorpacademy-components/src/molecule/learning-profile-radar-chart/index.tsx
  packages/@coorpacademy-components/src/molecule/learning-profile-radar-chart/style.css
  packages/@coorpacademy-components/src/molecule/learning-profile-radar-chart/test/dot-click.tsx
  packages/@coorpacademy-components/src/molecule/learning-profile-radar-chart/test/label-click.tsx
  packages/@coorpacademy-components/src/molecule/learning-profile-radar-chart/types.ts
  packages/@coorpacademy-components/src/molecule/skill-picker-modal/index.js
  packages/@coorpacademy-components/src/molecule/skills-chart-side-information-panel/style.css
  packages/@coorpacademy-components/src/organism/review-no-skills/index.js
  packages/@coorpacademy-components/src/organism/review-no-skills/prop-types.ts
  packages/@coorpacademy-components/src/organism/review-no-skills/style.css
  packages/@coorpacademy-components/src/template/my-learning/index.js
  packages/@coorpacademy-components/src/template/my-learning/style.css
  packages/@coorpacademy-components/src/template/my-learning/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/my-learning/test/fixtures/empty-skill-focus.js
  packages/@coorpacademy-components/src/template/my-learning/test/fixtures/no-learner-feature.js
  packages/@coorpacademy-components/src/template/my-learning/test/fixtures/no-review-skill.js
  packages/@coorpacademy-components/src/util/search-value-included.js
  packages/@coorpacademy-components/src/util/test/search-value-included.js
Labels: pr: :rocket: New feature
