Repository CoorpAcademy/components, pull requests merged in 2024-11, with the labels that each got.

#2897 CLXP-173 Improve the design of the "all certifications" page
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/atom/title/index.js
  packages/@coorpacademy-components/src/atom/title/style.css
  packages/@coorpacademy-components/src/molecule/certification-card/index.js
  packages/@coorpacademy-components/src/molecule/certification-card/style.css
  packages/@coorpacademy-components/src/molecule/certification-card/test/fixtures/complete-progress.js
  packages/@coorpacademy-components/src/molecule/certification-card/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/certification-card/test/fixtures/no-progress.js
  packages/@coorpacademy-components/src/template/certifications/index.js
  packages/@coorpacademy-components/src/template/certifications/style.css
  packages/@coorpacademy-components/src/template/certifications/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/certifications/test/fixtures/no-sort.js
  packages/@coorpacademy-components/src/template/skill-detail/all-courses.js
Labels: pr: :rocket: New feature

#2898 add password field on CM
  packages/@coorpacademy-components/src/atom/input-text/index.js
  packages/@coorpacademy-components/src/atom/input-text/test/fixtures/password.js
  packages/@coorpacademy-components/src/molecule/brand-form-group/index.js
  packages/@coorpacademy-components/src/molecule/brand-form-group/test/fixtures/sso.js
  packages/@coorpacademy-components/src/molecule/setup-slider/index.js
  packages/@coorpacademy-components/src/molecule/setup-slider/test/fixtures/without-upload-image.js
  packages/@coorpacademy-components/src/organism/brand-form/test/fixtures/lms.js
Labels: pr: :lollipop: Enhancement

#2899 Clxp 71 v2
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/atom/input-search/index.js
  packages/@coorpacademy-components/src/molecule/progress-wrapper/index.js
  packages/@coorpacademy-components/src/molecule/progress-wrapper/style.css
  packages/@coorpacademy-components/src/molecule/progress-wrapper/test/fixtures/complete.js
  packages/@coorpacademy-components/src/molecule/progress-wrapper/test/fixtures/in-progress.js
  packages/@coorpacademy-components/src/molecule/progress-wrapper/test/fixtures/no-badge.js
  packages/@coorpacademy-components/src/molecule/search-form/index.js
  packages/@coorpacademy-components/src/template/certification-detail/index.js
  packages/@coorpacademy-components/src/template/certification-detail/style.css
  packages/@coorpacademy-components/src/template/certification-detail/test/fixtures/complete.js
  packages/@coorpacademy-components/src/template/certification-detail/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/skill-detail/all-courses.js
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement
