Repository CoorpAcademy/components, pull requests merged in 2024-07, with the labels that each got.

#2862 My learning score processing enhancement
  packages/@coorpacademy-components/src/template/my-learning/index.js
  packages/@coorpacademy-components/src/template/my-learning/test/fixtures/default.js
Labels: pr: :lollipop: Enhancement

#2863 CLXP-56 [Technical] Add the ability to change language in the storybook
  packages/@coorpacademy-components/.storybook/main.js
  packages/@coorpacademy-components/.storybook/preview.js
  packages/@coorpacademy-components/package.json
  packages/@coorpacademy-components/src/molecule/learner-skill-card/index.js
  packages/@coorpacademy-components/src/molecule/learner-skill-card/style.css
  yarn.lock
Labels: enhancement

#2864 [Fix] see more button on discipline page
  packages/@coorpacademy-components/src/molecule/discipline-header/index.js
Labels: pr: :bug: Bug Fix

#2865 Discipline associated skills: truncate for non-focused associated skills
  packages/@coorpacademy-components/src/molecule/discipline-associated-skills/index.js
  packages/@coorpacademy-components/src/molecule/discipline-associated-skills/style.css
  packages/@coorpacademy-components/src/template/common/discipline/test/fixtures/with-associated-skills.js
Labels: pr: :lollipop: Enhancement

#2866 [fix] colapse/expand description
  packages/@coorpacademy-components/src/molecule/discipline-header/index.js
Labels: bug

#2868 Prevent My learning template to crash when skill have no stats
  packages/@coorpacademy-components/src/molecule/learner-skill-card/index.js
  packages/@coorpacademy-components/src/template/my-learning/index.js
Labels: bug
