Repository CoorpAcademy/components, pull requests merged in 2025-01, with the labels that each got.

#2907 display filters even if there is no results for the current search
  packages/@coorpacademy-components/package.json
  packages/@coorpacademy-components/src/template/certification-detail/index.js
  packages/@coorpacademy-components/src/template/certification-detail/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/playlist-detail/index.js
  packages/@coorpacademy-components/src/template/playlist-detail/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/skill-detail/all-courses.js
  packages/@coorpacademy-components/src/template/skill-detail/index.js
  packages/@coorpacademy-components/src/template/skill-detail/test/fixtures/default.js
  yarn.lock
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement

#2909 Cplx 192 2
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/molecule/certification-card/index.js
  packages/@coorpacademy-components/src/molecule/certification-card/style.css
  packages/@coorpacademy-components/src/molecule/certification-card/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/progress-wrapper/index.js
  packages/@coorpacademy-components/src/molecule/progress-wrapper/style.css
  packages/@coorpacademy-components/src/molecule/progress-wrapper/test/fixtures/complete.js
  packages/@coorpacademy-components/src/template/certification-detail/index.js
  packages/@coorpacademy-components/src/template/certification-detail/style.css
  packages/@coorpacademy-components/src/template/certification-detail/test/fixtures/complete.js
  packages/@coorpacademy-components/src/template/certification-detail/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/certifications/index.js
  packages/@coorpacademy-components/src/template/certifications/style.css
  packages/@coorpacademy-components/src/template/playlist-detail/index.js
  packages/@coorpacademy-components/src/template/playlist-detail/style.css
  packages/@coorpacademy-components/src/template/playlist-detail/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/playlist-detail/test/fixtures/fallback-image.js
  packages/@coorpacademy-components/src/template/skill-detail/index.js
  packages/@coorpacademy-components/src/template/skill-detail/test/fixtures/default.js
Labels: enhancement, pr: :bug: Bug Fix

#2912 Add go1 LMS configuration template
  packages/@coorpacademy-components/src/atom/input-switch/style.css
  packages/@coorpacademy-components/src/organism/brand-form/test/fixtures/lms.js
Labels: enhancement

#2913 Fix broken deployment on travis :rescue_worker_helmet:
  .travis.yml
Labels: pr: :bug: Bug Fix

#2917 Clxp 193 v4
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/atom/input-switch/style.css
  packages/@coorpacademy-components/src/molecule/banner/index.js
  packages/@coorpacademy-components/src/molecule/banner/style.css
  packages/@coorpacademy-components/src/molecule/banner/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/banner/test/fixtures/hidden-error-banner.js
  packages/@coorpacademy-components/src/molecule/banner/test/fixtures/info-banner.js
  packages/@coorpacademy-components/src/organism/cards-grid/test/fixtures/catalog.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/bulk-inspect-with-popin.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/bulk-inspect.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/cohort-error.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/general-settings-success.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lms-error.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lms-success.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lookandfeel-error.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/lookandfeel-success.js
  packages/@coorpacademy-components/src/template/playlist-detail/index.js
  packages/@coorpacademy-components/src/template/playlist-detail/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/skill-detail/all-courses.css
  packages/@coorpacademy-components/src/template/skill-detail/all-courses.js
  packages/@coorpacademy-components/src/template/skill-detail/index.js
  packages/@coorpacademy-components/src/template/skill-detail/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/skill-detail/test/fixtures/no-focused-and-review-skill.js
  packages/@coorpacademy-components/src/template/skill-detail/test/fixtures/no-questions-to-review.js
  packages/@coorpacademy-components/src/variables/colors.ts
Labels: pr: :bug: Bug Fix, pr: :lollipop: Enhancement
