Repository CoorpAcademy/components, pull requests merged in 2025-04, with the labels that each got.

#2952 CLXP-248: Create Skill Edition page
  packages/@coorpacademy-components/src/atom/title/index.js
  packages/@coorpacademy-components/src/atom/title/style.css
  packages/@coorpacademy-components/src/atom/title/test/fixtures/form-group-title-required.js
  packages/@coorpacademy-components/src/atom/title/types.ts
  packages/@coorpacademy-components/src/molecule/icon-preview/index.tsx
  packages/@coorpacademy-components/src/molecule/icon-preview/style.css
  packages/@coorpacademy-components/src/molecule/icon-preview/test/fixtures/default.js
  packages/@coorpacademy-components/src/molecule/icon-preview/test/fixtures/default.ts
  packages/@coorpacademy-components/src/molecule/icon-preview/types.ts
  packages/@coorpacademy-components/src/organism/header-with-actions/index.tsx
  packages/@coorpacademy-components/src/organism/icon-editor/index.js
  packages/@coorpacademy-components/src/organism/icon-editor/index.tsx
  packages/@coorpacademy-components/src/organism/icon-editor/style.css
  packages/@coorpacademy-components/src/organism/icon-editor/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/icon-editor/test/fixtures/empty-color.ts
  packages/@coorpacademy-components/src/organism/icon-editor/test/fixtures/invalid-color.ts
  packages/@coorpacademy-components/src/organism/icon-editor/types.ts
  packages/@coorpacademy-components/src/organism/list-item/style.css
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/content-skill-empty.js
  packages/@coorpacademy-components/src/organism/skill-edition/index.tsx
  packages/@coorpacademy-components/src/organism/skill-edition/style.css
  packages/@coorpacademy-components/src/organism/skill-edition/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/skill-edition/test/fixtures/draft.ts
  packages/@coorpacademy-components/src/organism/skill-edition/types.ts
  packages/@coorpacademy-components/src/organism/title-and-input/index.tsx
  packages/@coorpacademy-components/src/organism/title-and-input/test/fixtures/icon-editor-and-title.js
  packages/@coorpacademy-components/src/organism/title-and-input/test/fixtures/input-text-and-title.js
  packages/@coorpacademy-components/src/organism/title-and-input/test/fixtures/input-textarea-and-title.js
  packages/@coorpacademy-components/src/organism/title-and-input/types.ts
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/skill-edition.js
Labels: pr: :rocket: New feature

#2956 CSS - wording modules part 1
  packages/@coorpacademy-components/locales/en/global.json
Labels: pr: Wording :bookmark_tabs:

#2955 CLXP-203: Add content modal
  packages/@coorpacademy-components/src/atom/button-link/style.css
  packages/@coorpacademy-components/src/molecule/base-modal/index.js
  packages/@coorpacademy-components/src/molecule/base-modal/style.css
  packages/@coorpacademy-components/src/organism/content-skill-modal/index.tsx
  packages/@coorpacademy-components/src/organism/content-skill-modal/style.css
  packages/@coorpacademy-components/src/organism/content-skill-modal/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/content-skill-modal/test/fixtures/empty-search.ts
  packages/@coorpacademy-components/src/organism/content-skill-modal/test/index.js
  packages/@coorpacademy-components/src/organism/content-skill-modal/types.ts
  packages/@coorpacademy-components/src/organism/filter-checkbox-and-search/index.tsx
  packages/@coorpacademy-components/src/organism/filter-checkbox-and-search/style.css
  packages/@coorpacademy-components/src/organism/filter-checkbox-and-search/test/fixtures/empty-search.ts
  packages/@coorpacademy-components/src/organism/filter-checkbox-and-search/test/on-click.tsx
  packages/@coorpacademy-components/src/variables/colors.ts
Labels: pr: :rocket: New feature

#2958 singular support in certification detail page
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/molecule/progress-wrapper/index.js
  packages/@coorpacademy-components/src/template/certification-detail/index.js
Labels: pr: :bug: Bug Fix

#2961 fix bullet point menu
  packages/@coorpacademy-components/src/atom/button-link-icon/index.js
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/index.tsx
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/test/bullet-point-menu-button.tsx
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/test/fixtures/buttons-with-icon.ts
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/test/fixtures/default.ts
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/test/fixtures/multiple-buttons.ts
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/types.ts
  packages/@coorpacademy-components/src/organism/list-item/test/fixtures/published.js
Labels: pr: :bug: Bug Fix

#2962 Modify skillInformation's props in the SkillEdition component
  packages/@coorpacademy-components/src/atom/icon/test/fixtures/default.js
  packages/@coorpacademy-components/src/atom/icon/test/fixtures/medium-preset.js
  packages/@coorpacademy-components/src/atom/icon/test/fixtures/size.js
  packages/@coorpacademy-components/src/atom/icon/test/fixtures/small-preset.js
  packages/@coorpacademy-components/src/atom/icon/test/fixtures/x-large-preset.js
  packages/@coorpacademy-components/src/atom/input-text/test/fixtures/input-color-error.js
  packages/@coorpacademy-components/src/atom/input-text/test/fixtures/input-color.js
  packages/@coorpacademy-components/src/organism/icon-editor/index.tsx
  packages/@coorpacademy-components/src/organism/icon-editor/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/icon-editor/test/fixtures/empty-color.ts
  packages/@coorpacademy-components/src/organism/icon-editor/test/fixtures/invalid-color.ts
  packages/@coorpacademy-components/src/organism/icon-editor/test/fixtures/without-button.ts
  packages/@coorpacademy-components/src/organism/icon-editor/types.ts
  packages/@coorpacademy-components/src/organism/skill-edition/index.tsx
  packages/@coorpacademy-components/src/organism/skill-edition/style.css
  packages/@coorpacademy-components/src/organism/skill-edition/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/skill-edition/test/fixtures/draft.ts
  packages/@coorpacademy-components/src/organism/skill-edition/types.ts
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/custom-skill-edition-icon-picker-modal.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/custom-skill-edition.js
  packages/@coorpacademy-components/src/util/test/validate-color.js
  packages/@coorpacademy-components/src/util/validate-color.js
  packages/@coorpacademy-components/src/variables/colors.ts
Labels: pr: :lollipop: Enhancement
