Repository CoorpAcademy/components, pull requests merged in 2025-05, with the labels that each got.

#2968 add new default review confifiguration
  packages/@coorpacademy-progression-engine/src/config/review.js
  packages/@coorpacademy-progression-engine/src/config/test/get-config-for-progression.js
  packages/@coorpacademy-progression-engine/src/config/test/get-config.js
Labels: enhancement

#2963 minimize props get from the parent (only dynamic)
  packages/@coorpacademy-components/src/molecule/button-menu-action/test/fixtures/default.ts
  packages/@coorpacademy-components/src/molecule/translation-modal/index.js
  packages/@coorpacademy-components/src/organism/list-items/style.css
  packages/@coorpacademy-components/src/organism/skill-edition/index.tsx
  packages/@coorpacademy-components/src/organism/skill-edition/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/skill-edition/test/fixtures/draft.ts
  packages/@coorpacademy-components/src/organism/skill-edition/types.ts
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/custom-skill-dashboard-archived-popin.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/custom-skill-dashboard-published.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/custom-skill-edition-content-modal.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/custom-skill-edition-deleted-popin.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/custom-skill-edition-translation-modal.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/custom-skill-edition.js
Labels: pr: :lollipop: Enhancement, pr: :rocket: New feature

#2954 enhance Skill header
  packages/@coorpacademy-components/src/atom/button-link/index.tsx
  packages/@coorpacademy-components/src/atom/button-link/style.css
  packages/@coorpacademy-components/src/atom/icon/index.tsx
  packages/@coorpacademy-components/src/atom/select-icon/test/fixtures/color.js
  packages/@coorpacademy-components/src/atom/status-item/index.native.tsx
  packages/@coorpacademy-components/src/atom/tag/style.css
  packages/@coorpacademy-components/src/molecule/banner/style.css
  packages/@coorpacademy-components/src/molecule/base-modal/style.css
  packages/@coorpacademy-components/src/molecule/bulk-progress-bar/index.tsx
  packages/@coorpacademy-components/src/molecule/button-menu-action/test/fixtures/default.ts
  packages/@coorpacademy-components/src/molecule/card-congrats/test/fixtures/rank-reverse.ts
  packages/@coorpacademy-components/src/molecule/card-congrats/test/fixtures/star.ts
  packages/@coorpacademy-components/src/molecule/certification-card/index.js
  packages/@coorpacademy-components/src/molecule/cm-popin/types.ts
  packages/@coorpacademy-components/src/molecule/dashboard/cards-list/style.css
  packages/@coorpacademy-components/src/molecule/icon-preview/index.tsx
  packages/@coorpacademy-components/src/molecule/icon-preview/style.css
  packages/@coorpacademy-components/src/molecule/learner-skill-card/index.tsx
  packages/@coorpacademy-components/src/molecule/learner-skill-card/style.css
  packages/@coorpacademy-components/src/molecule/learning-priority-modal/style.css
  packages/@coorpacademy-components/src/molecule/progress-wrapper/index.js
  packages/@coorpacademy-components/src/organism/cards-grid/index.js
  packages/@coorpacademy-components/src/organism/cards-grid/index.tsx
  packages/@coorpacademy-components/src/organism/icon-editor/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/list-item/index.js
  packages/@coorpacademy-components/src/organism/list-item/style.css
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/content-skill-delete.js
  packages/@coorpacademy-components/src/organism/skill-edition/index.tsx
  packages/@coorpacademy-components/src/template/back-office/brand-update/utils.js
  packages/@coorpacademy-components/src/template/my-learning/index.js
  packages/@coorpacademy-components/src/template/skill-detail/all-courses.css
  packages/@coorpacademy-components/src/template/skill-detail/all-courses.tsx
  packages/@coorpacademy-components/src/template/skill-detail/continue-learning.css
  packages/@coorpacademy-components/src/template/skill-detail/continue-learning.tsx
  packages/@coorpacademy-components/src/template/skill-detail/index.js
  packages/@coorpacademy-components/src/template/skill-detail/index.tsx
  packages/@coorpacademy-components/src/template/skill-detail/style.css
  packages/@coorpacademy-components/src/template/skill-detail/test/fixtures/default.ts
  packages/@coorpacademy-components/src/template/skill-detail/test/fixtures/no-description.ts
  packages/@coorpacademy-components/src/template/skill-detail/test/fixtures/no-focused-and-review-skill.ts
  packages/@coorpacademy-components/src/template/skill-detail/test/fixtures/no-questions-to-review.ts
  packages/@coorpacademy-components/src/template/skill-detail/test/fixtures/with-old-switch-value-banner.ts
  packages/@coorpacademy-components/src/variables/colors.css
  packages/@coorpacademy-components/src/variables/colors.ts
  packages/@coorpacademy-components/src/variables/theme.native.ts
  packages/@coorpacademy-components/tsconfig.json
Labels: DO NOT MERGE
