Repository CoorpAcademy/components, pull requests merged in 2025-02, with the labels that each got.

#2920 Microlearning banner fix
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/src/molecule/banner/index.js
  packages/@coorpacademy-components/src/template/certification-detail/test/fixtures/complete-without-rewards.js
  packages/@coorpacademy-components/src/template/playlist-detail/index.js
  packages/@coorpacademy-components/src/template/skill-detail/all-courses.js
  packages/@coorpacademy-components/src/template/skill-detail/index.js
  packages/@coorpacademy-components/src/template/skill-detail/test/fixtures/no-focused-and-review-skill.js
  packages/@coorpacademy-components/src/template/skill-detail/test/fixtures/no-questions-to-review.js
Labels: pr: :lollipop: Enhancement

#2921 Detail pages fix post testing
  packages/@coorpacademy-components/src/molecule/banner/index.js
  packages/@coorpacademy-components/src/molecule/banner/test/fixtures/info-banner-with-old-switch-value.js
  packages/@coorpacademy-components/src/template/certification-detail/index.js
  packages/@coorpacademy-components/src/template/certification-detail/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/playlist-detail/index.js
  packages/@coorpacademy-components/src/template/playlist-detail/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/playlist-detail/test/fixtures/with-no-banner.js
  packages/@coorpacademy-components/src/template/playlist-detail/test/fixtures/with-old-switch-value-banner.js
  packages/@coorpacademy-components/src/template/skill-detail/all-courses.js
  packages/@coorpacademy-components/src/template/skill-detail/index.js
  packages/@coorpacademy-components/src/template/skill-detail/test/fixtures/default.js
  packages/@coorpacademy-components/src/template/skill-detail/test/fixtures/with-old-switch-value-banner.js
Labels: pr: :lollipop: Enhancement

#2922 Update babel accross repo and webpack plugin
  .travis.yml
  packages/@coorpacademy-app-review/package.json
  packages/@coorpacademy-components/.babelrc
  packages/@coorpacademy-components/package.json
  packages/@coorpacademy-css-modules-require-hook/.babelrc
  packages/@coorpacademy-css-modules-require-hook/package.json
  packages/@coorpacademy-history/.babelrc
  packages/@coorpacademy-history/package.json
  packages/@coorpacademy-nova-icons/.babelrc
  packages/@coorpacademy-nova-icons/package.json
  packages/@coorpacademy-player-services/.babelrc
  packages/@coorpacademy-player-services/package.json
  packages/@coorpacademy-player-store/.babelrc
  packages/@coorpacademy-player-store/package.json
  packages/@coorpacademy-player-web/.babelrc
  packages/@coorpacademy-player-web/package.json
  packages/@coorpacademy-progression-engine/.babelrc
  packages/@coorpacademy-progression-engine/package.json
  packages/@coorpacademy-react-adapter-angular/package.json
  packages/@coorpacademy-react-adapter-dust/package.json
  packages/@coorpacademy-react-native-animation/package.json
  packages/@coorpacademy-redux-history/.babelrc
  packages/@coorpacademy-redux-history/package.json
  packages/@coorpacademy-redux-router/package.json
  packages/@coorpacademy-redux-task/package.json
  packages/@coorpacademy-review-services-mocks/.babelrc
  packages/@coorpacademy-review-services-mocks/package.json
  packages/@coorpacademy-review-services/.babelrc
  packages/@coorpacademy-review-services/package.json
  packages/@coorpacademy-translate/package.json
  packages/@coorpacademy-webpack-config/.eslintrc
  packages/@coorpacademy-webpack-config/package.json
  packages/@coorpacademy-webpack-config/src/index.js
  yarn.lock
Labels: Upgrades :outbox_tray:

#2923 Update babel and webpack plugin hotfixes
  packages/@coorpacademy-components/src/variables/colors.css
  packages/@coorpacademy-webpack-config/src/index.js
Labels: pr: :bug: Bug Fix

#2925 add data name + data testid
  packages/@coorpacademy-components/src/molecule/base-modal/index.js
  packages/@coorpacademy-components/src/molecule/draggable-list/index.js
  packages/@coorpacademy-components/src/molecule/learning-priority-setup-item/index.js
  packages/@coorpacademy-components/src/organism/brand-learning-priorities/index.js
  packages/@coorpacademy-components/src/organism/list-item/index.js
Labels: pr: :lollipop: Enhancement

#2926 Introduce a webpack option esModule to support no modules
  packages/@coorpacademy-webpack-config/src/index.js
  packages/@coorpacademy-webpack-config/src/test/index.js
Labels: pr: :bug: Bug Fix

#2927 Tweak access to style kebab cased classname
  packages/@coorpacademy-components/src/atom/battle-opponent/index.tsx
  packages/@coorpacademy-components/src/atom/battle-opponent/style.css
Labels: pr: :bug: Bug Fix
