Repository CoorpAcademy/components, pull requests merged in 2025-03, with the labels that each got.

#2929 Add locales
  packages/@coorpacademy-components/locales/bs/global.json
  packages/@coorpacademy-components/locales/cs/global.json
  packages/@coorpacademy-components/locales/de/global.json
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/locales/es/global.json
  packages/@coorpacademy-components/locales/et/global.json
  packages/@coorpacademy-components/locales/fi/global.json
  packages/@coorpacademy-components/locales/fr/global.json
  packages/@coorpacademy-components/locales/hr/global.json
  packages/@coorpacademy-components/locales/hu/global.json
  packages/@coorpacademy-components/locales/hy/global.json
  packages/@coorpacademy-components/locales/it/global.json
  packages/@coorpacademy-components/locales/ja/global.json
  packages/@coorpacademy-components/locales/ko/global.json
  packages/@coorpacademy-components/locales/nl/global.json
  packages/@coorpacademy-components/locales/pl/global.json
  packages/@coorpacademy-components/locales/pt/global.json
  packages/@coorpacademy-components/locales/ro/global.json
  packages/@coorpacademy-components/locales/ru/global.json
  packages/@coorpacademy-components/locales/sk/global.json
  packages/@coorpacademy-components/locales/sl/global.json
  packages/@coorpacademy-components/locales/sv/global.json
  packages/@coorpacademy-components/locales/th/global.json
  packages/@coorpacademy-components/locales/tl/global.json
  packages/@coorpacademy-components/locales/tr/global.json
  packages/@coorpacademy-components/locales/uk/global.json
  packages/@coorpacademy-components/locales/vi/global.json
  packages/@coorpacademy-components/locales/zh/global.json
  packages/@coorpacademy-components/locales/zh_TW/global.json
Labels: pr: Wording :bookmark_tabs:

#2928 organism multi filter panel component
  packages/@coorpacademy-components/src/atom/chip/index.js
  packages/@coorpacademy-components/src/atom/chip/style.css
  packages/@coorpacademy-components/src/atom/chip/test/fixtures/default.js
  packages/@coorpacademy-components/src/atom/chip/test/fixtures/with-left-icon.js
  packages/@coorpacademy-components/src/atom/chip/test/fixtures/with-subtext.js
  packages/@coorpacademy-components/src/atom/tag/index.js
  packages/@coorpacademy-components/src/atom/tag/style.css
  packages/@coorpacademy-components/src/atom/tag/test/fixtures/info.js
  packages/@coorpacademy-components/src/molecule/multi-filter-panel/index.tsx
  packages/@coorpacademy-components/src/molecule/multi-filter-panel/prop-types.ts
  packages/@coorpacademy-components/src/molecule/multi-filter-panel/style.css
  packages/@coorpacademy-components/src/molecule/multi-filter-panel/test/fixtures/default.ts
  packages/@coorpacademy-components/src/molecule/multi-filter-panel/test/fixtures/no-filters.ts
  packages/@coorpacademy-components/src/molecule/multi-filter-panel/test/fixtures/no-selected-filters.ts
  packages/@coorpacademy-components/src/organism/filter-chip/index.tsx
  packages/@coorpacademy-components/src/organism/filter-chip/prop-types.ts
  packages/@coorpacademy-components/src/organism/filter-chip/style.css
  packages/@coorpacademy-components/src/organism/filter-chip/test/chip-obn-click.tsx
  packages/@coorpacademy-components/src/organism/filter-chip/test/fixtures/all-selected.ts
  packages/@coorpacademy-components/src/organism/filter-chip/test/fixtures/no-selected.ts
  packages/@coorpacademy-components/src/variables/colors.ts
Labels: pr: :lollipop: Enhancement, pr: :rocket: New feature

#2924 CLXP-234: Create header skill custom
  packages/@coorpacademy-components/src/atom/button-link-icon/style.css
  packages/@coorpacademy-components/src/atom/button-link/index.tsx
  packages/@coorpacademy-components/src/atom/button-link/style.css
  packages/@coorpacademy-components/src/atom/button-link/types.ts
  packages/@coorpacademy-components/src/atom/button-menu/index.tsx
  packages/@coorpacademy-components/src/atom/button-menu/style.css
  packages/@coorpacademy-components/src/atom/button-menu/test/fixtures/menu-with-icon.ts
  packages/@coorpacademy-components/src/atom/button-menu/types.ts
  packages/@coorpacademy-components/src/atom/tag/style.css
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/style.css
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/test/fixtures/buttons-with-icon.ts
  packages/@coorpacademy-components/src/organism/header-with-actions/index.tsx
  packages/@coorpacademy-components/src/organism/header-with-actions/style.css
  packages/@coorpacademy-components/src/organism/header-with-actions/test/fixtures/action-without-icon.ts
  packages/@coorpacademy-components/src/organism/header-with-actions/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/header-with-actions/test/fixtures/single-action.ts
  packages/@coorpacademy-components/src/organism/header-with-actions/types.ts
  packages/@coorpacademy-components/src/variables/colors.css
  packages/@coorpacademy-components/src/variables/colors.ts
Labels: pr: :rocket: New feature

#2934 Change case of CTA filter class :camel:
  packages/@coorpacademy-components/src/molecule/filters/index.js
  packages/@coorpacademy-components/src/molecule/filters/style.css
Labels: pr: :bug: Bug Fix

#2935 Fix card visual glitch :memo:
  packages/@coorpacademy-components/src/molecule/card/customer.js
  packages/@coorpacademy-components/src/molecule/card/index.js
Labels: pr: :bug: Bug Fix

#2937 Stop the tweaking with casing of class :no_good:
  packages/@coorpacademy-webpack-config/src/index.js
Labels: pr: :bug: Bug Fix

#2939 button link fix props isRequired
  packages/@coorpacademy-components/src/atom/button-link/types.ts
Labels: enhancement

#2941 CLXP-260: Update `ListItem` component
  packages/@coorpacademy-components/src/atom/checkbox-with-title/index.js
  packages/@coorpacademy-components/src/atom/checkbox-with-title/style.css
  packages/@coorpacademy-components/src/atom/checkbox-with-title/test/fixtures/with-custom-icon.js
  packages/@coorpacademy-components/src/atom/checkbox-with-title/test/fixtures/without-title.js
  packages/@coorpacademy-components/src/organism/list-item/index.js
  packages/@coorpacademy-components/src/organism/list-item/style.css
  packages/@coorpacademy-components/src/organism/list-item/test/fixtures/checkbox-selected.js
  packages/@coorpacademy-components/src/organism/list-item/test/fixtures/checkbox.js
Labels: pr: :lollipop: Enhancement

#2942 CLXP-254: List items search
  packages/@coorpacademy-components/src/organism/list-item/test/fixtures/checkbox-deletable.js
  packages/@coorpacademy-components/src/organism/list-items/index.js
  packages/@coorpacademy-components/src/organism/list-items/style.css
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/content-skill-delete.js
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/content-skill-empty.js
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/content-skill.js
Labels: pr: :rocket: New feature

#2944 CLXP-268: Create `ButtonMenuAction` component for the translation section
  packages/@coorpacademy-components/src/atom/button-menu/index.tsx
  packages/@coorpacademy-components/src/atom/button-menu/style.css
  packages/@coorpacademy-components/src/atom/title/index.js
  packages/@coorpacademy-components/src/atom/title/style.css
  packages/@coorpacademy-components/src/molecule/button-menu-action/index.tsx
  packages/@coorpacademy-components/src/molecule/button-menu-action/style.css
  packages/@coorpacademy-components/src/molecule/button-menu-action/test/button-menu-action.tsx
  packages/@coorpacademy-components/src/molecule/button-menu-action/test/fixtures/default.ts
  packages/@coorpacademy-components/src/molecule/button-menu-action/types.ts
  packages/@coorpacademy-components/src/organism/list-items/index.js
  packages/@coorpacademy-components/src/organism/list-items/style.css
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/content-skill-empty.js
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/translations-empty.js
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/translations.js
  packages/@coorpacademy-components/src/variables/colors.css
  packages/@coorpacademy-components/src/variables/colors.ts
Labels: pr: :rocket: New feature

#2950 Update ignore pattern for translations :white_flag:
  .travis.yml
Labels: pr: :bug: Bug Fix

#2943 Custom skill update: cm popin / menu button / brand update
  packages/@coorpacademy-components/src/atom/button-link-icon/index.js
  packages/@coorpacademy-components/src/atom/button-menu/index.tsx
  packages/@coorpacademy-components/src/atom/button-menu/style.css
  packages/@coorpacademy-components/src/atom/button-menu/test/fixtures/menu-themes.ts
  packages/@coorpacademy-components/src/atom/button-menu/types.ts
  packages/@coorpacademy-components/src/atom/button-menu/utils.ts
  packages/@coorpacademy-components/src/atom/icon/index.js
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/index.tsx
  packages/@coorpacademy-components/src/molecule/bullet-point-menu-button/types.ts
  packages/@coorpacademy-components/src/molecule/cm-popin/index.js
  packages/@coorpacademy-components/src/molecule/cm-popin/style.css
  packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/custom-skill-archive.js
  packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/custom-skill-delete.js
  packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/dangerous.js
  packages/@coorpacademy-components/src/molecule/cm-popin/types.ts
  packages/@coorpacademy-components/src/organism/list-item/index.js
  packages/@coorpacademy-components/src/organism/list-item/test/fixtures/custom-skill.js
  packages/@coorpacademy-components/src/organism/list-items/index.js
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/custom-skill.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/custom-skill-published-popin.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/utils.js
  packages/@coorpacademy-components/src/variables/colors.css
  packages/@coorpacademy-components/src/variables/colors.ts
Labels: pr: :lollipop: Enhancement
