Repository CoorpAcademy/components, pull requests merged in 2025-06, with the labels that each got.

#2990 forum support on external course page
  packages/@coorpacademy-components/src/molecule/discipline-scope/index.js
  packages/@coorpacademy-components/src/template/common/discipline/index.js
  packages/@coorpacademy-components/src/template/common/discipline/test/fixtures/external-course.js
Labels: bug

#2989 Clxp 310
  packages/@coorpacademy-components/src/atom/checkbox-with-title/index.js
  packages/@coorpacademy-components/src/atom/checkbox-with-title/test/fixtures/without-checkbox.js
  packages/@coorpacademy-components/src/atom/tag/index.js
  packages/@coorpacademy-components/src/atom/tag/test/fixtures/course-with-default-icon-props.js
  packages/@coorpacademy-components/src/atom/tag/test/fixtures/with-left-icon.js
  packages/@coorpacademy-components/src/atom/tag/test/fixtures/with-right-icon.js
  packages/@coorpacademy-components/src/molecule/multi-filter-panel/index.tsx
  packages/@coorpacademy-components/src/organism/filter-checkbox-and-search/index.tsx
  packages/@coorpacademy-components/src/organism/filter-checkbox-and-search/props-types.ts
  packages/@coorpacademy-components/src/organism/filter-checkbox-and-search/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/filter-checkbox-and-search/test/fixtures/empty-search.ts
  packages/@coorpacademy-components/src/organism/filter-checkbox-and-search/test/fixtures/without-search.ts
  packages/@coorpacademy-components/src/organism/list-items/test/fixtures/content-skill.js
  packages/@coorpacademy-components/src/organism/skill-edition/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/skill-edition/types.ts
Labels: pr: :lollipop: Enhancement

#2967 CLXP-302 - Modify the header for the skill edition page
  packages/@coorpacademy-components/src/molecule/cm-popin/test/fixtures/custom-skill-draft.js
  packages/@coorpacademy-components/src/organism/header-with-actions/index.tsx
  packages/@coorpacademy-components/src/organism/header-with-actions/test/fixtures/action-without-icon.ts
  packages/@coorpacademy-components/src/organism/header-with-actions/test/fixtures/default.ts
  packages/@coorpacademy-components/src/organism/header-with-actions/test/fixtures/single-action.ts
  packages/@coorpacademy-components/src/organism/header-with-actions/types.ts
  packages/@coorpacademy-components/src/organism/skill-edition/index.tsx
  packages/@coorpacademy-components/src/organism/skill-edition/test/fixtures/draft-deletable-content-items.ts
  packages/@coorpacademy-components/src/template/back-office/brand-update/index.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/style.css
  packages/@coorpacademy-components/src/template/back-office/brand-update/test/fixtures/custom-skill-edition-draft-popin.js
  packages/@coorpacademy-components/src/template/back-office/brand-update/utils.js
Labels: pr: :lollipop: Enhancement

#2999 esante-formation - modification wording Attestation
  packages/@coorpacademy-components/locales/en/global.json
  packages/@coorpacademy-components/locales/fr/global.json
Labels: pr: Wording :bookmark_tabs:
